"""
  Copyright 2023 abnoname
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
"""

import Open3Ecodecs
from Open3Ecodecs import *

# Datapoints sourced from ViGuide Demo Mode:
# https://viguide.viessmann.com/installations/10000017?gatewaySerial=7736170-gw-serial-17&deviceSerial=7720533-device-serial

dataIdentifiersVcal = {
    # HPMU Führungsgerät Interner CAN-BUS: 1
    # Heat Pump Management Unit 
    0x680 : {
        "name": "HPMU", "tx": 0x680, "rx": 0x690, 
        "dids" : 
        {
            256	: O3EComplexType(36, "BusIdentification", [O3EByteVal(1, "BusAddress"), O3EByteVal(1, "BusType"),O3EByteVal(1, "DeviceProperty"),O3EByteVal(1, "DeviceFunction"), O3ESoftVers(8, "SW-Version"), O3ESoftVers(8, "HW-Version"),O3EUtf8(16, "VIN")]),
            257	: O3EDtcList(122, "StatusDtcList", dtcType ="Status"),
            258	: O3EDtcList(122, "StatusDtcHistory", dtcType ="Status" ),
            259	: O3EDtcList(122, "InfoDtcList", dtcType ="Info"),
            260	: O3EDtcList(122, "InfoDtcHistory", dtcType ="Info"),
            261	: O3EDtcList(122, "ServiceDtcList", dtcType ="Service"),
            262	: O3EDtcList(122, "ServiceDtcHistory", dtcType ="Service"),
            263	: O3EDtcList(122, "WarningDtcList", dtcType ="Warning"),
            264	: O3EDtcList(124, "WarningDtcHistory", dtcType ="Warning", subType="History" ),
            265	: O3EDtcList(122, "ErrorDtcList",dtcType ="Error"),
            266	: O3EDtcList(124, "ErrorDtcHistory", dtcType ="Error", subType="History"),
            268	: O3EInt16(9, "FlowTemperatureSensor", signed=True),
            269	: O3EInt16(9, "ReturnTemperatureSensor", signed=True),
            271	: O3EInt16(9, "DomesticHotWaterSensor", signed=True),
            272	: RawCodec(10, "DomesticHotWaterFlowSensor"),
            274	: O3EInt16(9, "OutsideTemperatureSensor", signed=True),
            279	: O3EInt16(9, "BufferMidTemperatureSensor", signed=True),
            282	: O3EInt16(9, "HydraulicSeparatorTemperatureSensor", signed=True),
            284	: O3EInt16(9, "MixerOneCircuitFlowTemperatureSensor", signed=True),
            285	: O3EInt16(9, "MixerOneCircuitReturnTemperatureSensor", signed=True),
            286	: O3EInt16(9, "MixerTwoCircuitFlowTemperatureSensor", signed=True),
            287	: O3EInt16(9, "MixerTwoCircuitReturnTemperatureSensor", signed=True),
            288	: O3EInt16(9, "MixerThreeCircuitFlowTemperatureSensor", signed=True),
            289	: O3EInt16(9, "MixerThreeCircuitReturnTemperatureSensor", signed=True),
            290	: O3EInt16(9, "MixerFourCircuitFlowTemperatureSensor", signed=True),
            291	: O3EInt16(9, "MixerFourCircuitReturnTemperatureSensor", signed=True),
            318	: O3EInt16(9, "WaterPressureSensor"),
            320	: O3EInt16(9, "PrimaryHeatExchangerLiquidTemperatureSensor", signed=True),
            321	: O3EInt16(9, "CompressorInletTemperatureSensor", signed=True),
            322 : O3EInt16(9, "CompressorInletPressureSensor", scale = 100),
            324	: O3EInt16(9, "CompressorOutletTemperatureSensor", signed=True),
            325	: O3EInt16(9, "CompressorOutletPressureSensor", scale = 100),
            334	: O3EInt16(9, "MixerOneCircuitRoomTemperatureSensor", signed=True),
            335	: O3EInt16(9, "MixerTwoCircuitRoomTemperatureSensor", signed=True),
            336	: O3EInt16(9, "MixerThreeCircuitRoomTemperatureSensor", signed=True),
            337	: O3EInt16(9, "MixerFourCircuitRoomTemperatureSensor", signed=True),
            354	: O3EInt8(1, "PrimaryHeatExchangerBaseHeater"),
            355	: O3EInt16(9, "SecondaryHeatExchangerLiquidTemperatureSensor", signed=True),
            377	: RawCodec(16, "ViessmannIdentificationNumber"),
            381	: O3EInt8(4, "CentralHeatingPump", offset = 1),
            382:  O3EComplexType(5, "UnitsAndFormats", [O3EByteVal(1, "Maßeinheit"), O3EByteVal(1, "Datumsformat"),O3EByteVal(1, "Zeitformat"),O3EByteVal(1, "Zeitzone"),]),
            389	: O3EInt8(1, "ElectronicExpansionValveOneCurrentPositionPercent"),
            391	: O3EInt8(1, "ElectronicExpansionValveTwoCurrentPositionPercent"),
            396	: O3EInt16(2, "DomesticHotWaterTemperatureSetpoint", signed=True),
            401	: O3EInt8(5, "MixerOneCircuitPump", scale = 1, offset = 2),
            402	: O3EInt8(5, "MixerTwoCircuitPump", scale = 1, offset = 2),
            403	: O3EInt8(5, "MixerThreeCircuitPump", scale = 1, offset = 2),
            404	: O3EInt8(5, "MixerFourCircuitPump", scale = 1, offset = 2),
            424	: O3EInt16(9, "MixerOneCircuitRoomTemperatureSetpoint", signed=True),
            426	: O3EInt16(9, "MixerTwoCircuitRoomTemperatureSetpoint", signed=True),
            428	: O3EInt16(9, "MixerThreeCircuitRoomTemperatureSetpoint", signed=True),
            430	: O3EInt16(9, "MixerFourCircuitRoomTemperatureSetpoint", signed=True),
            475	: RawCodec(2, "MixerOneCircuitThreeWayValvePositionPercent"),
            476	: RawCodec(2, "MixerTwoCircuitThreeWayValvePositionPercent"),
            477	: RawCodec(2, "MixerThreeCircuitThreeWayValvePositionPercent"),
            478	: RawCodec(2, "MixerFourCircuitThreeWayValvePositionPercent"),
            491	: RawCodec(2, "DomesticHotWaterCirculationPump"),
            497	: RawCodec(5, "DomesticHotWaterCirculationPumpMode"),
            500	: RawCodec(2, "CentralHeatDemandExternalAc"),
            503	: RawCodec(2, "ScaldProtection"),
            504	: RawCodec(14, "DomesticHotWaterSetpointMetaData"),
            505	: RawCodec(3, "Date"),
            506	: RawCodec(3, "Time"),
            507	: RawCodec(4, "UniversalTimeCoordinated"),
            508	: O3EInt8(1, "UniversalTimeCoordinatedOffset"),
            510	: O3EInt8(1, "Language"),
            511	: RawCodec(8, "HolidayPhase"),
            512	: RawCodec(8, "HolidayAtHomePhase"),
            513	: RawCodec(8, "HolidayPhaseCircuitOne"),
            514	: RawCodec(8, "HolidayAtHomePhaseCircuitOne"),
            515	: RawCodec(8, "HolidayPhaseCircuitTwo"),
            516	: RawCodec(8, "HolidayAtHomePhaseCircuitTwo"),
            517	: RawCodec(8, "HolidayPhaseCircuitThree"),
            518	: RawCodec(8, "HolidayAtHomePhaseCircuitThree"),
            519	: RawCodec(8, "HolidayPhaseCircuitFour"),
            520	: RawCodec(8, "HolidayAtHomePhaseCircuitFour"),
            531	: O3EOperationState(2, "DomesticHotWaterOperationState"),
            534	: RawCodec(2, "DomesticHotWaterPumpPostRunTime"),
            537	: O3EOperationState(2, "ExternalMixerOneCircuitTargetOperationMode"),
            538	: O3EOperationState(2, "ExternalDomesticHotWaterTargetOperationMode"),
            543	: RawCodec(4, "SmartGridReadyConsolidator"),
            548	: RawCodec(24, "EnergyConsumptionCentralHeating"),
            565	: RawCodec(24, "EnergyConsumptionDomesticHotWater"),
            566	: RawCodec(24, "EnergyConsumptionCooling"),
            572	: RawCodec(3, "SetDefaultValuesDate"),
            573	: RawCodec(2, "RemoteReset"),
            576	: RawCodec(3, "SetDeliveryStatusDate"),
            580	: RawCodec(8, "SoftwareVersion"),
            581	: RawCodec(8, "HardwareVersion"),
            592	: RawCodec(6, "MacAddressLan"),
            593	: RawCodec(6, "GatewayMac"),
            602	: O3EInt8(1, "GatewayRemoteLocalNetworkStatus"),
            603	: O3EInt8(1, "GatewayApEnable"),
            604 : O3EComplexType(76, "GatewayApDataSet", [O3EUtf8(32, "SSID Access Point"), O3EUtf8(40, "Password Access Point"),O3EIp4Addr(4, "IP-Address Access Point")]),
            607 : O3EComplexType(20, "GatewayRemoteIp", [O3EIp4Addr(4, "WLAN IP"), O3EIp4Addr(4, "SubnetMask"),O3EIp4Addr(4, "Gateway IP"),O3EIp4Addr(4, "DNS Server 1"),O3EIp4Addr(4, "DNS Server 2")]),
            616	: O3EInt8(1, "GatewayRemoteEnable"),
            618	: O3EInt8(1, "GatewayRemoteIpStatic"),
            619	: RawCodec(2, "GatewayRemoteScanNetwork"),
            620	: O3EInt8(1, "DiagnosticServiceConnectionStatus"),
            621	: RawCodec(181, "ObjectContactDetails"),
            622	: RawCodec(181, "CustomerDetails"),
            623 : O3EComplexType(181, "ServiceEngineer", [O3EUtf8(20, "Name"),O3EUtf8(15, "Forename"),O3EUtf8(20, "Street"),O3EUtf8(10, "Street add."),O3EUtf8(7, "ZIP"),O3EUtf8(15, "Region"),O3EUtf8(15, "City"),O3EUtf8(16, "Phone"),O3EUtf8(16, "Mobile"),O3EUtf8(20, "Email"),O3EUtf8(1, "Country"),O3EUtf8(15, "Identification Number")]), #Länge Email und Identnummer nicht testbar ggf. ändern
            624 : O3EComplexType(181, "TechnicalSupport", [O3EUtf8(20, "Name"),O3EUtf8(15, "Forename"),O3EUtf8(20, "Street"),O3EUtf8(10, "Street add."),O3EUtf8(7, "ZIP"),O3EUtf8(15, "Region"),O3EUtf8(15, "City"),O3EUtf8(16, "Phone"),O3EUtf8(16, "Mobile"),O3EUtf8(20, "Email"),O3EUtf8(1, "Country"),O3EUtf8(15, "Identification Number")]), #Länge Email und Identnummer nicht testbar ggf. ändern
            625	: RawCodec(26, "ObjectDetails"),
            627	: RawCodec(40, "CentralHeatingOneCircuitName"),
            628	: RawCodec(40, "CentralHeatingTwoCircuitName"),
            629	: RawCodec(40, "CentralHeatingThreeCircuitName"),
            630	: RawCodec(40, "CentralHeatingFourCircuitName"),
            645	: O3EInt8(1, "GenericAnalogDigitalAccessoryOneModulFunction"),
            646	: O3EInt8(1, "GenericAnalogDigitalAccessoryTwoModulFunction"),
            647	: O3EInt8(1, "GenericAnalogDigitalAccessoryThreeModulFunction"),
            648	: O3EInt8(1, "GenericAnalogDigitalAccessoryFourModulFunction"),
            649	: O3EInt8(1, "GenericAnalogDigitalAccessoryFiveModulFunction"),
            650	: O3EInt8(1, "GenericDigitalAccessoryOneModulFunction"),
            651	: O3EInt8(1, "GenericDigitalAccessoryTwoModulFunction"),
            652	: O3EInt8(1, "GenericDigitalAccessoryThreeModulFunction"),
            680	: RawCodec(123, "EnergyMeter"),
            691	: RawCodec(57, "DomesticHotWaterTimeScheduleMonday"),
            692	: RawCodec(57, "DomesticHotWaterTimeScheduleTuesday"),
            693	: RawCodec(57, "DomesticHotWaterTimeScheduleWednesday"),
            694	: RawCodec(57, "DomesticHotWaterTimeScheduleThursday"),
            695	: RawCodec(57, "DomesticHotWaterTimeScheduleFriday"),
            696	: RawCodec(57, "DomesticHotWaterTimeScheduleSaturday"),
            697	: RawCodec(57, "DomesticHotWaterTimeScheduleSunday"),
            726	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleMonday"),
            727	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleTuesday"),
            728	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleWednesday"),
            729	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleThursday"),
            730	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleFriday"),
            731	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleSaturday"),
            732	: RawCodec(57, "DomesticHotWaterCirculationTimeScheduleSunday"),
            761	: RawCodec(57, "MixerOneCircuitTimeScheduleMonday"),
            762	: RawCodec(57, "MixerOneCircuitTimeScheduleTuesday"),
            763	: RawCodec(57, "MixerOneCircuitTimeScheduleWednesday"),
            764	: RawCodec(57, "MixerOneCircuitTimeScheduleThursday"),
            765	: RawCodec(57, "MixerOneCircuitTimeScheduleFriday"),
            766	: RawCodec(57, "MixerOneCircuitTimeScheduleSaturday"),
            767	: RawCodec(57, "MixerOneCircuitTimeScheduleSunday"),
            768	: RawCodec(57, "MixerTwoCircuitTimeScheduleMonday"),
            769	: RawCodec(57, "MixerTwoCircuitTimeScheduleTuesday"),
            770	: RawCodec(57, "MixerTwoCircuitTimeScheduleWednesday"),
            771	: RawCodec(57, "MixerTwoCircuitTimeScheduleThursday"),
            772	: RawCodec(57, "MixerTwoCircuitTimeScheduleFriday"),
            773	: RawCodec(57, "MixerTwoCircuitTimeScheduleSaturday"),
            774	: RawCodec(57, "MixerTwoCircuitTimeScheduleSunday"),
            775	: RawCodec(57, "MixerThreeCircuitTimeScheduleMonday"),
            776	: RawCodec(57, "MixerThreeCircuitTimeScheduleTuesday"),
            777	: RawCodec(57, "MixerThreeCircuitTimeScheduleWednesday"),
            778	: RawCodec(57, "MixerThreeCircuitTimeScheduleThursday"),
            779	: RawCodec(57, "MixerThreeCircuitTimeScheduleFriday"),
            780	: RawCodec(57, "MixerThreeCircuitTimeScheduleSaturday"),
            781	: RawCodec(57, "MixerThreeCircuitTimeScheduleSunday"),
            782	: RawCodec(57, "MixerFourCircuitTimeScheduleMonday"),
            783	: RawCodec(57, "MixerFourCircuitTimeScheduleTuesday"),
            784	: RawCodec(57, "MixerFourCircuitTimeScheduleWednesday"),
            785	: RawCodec(57, "MixerFourCircuitTimeScheduleThursday"),
            786	: RawCodec(57, "MixerFourCircuitTimeScheduleFriday"),
            787	: RawCodec(57, "MixerFourCircuitTimeScheduleSaturday"),
            788	: RawCodec(57, "MixerFourCircuitTimeScheduleSunday"),
            873	: RawCodec(2, "LegionellaProtectionActivation"),
            874	: O3EInt16(3, "LegionellaProtectionTargetTemperatureSetpoint"),
            875	: RawCodec(2, "LegionellaProtectionStartTime"),
            876	: O3EInt8(1, "LegionellaProtectionWeekday"),
            877	: RawCodec(3, "LegionellaProtectionLastSuccessfulStartTime"),
            878	: O3EInt8(1, "LegionellaProtectionLastSuccessfulWeekday"),
            880	: O3EHeatingCurve(4, "MixerOneCircuitCentralHeatingCurve"),
            881	: O3EHeatingCurve(4, "MixerTwoCircuitCentralHeatingCurve"),
            882	: O3EHeatingCurve(4, "MixerThreeCircuitCentralHeatingCurve"),
            883	: O3EHeatingCurve(4, "MixerFourCircuitCentralHeatingCurve"),
            896	: RawCodec(2, "OutsideTemperatureOffset"),
            897	: O3EInt8(1, "ScreedDryingProfileActivation"),
            898	: O3EInt8(1, "RemainingFloorDryingDays"),
            900	: O3EInt8(1, "GatewayRemoteSignalStrength"),
            901	: O3EInt8(1, "ServiceManagerIsRequired"),
            902	: O3EInt8(1, "MalfunctionIdentification"),
            903	: RawCodec(4, "DisplaySettings"),
            908	: O3EInt8(1, "ExternalFaultSignal"),
            909	: O3EInt8(1, "ExternalFaultSignalInput"),
            912	: RawCodec(5, "DaylightSavingTimeActive"),
            918	: O3EInt8(1, "TradeFairMode"),
            919	: RawCodec(2, "OutsideTemperatureDampingFactor"),
            921	: O3EOperationState(2, "ExternalAccessInProgress"),
            923	: RawCodec(8, "RealTimeClockStatus"),
            924	: O3EInt8(1, "StartUpWizard"),
            925	: RawCodec(5, "FillingVenting"),
            927	: O3EInt8(1, "BuildingType"),
            928	: RawCodec(16, "ElectronicTraceabilityNumber"),
            933	: O3EInt16(9, "MixerOneCircuitProperty"),
            934	: O3EInt16(9, "MixerTwoCircuitProperty"),
            935	: O3EInt16(9, "MixerThreeCircuitProperty"),
            936	: O3EInt16(9, "MixerFourCircuitProperty"),
            952	: RawCodec(51, "HydraulicMatrix"),
            954 : O3EComplexType(181, "BusTopologyMatrix", [O3EByteVal(1, "Count"),O3EByteVal(1, "NodeID1"),O3EByteVal(1, "BusType1"),O3EByteVal(1, "DeviceProperty1"),O3EByteVal(1, "DeviceFunction1"),O3ESoftVers(8, "SW-Version1"), O3ESoftVers(8, "HW-Version1"),O3EUtf8(16, "VIN1"), O3EByteVal(1, "BusAddress2"),O3EByteVal(1, "BusType2"),O3EByteVal(1, "DeviceProperty2"),O3EByteVal(1, "DeviceFunction2"),O3ESoftVers(8, "SW-Version2"), O3ESoftVers(8, "HW-Version2"),O3EUtf8(16, "VIN2"),O3EByteVal(1, "BusAddress3"),O3EByteVal(1, "BusType3"),O3EByteVal(1, "DeviceProperty3"),O3EByteVal(1, "DeviceFunction3"),O3ESoftVers(8, "SW-Version3"), O3ESoftVers(8, "HW-Version3"),O3EUtf8(16, "VIN3"),O3EByteVal(1, "BusAddress4"),O3EByteVal(1, "BusType4"),O3EByteVal(1, "DeviceProperty4"),O3EByteVal(1, "DeviceFunction4"),O3ESoftVers(8, "SW-Version4"), O3ESoftVers(8, "HW-Version4"),O3EUtf8(16, "VIN4"),O3EByteVal(1, "BusAddress5"),O3EByteVal(1, "BusType5"),O3EByteVal(1, "DeviceProperty5"),O3EByteVal(1, "DeviceFunction5"),O3ESoftVers(8, "SW-Version5"), O3ESoftVers(8, "HW-Version5"),O3EUtf8(16, "VIN5")]),            961	: RawCodec(2, "SecurityAlgorithmNumber"),
            962	: RawCodec(8, "BootLoaderVersion"),
            964	: O3EInt8(1, "ActiveDiagnosticSession"),
            987	: O3EInt16(2, "MixerOneCircuitFlowTemperatureTargetSetpoint"),
            988	: O3EInt16(2, "MixerTwoCircuitFlowTemperatureTargetSetpoint"),
            989	: O3EInt16(2, "MixerThreeCircuitFlowTemperatureTargetSetpoint"),
            990	: O3EInt16(2, "MixerFourCircuitFlowTemperatureTargetSetpoint"),
            1004	: O3EInt8(1, "CentralHeatingRegulationMode"),
            1006	: RawCodec(4, "TargetQuickMode"),
            1007	: RawCodec(4, "CurrentQuickMode"),
            1008	: RawCodec(4, "MixerOneCircuitTargetQuickMode"),
            1009	: RawCodec(4, "MixerTwoCircuitTargetQuickMode"),
            1010	: RawCodec(4, "MixerThreeCircuitTargetQuickMode"),
            1011	: RawCodec(4, "MixerFourCircuitTargetQuickMode"),
            1024	: RawCodec(4, "MixerOneCircuitCurrentQuickMode"),
            1025	: RawCodec(4, "MixerTwoCircuitCurrentQuickMode"),
            1026	: RawCodec(4, "MixerThreeCircuitCurrentQuickMode"),
            1027	: RawCodec(4, "MixerFourCircuitCurrentQuickMode"),
            1043	: O3EInt16(5, "AllengraSensor"),
            1085	: RawCodec(4, "DomesticHotWaterHysteresis"),
            1087	: RawCodec(2, "MaximumDomesticHotWaterLoadingTime"),
            1096	: O3EInt8(1, "ResetEnergyManagerDataCollector"),
            1097	: RawCodec(20, "ElectricityPrice"),
            1098	: RawCodec(20, "GasProperties"),
            1100	: O3EComplexType(3, "CentralHeatingPumpMinimumMaximumLimit", [O3EInt8(1, "MinSpeed_%"), O3EInt8(1, "MaxSpeed_%"),O3EInt8(1, "Setpoint_%")]),
            1101	: O3EComplexType(3, "DomesticHotWaterPumpMinimumMaximumLimit", [O3EInt8(1, "MinSpeed_%"), O3EInt8(1, "MaxSpeed_%"),O3EInt8(1, "Setpoint_%")]),
            1102	: RawCodec(3, "MixerOneCircuitPumpMinimumMaximumLimit"),
            1103	: RawCodec(3, "MixerTwoCircuitPumpMinimumMaximumLimit"),
            1104	: RawCodec(3, "MixerThreeCircuitPumpMinimumMaximumLimit"),
            1105	: RawCodec(3, "MixerFourCircuitPumpMinimumMaximumLimit"),
            1138	: O3EInt8(1, "AccentLedBar"),
            1139	: RawCodec(7, "CentralHeatingCurveAdaptionParameter"),
            1165	: O3EInt8(1, "BackendConnectionStatus"),
            1166	: RawCodec(5, "ResetDtcHistory"),
            1167	: O3EInt16(2, "ExternalDomesticHotWaterTemperatureSetpoint", signed=True),
            1175	: O3EInt8(1, "AcknowledgeInfoAlarmMessage"),
            1177	: O3EInt8(1, "AcknowledgeServiceAlarmMessage"),
            1178	: O3EInt8(1, "AcknowledgeErrorAlarmMessage"),
            1190	: RawCodec(4, "ThermalPower"),
            1192	: RawCodec(10, "MixerOneCircuitFlowTemperatureMinimumMaximumLimit"),
            1193	: RawCodec(10, "MixerTwoCircuitFlowTemperatureMinimumMaximumLimit"),
            1194	: RawCodec(10, "MixerThreeCircuitFlowTemperatureMinimumMaximumLimit"),
            1195	: RawCodec(10, "MixerFourCircuitFlowTemperatureMinimumMaximumLimit"),
            1211	: RawCodec(24, "GeneratedCentralHeatingOutput"),
            1232	: O3EInt8(1, "GenericDigitalInputConfigurationOnBoardOne"),
            1233	: RawCodec(68, "GatewayRemoteVisibleOneTwo"),
            1234	: RawCodec(68, "GatewayRemoteVisibleThreeFour"),
            1235	: RawCodec(68, "GatewayRemoteVisibleFiveSix"),
            1236	: RawCodec(68, "GatewayRemoteVisibleSevenEight"),
            1237	: RawCodec(68, "GatewayRemoteVisibleNineTen"),
            1238	: RawCodec(31, "AvailableActorSensorComponents"),
            1239	: RawCodec(2, "ActorSensorTest"),
            1240	: O3EInt8(1, "CentralHeatingPumpMode"),
            1241	: O3EInt8(1, "MixerOneCircuitPumpMode"),
            1242	: O3EInt8(1, "MixerTwoCircuitPumpMode"),
            1243	: O3EInt8(1, "MixerThreeCircuitPumpMode"),
            1244	: O3EInt8(1, "MixerFourCircuitPumpMode"),
            1286    : O3EComplexType(181, "BusTopologyMatrixTwo", [O3EByteVal(1, "Count"),O3EByteVal(1, "NodeID1"),O3EByteVal(1, "BusType1"),O3EByteVal(1, "DeviceProperty1"),O3EByteVal(1, "DeviceFunction1"),O3ESoftVers(8, "SW-Version1"), O3ESoftVers(8, "HW-Version1"),O3EUtf8(16, "VIN1"), O3EByteVal(1, "BusAddress2"),O3EByteVal(1, "BusType2"),O3EByteVal(1, "DeviceProperty2"),O3EByteVal(1, "DeviceFunction2"),O3ESoftVers(8, "SW-Version2"), O3ESoftVers(8, "HW-Version2"),O3EUtf8(16, "VIN2"),O3EByteVal(1, "BusAddress3"),O3EByteVal(1, "BusType3"),O3EByteVal(1, "DeviceProperty3"),O3EByteVal(1, "DeviceFunction3"),O3ESoftVers(8, "SW-Version3"), O3ESoftVers(8, "HW-Version3"),O3EUtf8(16, "VIN3"),O3EByteVal(1, "BusAddress4"),O3EByteVal(1, "BusType4"),O3EByteVal(1, "DeviceProperty4"),O3EByteVal(1, "DeviceFunction4"),O3ESoftVers(8, "SW-Version4"), O3ESoftVers(8, "HW-Version4"),O3EUtf8(16, "VIN4"),O3EByteVal(1, "BusAddress5"),O3EByteVal(1, "BusType5"),O3EByteVal(1, "DeviceProperty5"),O3EByteVal(1, "DeviceFunction5"),O3ESoftVers(8, "SW-Version5"), O3ESoftVers(8, "HW-Version5"),O3EUtf8(16, "VIN5")]),
            1287    : O3EComplexType(181, "BusTopologyMatrixThree", [O3EByteVal(1, "Count"),O3EByteVal(1, "NodeID1"),O3EByteVal(1, "BusType1"),O3EByteVal(1, "DeviceProperty1"),O3EByteVal(1, "DeviceFunction1"),O3ESoftVers(8, "SW-Version1"), O3ESoftVers(8, "HW-Version1"),O3EUtf8(16, "VIN1"), O3EByteVal(1, "BusAddress2"),O3EByteVal(1, "BusType2"),O3EByteVal(1, "DeviceProperty2"),O3EByteVal(1, "DeviceFunction2"),O3ESoftVers(8, "SW-Version2"), O3ESoftVers(8, "HW-Version2"),O3EUtf8(16, "VIN2"),O3EByteVal(1, "BusAddress3"),O3EByteVal(1, "BusType3"),O3EByteVal(1, "DeviceProperty3"),O3EByteVal(1, "DeviceFunction3"),O3ESoftVers(8, "SW-Version3"), O3ESoftVers(8, "HW-Version3"),O3EUtf8(16, "VIN3"),O3EByteVal(1, "BusAddress4"),O3EByteVal(1, "BusType4"),O3EByteVal(1, "DeviceProperty4"),O3EByteVal(1, "DeviceFunction4"),O3ESoftVers(8, "SW-Version4"), O3ESoftVers(8, "HW-Version4"),O3EUtf8(16, "VIN4"),O3EByteVal(1, "BusAddress5"),O3EByteVal(1, "BusType5"),O3EByteVal(1, "DeviceProperty5"),O3EByteVal(1, "DeviceFunction5"),O3ESoftVers(8, "SW-Version5"), O3ESoftVers(8, "HW-Version5"),O3EUtf8(16, "VIN5")]),
            1288    : O3EComplexType(181, "BusTopologyMatrixFour", [O3EByteVal(1, "Count"),O3EByteVal(1, "NodeID1"),O3EByteVal(1, "BusType1"),O3EByteVal(1, "DeviceProperty1"),O3EByteVal(1, "DeviceFunction1"),O3ESoftVers(8, "SW-Version1"), O3ESoftVers(8, "HW-Version1"),O3EUtf8(16, "VIN1"), O3EByteVal(1, "BusAddress2"),O3EByteVal(1, "BusType2"),O3EByteVal(1, "DeviceProperty2"),O3EByteVal(1, "DeviceFunction2"),O3ESoftVers(8, "SW-Version2"), O3ESoftVers(8, "HW-Version2"),O3EUtf8(16, "VIN2"),O3EByteVal(1, "BusAddress3"),O3EByteVal(1, "BusType3"),O3EByteVal(1, "DeviceProperty3"),O3EByteVal(1, "DeviceFunction3"),O3ESoftVers(8, "SW-Version3"), O3ESoftVers(8, "HW-Version3"),O3EUtf8(16, "VIN3"),O3EByteVal(1, "BusAddress4"),O3EByteVal(1, "BusType4"),O3EByteVal(1, "DeviceProperty4"),O3EByteVal(1, "DeviceFunction4"),O3ESoftVers(8, "SW-Version4"), O3ESoftVers(8, "HW-Version4"),O3EUtf8(16, "VIN4"),O3EByteVal(1, "BusAddress5"),O3EByteVal(1, "BusType5"),O3EByteVal(1, "DeviceProperty5"),O3EByteVal(1, "DeviceFunction5"),O3ESoftVers(8, "SW-Version5"), O3ESoftVers(8, "HW-Version5"),O3EUtf8(16, "VIN5")]),
            1289    : O3EComplexType(181, "BusTopologyMatrixFive", [O3EByteVal(1, "Count"),O3EByteVal(1, "NodeID1"),O3EByteVal(1, "BusType1"),O3EByteVal(1, "DeviceProperty1"),O3EByteVal(1, "DeviceFunction1"),O3ESoftVers(8, "SW-Version1"), O3ESoftVers(8, "HW-Version1"),O3EUtf8(16, "VIN1"), O3EByteVal(1, "BusAddress2"),O3EByteVal(1, "BusType2"),O3EByteVal(1, "DeviceProperty2"),O3EByteVal(1, "DeviceFunction2"),O3ESoftVers(8, "SW-Version2"), O3ESoftVers(8, "HW-Version2"),O3EUtf8(16, "VIN2"),O3EByteVal(1, "BusAddress3"),O3EByteVal(1, "BusType3"),O3EByteVal(1, "DeviceProperty3"),O3EByteVal(1, "DeviceFunction3"),O3ESoftVers(8, "SW-Version3"), O3ESoftVers(8, "HW-Version3"),O3EUtf8(16, "VIN3"),O3EByteVal(1, "BusAddress4"),O3EByteVal(1, "BusType4"),O3EByteVal(1, "DeviceProperty4"),O3EByteVal(1, "DeviceFunction4"),O3ESoftVers(8, "SW-Version4"), O3ESoftVers(8, "HW-Version4"),O3EUtf8(16, "VIN4"),O3EByteVal(1, "BusAddress5"),O3EByteVal(1, "BusType5"),O3EByteVal(1, "DeviceProperty5"),O3EByteVal(1, "DeviceFunction5"),O3ESoftVers(8, "SW-Version5"), O3ESoftVers(8, "HW-Version5"),O3EUtf8(16, "VIN5")]),
            1290	: RawCodec(4, "DomesticHotWaterShiftLoadPump"),
            1294	: RawCodec(124, "EnergyConsumptionCentralHeatingMonthMatrix"),
            1311	: RawCodec(124, "EnergyConsumptionDomesticHotWaterMonthMatrix"),
            1312	: RawCodec(124, "EnergyConsumptionCoolingMonthMatrix"),
            1315	: RawCodec(124, "GeneratedCentralHeatingOutputMonthMatrix"),
            1316	: RawCodec(96, "EnergyConsumptionCentralHeatingYearMatrix"),
            1333	: RawCodec(96, "EnergyConsumptionDomesticHotWaterYearMatrix"),
            1334	: RawCodec(96, "EnergyConsumptionCoolingYearMatrix"),
            1337	: RawCodec(96, "GeneratedCentralHeatingOutputYearMatrix"),
            1338	: RawCodec(31, "ScreedDryingProfileDefinition"),
            1339	: O3EInt8(1, "MalfunctionHeatingUnitBlocked"),
            1364	: O3EInt8(1, "GenericSdioAccessoryOneModulFunction"),
            1391	: RawCodec(24, "GeneratedDomesticHotWaterOutput"),
            1392	: RawCodec(124, "GeneratedDomesticHotWaterOutputMonthMatrix"),
            1393	: RawCodec(96, "GeneratedDomesticHotWaterOutputYearMatrix"),
            1394	: RawCodec(2, "SolarChargingDomesticHotWaterSetpoint"),
            1395	: RawCodec(3, "MixerOneCircuitSummerSavingTemperatureThreshold"),
            1396	: RawCodec(3, "MixerTwoCircuitSummerSavingTemperatureThreshold"),
            1397	: RawCodec(3, "MixerThreeCircuitSummerSavingTemperatureThreshold"),
            1398	: RawCodec(3, "MixerFourCircuitSummerSavingTemperatureThreshold"),
            1415	: O3EOperationState(2, "MixerOneCircuitOperationState"),
            1416	: O3EOperationState(2, "MixerTwoCircuitOperationState"),
            1417	: O3EOperationState(2, "MixerThreeCircuitOperationState"),
            1418	: O3EOperationState(2, "MixerFourCircuitOperationState"),
            1439	: RawCodec(41, "NoiseReductionTimeScheduleMonday"),
            1440	: RawCodec(41, "NoiseReductionTimeScheduleTuesday"),
            1441	: RawCodec(41, "NoiseReductionTimeScheduleWednesday"),
            1442	: RawCodec(41, "NoiseReductionTimeScheduleThursday"),
            1443	: RawCodec(41, "NoiseReductionTimeScheduleFriday"),
            1444	: RawCodec(41, "NoiseReductionTimeScheduleSaturday"),
            1445	: RawCodec(41, "NoiseReductionTimeScheduleSunday"),
            1467	: RawCodec(2, "SafetyRelevantRemoteUnlock"),
            1469	: RawCodec(31, "SensorActuatorTestGroupHeatEngine"),
            1470	: RawCodec(31, "SensorActuatorTestGroupDomesticHotWater"),
            1472	: RawCodec(31, "SensorActuatorTestGroupHeatingCircuit"),
            1473	: RawCodec(31, "SensorActuatorTestGroupSolar"),
            1494	: RawCodec(8, "OemProductVersion"),
            1504	: O3EInt8(1, "TimeSettingSource"),
            1529	: O3EInt8(1, "SolarRechargeSuppressionImpact"),
            1533	: RawCodec(2, "InstallationWizardInProgress"),
            1536	: RawCodec(3, "PrimaryCircuitWaterFlowTestMode"),
            1537	: RawCodec(3, "ChimneySweeperTestMode"),
            1538	: O3EInt8(1, "ZigbeeEnable"),
            1539	: O3EInt8(1, "ZigbeeStatus"),
            1540	: RawCodec(26, "ZigbeeIdentification"),
            1549	: RawCodec(97, "HydraulicMatrixConfiguration"),
            1553	: RawCodec(8, "ElectronicControlUnitOdxVersion"),
            1555	: RawCodec(6, "MixerOneCircuitFixedValueFlowTemperatureSetpoint"),
            1556	: RawCodec(6, "MixerTwoCircuitFixedValueFlowTemperatureSetpoint"),
            1557	: RawCodec(6, "MixerThreeCircuitFixedValueFlowTemperatureSetpoint"),
            1558	: RawCodec(6, "MixerFourCircuitFixedValueFlowTemperatureSetpoint"),
            1595	: RawCodec(8, "ParameterIdentificationVersionFactory"),
            1607	: O3EInt8(1, "MalfunctionUnitBlocked"),
            1612	: O3EOperationState(2, "ExternalMixerTwoCircuitTargetOperationMode"),
            1613	: O3EOperationState(2, "ExternalMixerThreeCircuitTargetOperationMode"),
            1614	: O3EOperationState(2, "ExternalMixerFourCircuitTargetOperationMode"),
            1627	: O3EInt16(2, "ExternalMixerOneCircuitFixedValueTargetTemperatureSetpoint", scale = 10, signed=True),
            1628	: O3EInt16(2, "ExternalMixerTwoCircuitFixedValueTargetTemperatureSetpoint", scale = 10, signed=True),
            1629	: O3EInt16(2, "ExternalMixerThreeCircuitFixedValueTargetTemperatureSetpoint", scale = 10, signed=True),
            1630	: O3EInt16(2, "ExternalMixerFourCircuitFixedValueTargetTemperatureSetpoint", scale = 10, signed=True),
            1643	: O3EInt16(2, "MixerOneCircuitCurrentTemperatureSetpoint", scale = 10, signed=True),
            1644	: O3EInt16(2, "MixerTwoCircuitCurrentTemperatureSetpoint", scale = 10, signed=True),
            1645	: O3EInt16(2, "MixerThreeCircuitCurrentTemperatureSetpoint", scale = 10, signed=True),
            1646	: O3EInt16(2, "MixerFourCircuitCurrentTemperatureSetpoint", scale = 10, signed=True),
            1659	: O3EInt16(3, "EndResultDomesticHotWaterTemperatureSetpoint", scale = 10, signed=True),
            1660	: RawCodec(16, "SupportedFeatures"),
            1667	: RawCodec(2, "MixerOneCircuitPumpOscillationTime"),
            1668	: RawCodec(2, "MixerTwoCircuitPumpOscillationTime"),
            1669	: RawCodec(2, "MixerThreeCircuitPumpOscillationTime"),
            1670	: RawCodec(2, "MixerFourCircuitPumpOscillationTime"),
            1694	: O3EInt8(1, "GatewayEthernetEnable"),
            1695	: RawCodec(21, "GatewayEthernetConfig"),
            1696	: RawCodec(20, "GatewayEthernetIp"),
            1697	: O3EInt8(1, "GatewayEthernetNetworkStatus"),
            1710	: RawCodec(8, "FunctionalSoftwareVersion"),
            1721	: RawCodec(8, "WaterPressureConfiguration"),
            1731	: O3EInt8(1, "ExternalLockActive"),
            1768	: O3EInt16(9, "ReceiverTemperatureSensor", signed=True),
            1769	: O3EInt16(9, "PrimaryInletTemperatureSensor", signed=True),
            1770	: O3EInt16(9, "SecondaryOutletTemperatureSensor", signed=True),
            1771	: O3EInt16(9, "EngineRoomTemperatureSensor", signed=True),
            1772	: O3EInt16(9, "CompressorOilTemperatureSensor", signed=True),
            1773	: O3EInt8(1, "RefrigerantCircuitFourWayValve"),
            1774	: O3EInt8(1, "CompressorCrankCaseHeater"),
            1775	: O3EInt8(1, "PrimaryCircuitFanOne"),
            1776	: O3EInt8(1, "PrimaryCircuitFanTwo"),
            1786	: RawCodec(52, "TimeSeriesRecordedWaterPressureStagnation"),
            1787	: RawCodec(32, "TimeSeriesRecordedWaterPressurePeaks"),
            1799	: RawCodec(2, "PrimaryCircuitCurrentTemperatureSetpoint"),
            1814	: RawCodec(5, "ReceiverLiquidLevelSensor"),
            1815	: O3EInt8(1, "ElectricalHeaterPhaseOne"),
            1816	: O3EInt8(1, "ElectricalHeaterPhaseTwo"),
            1817	: O3EInt8(1, "ElectricalHeaterPhaseThree"),
            1819	: O3EInt8(1, "SolarPumpConfigurationSelection"),
            1842	: RawCodec(2, "SecondaryCircuitFourThreeWayValve"),
            1843	: RawCodec(2, "MixerOneCircuitHumidityProtection"),
            1844	: RawCodec(2, "MixerTwoCircuitHumidityProtection"),
            2233	: O3EInt8(1, "PersistentStorageStatus"),
            2235	: RawCodec(65, "CascadeSystemConfiguration"),
            2255	: O3EInt16(2, "MinimumSecondaryReturnTemperatureRefrigerantCircuit", signed=True),
            2256	: O3EInt16(2, "DesiredThermalEnergyDefrost"),
            2257	: O3EInt16(2, "DomesticHotWaterTemperatureSetpointOffset", signed=True),
            2259	: O3EInt8(1, "RefrigerationCircuitStatus"),
            2320	: O3EInt8(1, "DomesticHotWaterStatus"),
            2330	: O3EInt8(1, "GenericDigitalInputConfigurationOnBoardTwo"),
            2331	: O3EInt8(1, "GenericDigitalInputConfigurationOnBoardThree"),
            2332	: O3EInt8(1, "GenericDigitalInputConfigurationOnBoardFour"),
            2333	: O3EInt16(9, "EconomizerLiquidTemperatureSensor", signed=True),
            2334	: O3EInt16(9, "EvaporatorVaporTemperatureSensor", signed=True),
            2340	: RawCodec(2, "ElectricalHeaterConfiguration"),
            2341	: RawCodec(4, "CoefficientOfPerformanceConfiguration"),
            2342	: O3EInt16(4, "NominalThermalCapacityHeating", scale = 1),
            2343	: O3EInt16(4, "NominalThermalCapacityCooling", scale = 1),
            2346	: O3EInt8(1, "CompressorSpeedPercent"),
            2350	: O3EInt8(1, "EnergyManagmentSystemResultingControlState"),
            2351	: O3EInt8(2, "HeatPumpCompressor", offset = 0),
            2352	: RawCodec(2, "AdditionalElectricHeater"),
            2369	: O3ECompStat(14, "HeatPumpCompressorStatistical"),
            2370	: O3EAddElHeaterStat(11, "AdditionalElectricHeaterStatistical"),
            2404	: RawCodec(6, "BivalenceControlMode"),
            2405	: RawCodec(6, "MixerOneCircuitConstantFlowSetTemperatureCooling"),
            2406	: RawCodec(6, "MixerTwoCircuitConstantFlowSetTemperatureCooling"),
            2407	: RawCodec(6, "MixerThreeCircuitConstantFlowSetTemperatureCooling"),
            2408	: RawCodec(6, "MixerFourCircuitConstantFlowSetTemperatureCooling"),
            2409	: RawCodec(12, "MixerOneCircuitMinimumMaximumFlowSetTemperatureCooling"),
            2410	: RawCodec(12, "MixerTwoCircuitMinimumMaximumFlowSetTemperatureCooling"),
            2411	: RawCodec(12, "MixerThreeCircuitMinimumMaximumFlowSetTemperatureCooling"),
            2412	: RawCodec(12, "MixerFourCircuitMinimumMaximumFlowSetTemperatureCooling"),
            2413	: RawCodec(4, "MixerOneCircuitThresholdCooling"),
            2414	: RawCodec(4, "MixerTwoCircuitThresholdCooling"),
            2415	: RawCodec(4, "MixerThreeCircuitThresholdCooling"),
            2416	: RawCodec(4, "MixerFourCircuitThresholdCooling"),
            2417	: RawCodec(6, "MixerOneCircuitTargetValueRelativeHumidityCooling"),
            2418	: RawCodec(6, "MixerTwoCircuitTargetValueRelativeHumidityCooling"),
            2419	: RawCodec(6, "MixerThreeCircuitTargetValueRelativeHumidityCooling"),
            2420	: RawCodec(6, "MixerFourCircuitTargetValueRelativeHumidityCooling"),
            2421	: RawCodec(2, "MixerOneCircuitTemperatureOffsetCooling"),
            2422	: RawCodec(2, "MixerTwoCircuitTemperatureOffsetCooling"),
            2423	: RawCodec(2, "MixerThreeCircuitTemperatureOffsetCooling"),
            2424	: RawCodec(2, "MixerFourCircuitTemperatureOffsetCooling"),
            2426	: RawCodec(6, "MixerOneCircuitRoomEcoFunctionSettings"),
            2427	: RawCodec(6, "MixerTwoCircuitRoomEcoFunctionSettings"),
            2428	: RawCodec(6, "MixerThreeCircuitRoomEcoFunctionSettings"),
            2429	: RawCodec(6, "MixerFourCircuitRoomEcoFunctionSettings"),
            2452	: RawCodec(4, "MixerOneCircuitRoomTemperatureThresholdCooling"),
            2453	: RawCodec(4, "MixerTwoCircuitRoomTemperatureThresholdCooling"),
            2454	: RawCodec(4, "MixerThreeCircuitRoomTemperatureThresholdCooling"),
            2455	: RawCodec(4, "MixerFourCircuitRoomTemperatureThresholdCooling"),
            2457	: O3EInt16(9, "CalculatedOutsideTemperature", signed=True),
            2479	: RawCodec(5, "MixerOneCircuitRoomAirHumiditySensor"),
            2480	: RawCodec(5, "MixerTwoCircuitRoomAirHumiditySensor"),
            2481	: RawCodec(5, "MixerThreeCircuitRoomAirHumiditySensor"),
            2482	: RawCodec(5, "MixerFourCircuitRoomAirHumiditySensor"),
            2484	: RawCodec(8, "ElectricalPowerRangeMetaData"),
            2486	: O3EInt16(4, "CurrentElectricalPowerConsumptionRefrigerantCircuit", scale = 1),
            2487	: O3EInt16(4, "CurrentElectricalPowerConsumptionElectricHeater", scale = 1),
            2488	: O3EInt16(4, "CurrentElectricalPowerConsumptionSystem", scale = 1),
            2494	: O3EInt16(4, "CurrentThermalCapacityRefrigerantCircuit", scale = 1),
            2495	: O3EInt16(4, "CurrentThermalCapacityElectricHeater", scale = 1),
            2496	: O3EInt16(4, "CurrentThermalCapacitySystem", scale = 1),
            2498	: O3EInt8(1, "CentralHeatingPumpType"),
            2499	: O3EInt8(1, "MixerOneCircuitPumpType"),
            2500	: O3EInt8(1, "MixerTwoCircuitPumpType"),
            2501	: O3EInt8(1, "MixerThreeCircuitPumpType"),
            2502	: O3EInt8(1, "MixerFourCircuitPumpType"),
            2515	: RawCodec(124, "EnergyConsumptionDomesticHotWaterMonthMatrixElectricHeater"),
            2516	: RawCodec(96, "EnergyConsumptionDomesticHotWaterYearMatrixElectricHeater"),
            2517	: RawCodec(24, "EnergyConsumptionDomesticHotWaterElectricHeater"),
            2524	: RawCodec(124, "EnergyConsumptionCentralHeatingMonthMatrixElectricHeater"),
            2525	: RawCodec(96, "EnergyConsumptionCentralHeatingYearMatrixElectricHeater"),
            2526	: RawCodec(24, "EnergyConsumptionCentralHeatingElectricHeater"),
            2527	: RawCodec(124, "GeneratedCoolingOutputMonthMatrix"),
            2528	: RawCodec(96, "GeneratedCoolingOutputYearMatrix"),
            2529	: RawCodec(24, "GeneratedCoolingOutput"),
            2540	: RawCodec(6, "NoiseReductionSettings"),
            2543	: RawCodec(10, "SmartGridTemperatureOffsets"),
            2544	: O3EInt8(1, "EnableElectricalHeaterSmartGridLock"),
            2545	: O3EInt8(1, "EnableElectricalHeaterSmartGridIncreaseMaxDemand"),
            2546	: O3EInt16(9, "MixerOneCircuitRoomTemperatureSetpointCooling", signed=True),
            2547	: O3EInt16(9, "MixerTwoCircuitRoomTemperatureSetpointCooling", signed=True),
            2548	: O3EInt16(9, "MixerThreeCircuitRoomTemperatureSetpointCooling", signed=True),
            2549	: O3EInt16(9, "MixerFourCircuitRoomTemperatureSetpointCooling", signed=True),
            2555	: RawCodec(4, "ElectricalPowerSetPoint"),
            2556	: RawCodec(4, "ElectricalEnergyRemainingCapacity"),
            2557	: O3EInt8(1, "HeatPumpState"),
            2558	: RawCodec(3, "HeatPumpSupportedStates"),
            2560	: O3EInt8(1, "SmartGridFeatureSelection"),
            2569	: O3EInt16(2, "CompressorSpeedRps", scale = 10),
            2573	: RawCodec(2, "CompressorOnTimer"),
            2574	: O3EInt16(8, "NominalPowerElectricalHeater", scale = 1),
            2582	: RawCodec(2, "CompressorOffTimer"),
            2586	: RawCodec(2, "DigitalOutputCooling"),
            2593	: RawCodec(181, "ProductMatrix"),
            2611	: RawCodec(4, "NominalThermalCapacityIndoorUnit"),
            2622	: O3EInt16(9, "SeasonalCoefficientOfPerformaceHeating"),
            2623	: O3EInt16(9, "SeasonalEnergyEfficiencyRatioCooling"),
            2624	: O3EInt16(9, "SeasonalCoefficientOfPerformaceDomesticHotWater"),
            2625	: O3EInt16(9, "SeasonalCoefficientOfPerformaceHeatingAndDomesticHotWater"),
            2626	: O3EInt16(4, "MaximumPowerElectricalHeater", scale = 1),
            2629	: O3EInt16(4, "DesiredThermalCapacity", scale = 1),
            2634	: O3EInt8(1, "NoiseReductionMode"),
            2733	: RawCodec(3, "InstallationConfirmation"),
            2735	: O3EInt8(1, "FourThreeWayValveValveCurrentPosition"),
            2741	: RawCodec(3, "ComfortEnsuringMode"),
            2742	: O3EInt8(1, "DiagnosticHydraulicFilterInterval"),
            2743	: O3EInt8(1, "DiagnosticElectricalHeaterSafetyTemperatureLimiter"),
            2744	: O3EInt8(1, "DiagnosticSecondaryFourThreeWayValve"),
            2745	: O3EInt8(1, "DiagnosticHydraulicFilterContamination"),
            2746	: O3EInt8(1, "DiagnosticHydraulicSafetyValve"),
            2750	: O3EInt8(1, "DiagnosticHydraulicTemperatureSensors"),
            2767	: O3EInt8(1, "DiagnosticMonitoringPressureDrop"),
            2768	: O3EInt8(1, "DiagnosticMonitoringPressurePeaks"),
            2776	: RawCodec(181, "ProductMatrixTwo"),
            2777	: RawCodec(8, "PrimaryBootLoaderVersion"),
            2784	: O3EInt16(9, "SecondaryHeatExchangerVaporPressureSensor", scale = 100),
            2791	: O3EInt8(5, "CentralHeatingPumpStatus", offset = 0, scale = 1),
            2792	: O3EInt8(5, "MixerOneCircuitPumpStatus", offset = 0, scale = 1),
            2793	: O3EInt8(5, "MixerTwoCircuitPumpStatus", offset = 0, scale = 1),
            2794	: O3EInt8(5, "MixerThreeCircuitPumpStatus", offset = 0, scale = 1),
            2795	: O3EInt8(5, "MixerFourCircuitPumpStatus", offset = 0, scale = 1),
            2796	: RawCodec(2, "ExternalHeaterConfiguration"),
            2806	: O3EOperationState(2, "RefrigerationCircuitOperationMode"),
            2829	: RawCodec(20, "ProductIdentification"),
            2831	: RawCodec(2, "BivalenceControlAlternativeTemperature"),
            2853	: RawCodec(2, "ExternalHeaterTimeIntegralThershold"),
            2855	: RawCodec(3, "MixerOneCircuitFrostProtectionConfiguration"),
            2856	: RawCodec(3, "MixerTwoCircuitFrostProtectionConfiguration"),
            2857	: RawCodec(3, "MixerThreeCircuitFrostProtectionConfiguration"),
            2858	: RawCodec(3, "MixerFourCircuitFrostProtectionConfiguration"),
            2879	: RawCodec(2, "MixerOneCircuitHeatingBlocked"),
            2880	: RawCodec(2, "MixerTwoCircuitHeatingBlocked"),
            2894	: O3EInt8(1, "RefrigerantCycleAvailability"),
            2920	: RawCodec(2, "ExternalHeaterSpecification"),
            2921	: RawCodec(2, "DiagnosticHydraulicFilterIntervalSettings"),
            2922	: RawCodec(2, "DiagnosticHydraulicFilterIntervalTemporalSettings"),
            2923	: RawCodec(6, "DiagnosticSecondaryFourThreeWayValveSettings"),
            2924	: RawCodec(4, "DiagnosticHydraulicFilterContaminationSettings"),
            2925	: RawCodec(2, "DiagnosticMonitoringPressurePeaksSettings"),
            2926	: RawCodec(6, "DiagnosticMonitoringPressureDropSettings"),
            2932	: RawCodec(4, "TimeCounterSinceLastReset"),
            2940	: RawCodec(3, "ExternalHeaterDelayTimer"),
            2942	: RawCodec(137, "ListOfLayerSettingServiceDevices"),
            2944	: O3EInt8(1, "NodeIdOnExternalCan"),
            2952	: RawCodec(137, "ListOfLayerSettingServiceDevicesTwo"),
            2953	: RawCodec(10, "CascadeSystemConfigurationArray"),
            2969	: O3EInt8(1, "ElectronicControlUnitSafeStateStatus"),
            2985	: RawCodec(2, "ExternalHeaterTemperatureSetpoint"),
            2986	: O3EInt8(1, "ExternalHeaterOperationState"),
            3000	: RawCodec(115, "EcuResetInformationList"),
            3013	: RawCodec(2, "MixerHybridThreeWayValvePositionPercent"),
            3014	: O3EInt16(9, "OutdoorMiddleCoilTemperatureSensor", signed=True),
            3015	: O3EInt16(9, "HeatSinkTemperatureSensor", signed=True),
            3016	: O3EInt16(9, "HeatingBufferTemperatureSensor", signed=True),
            3017	: O3EInt16(9, "CoolingBufferTemperatureSensor", signed=True),
            3018	: O3EInt16(9, "HeatingCoolingBufferTemperatureSensor", signed=True),
            3029	: O3EInt8(1, "DomesticHotWaterEfficiencyMode"),
            3030	: RawCodec(2, "DomesticHotWaterEfficiencyModeAvailability"),
            3031	: RawCodec(2, "ExternalHeater"),
            3032	: RawCodec(2, "PrimaryEnergyFactorElectricity"),
            3034	: O3EInt16(9, "DomesticHotWaterReturnTemperaturTankLoadSystem", signed=True),
            3035	: O3EInt16(9, "DomesticHotWaterFlowTemperaturTankLoadSystem", signed=True),
            3036	: RawCodec(2, "PrimaryEnergyFactorExternalHeater"),
            3037	: RawCodec(57, "ElectricityPriceTimeScheduleMonday"),
            3038	: RawCodec(57, "ElectricityPriceTimeScheduleTuesday"),
            3039	: RawCodec(57, "ElectricityPriceTimeScheduleWednesday"),
            3040	: RawCodec(57, "ElectricityPriceTimeScheduleThursday"),
            3041	: RawCodec(57, "ElectricityPriceTimeScheduleFriday"),
            3042	: RawCodec(57, "ElectricityPriceTimeScheduleSaturday"),
            3043	: RawCodec(57, "ElectricityPriceTimeScheduleSunday"),
            3066	: RawCodec(4, "DomesticHotWaterHighDemandDetection"),
            3068	: RawCodec(2, "DomesticHotWaterTemperatureSetpointComfort"),
            3069	: O3EInt8(1, "DomesticHotWaterSensorForDemand"),
            3070	: O3EInt8(1, "BufferTargetOperationMode"),
            3091	: O3EInt8(1, "GatewayEthernetTwoEnable"),
            3092	: RawCodec(21, "GatewayEthernetTwoConfig"),
            3093	: RawCodec(20, "GatewayEthernetTwoIp"),
            3094	: O3EInt8(1, "GatewayEthernetTwoNetworkStatus"),
            3095	: RawCodec(6, "MacAddressLanTwo"),
            3096	: O3EInt8(1, "GatewayWifiStationEnable"),
            3097	: O3EInt8(1, "GatewayInternetAccess"),
            3098	: RawCodec(2, "ExternalHeaterTemperatureOffset"),
            3106	: RawCodec(4, "BufferMinimumMaximumSetTemperature"),
            3113	: RawCodec(8, "DeviceDigitalOutputOneValueStatistical"),
            3114	: RawCodec(8, "DeviceDigitalOutputTwoValueStatistical"),
            3155	: RawCodec(5, "DomesticHotWaterShiftLoadPumpStatus"),
            3156	: O3EInt8(1, "DomesticHotWaterShiftLoadPumpType"),
            3191    : RawCodec(199, "ExtendedEventLoggingHistory")
        }
    },
    # VCMU Interner CAN-BUS: 54
    # Vapor Compression Management Unit
    0x68C : {
        "name": "VCMU", "tx": 0x68C, "rx": 0x69C, 
        "dids" :
        {
            256: RawCodec(36, "BusIdentification"),
            257: RawCodec(122, "StatusDtcList"),
            258: RawCodec(122, "StatusDtcHistory"),
            259: RawCodec(122, "InfoDtcList"),
            260: RawCodec(122, "InfoDtcHistory"),
            261: RawCodec(122, "ServiceDtcList"),
            262: RawCodec(122, "ServiceDtcHistory"),
            263: RawCodec(122, "WarningDtcList"),
            264: RawCodec(124, "WarningDtcHistory"),
            265: RawCodec(122, "ErrorDtcList"),
            266: RawCodec(124, "ErrorDtcHistory"),
            320: RawCodec(9, "PrimaryHeatExchangerLiquidTemperatureSensor"),
            321: RawCodec(9, "CompressorInletTemperatureSensor"),
            322: RawCodec(9, "CompressorInletPressureSensor"),
            323: RawCodec(9, "EnhancedVapourInjectionTemperatureSensor"),
            324: RawCodec(9, "CompressorOutletTemperatureSensor"),
            325: RawCodec(9, "CompressorOutletPressureSensor"),
            354: RawCodec(1, "PrimaryHeatExchangerBaseHeater"),
            355: RawCodec(9, "SecondaryHeatExchangerLiquidTemperatureSensor"),
            377: RawCodec(16, "ViessmannIdentificationNumber"),
            388: RawCodec(1, "ElectronicExpansionValveOneTargetPositionPercent"),
            389: RawCodec(1, "ElectronicExpansionValveOneCurrentPositionPercent"),
            505: RawCodec(3, "Date"),
            506: RawCodec(3, "Time"),
            507: RawCodec(4, "UniversalTimeCoordinated"),
            573: RawCodec(2, "RemoteReset"),
            576: RawCodec(3, "SetDeliveryStatusDate"),
            580: RawCodec(8, "SoftwareVersion"),
            581: RawCodec(8, "HardwareVersion"),
            901: RawCodec(1, "ServiceManagerIsRequired"),
            902: RawCodec(1, "MalfunctionIdentification"),
            928: RawCodec(16, "ElectronicTraceabilityNumber"),
            954: RawCodec(73, "BusTopologyMatrix"),
            962: RawCodec(8, "BootLoaderVersion"),
            963: RawCodec(16, "SparePartNumber"),
            964: RawCodec(1, "ActiveDiagnosticSession"),
            1141: RawCodec(10, "CustomerIndividualParameters"),
            1166: RawCodec(5, "ResetDtcHistory"),
            1175: RawCodec(1, "AcknowledgeInfoAlarmMessage"),
            1176: RawCodec(1, "AcknowledgeWarningAlarmMessage"),
            1177: RawCodec(1, "AcknowledgeServiceAlarmMessage"),
            1178: RawCodec(1, "AcknowledgeErrorAlarmMessage"),
            1239: RawCodec(2, "ActorSensorTest"),
            1283: RawCodec(26, "HeatEnginePerformanceParameter"),
            1339: RawCodec(1, "MalfunctionHeatingUnitBlocked"),
            1467: RawCodec(2, "SafetyRelevantRemoteUnlock"),
            1493: RawCodec(16, "HeatEnginePerformanceStatistics"),
            1494: RawCodec(8, "OemProductVersion"),
            1553: RawCodec(6, "ElectronicControlUnitOdxVersion"),
            1595: RawCodec(8, "ParameterIdentificationVersionFactory"),
            1768: RawCodec(9, "ReceiverTemperatureSensor"),
            1769: RawCodec(9, "PrimaryInletTemperatureSensor"),
            1770: RawCodec(9, "SecondaryOutletTemperatureSensor"),
            1771: RawCodec(9, "EngineRoomTemperatureSensor"),
            1772: RawCodec(9, "CompressorOilTemperatureSensor"),
            1773: RawCodec(1, "RefrigerantCircuitFourWayValve"),
            1774: RawCodec(1, "CompressorCrankCaseHeater"),
            1775: RawCodec(1, "PrimaryCircuitFanOne"),
            1776: RawCodec(1, "PrimaryCircuitFanTwo"),
            1846: RawCodec(4, "HeatPumpCompressorCurrentOperatingPoint"),
            2255: RawCodec(2, "MinimumSecondaryReturnTemperatureRefrigerantCircuit"),
            2256: RawCodec(2, "DesiredThermalEnergyDefrost"),
            2259: RawCodec(1, "RefrigerationCircuitStatus"),
            2342: RawCodec(4, "NominalThermalCapacityHeating"),
            2343: RawCodec(4, "NominalThermalCapacityCooling"),
            2345: RawCodec(1, "CompressorSetpointPercent"),
            2346: RawCodec(1, "CompressorSpeedPercent"),
            2351: RawCodec(2, "HeatPumpCompressor"),
            2369: RawCodec(14, "HeatPumpCompressorStatistical"),
            2486: RawCodec(4, "CurrentElectricalPowerConsumptionRefrigerantCircuit"),
            2494: RawCodec(4, "CurrentThermalCapacityRefrigerantCircuit"),
            2568: RawCodec(1, "RefrigerantType"),
            2569: RawCodec(2, "CompressorSpeedRps"),
            2573: RawCodec(2, "CompressorOnTimer"),
            2578: RawCodec(1, "RefrigerationCircuitDesiredOperatingMode"),
            2579: RawCodec(4, "CompressorMinMaxAllowedPrimaryTemperatureHeating"),
            2580: RawCodec(2, "CompressorSetpointRps"),
            2582: RawCodec(2, "CompressorOffTimer"),
            2612: RawCodec(7, "PrimarySourceCommonSettingsHeating"),
            2613: RawCodec(7, "PrimarySourceCommonSettingsCooling"),
            2629: RawCodec(4, "DesiredThermalCapacity"),
            2630: RawCodec(4, "CompressorMinMaxSpeedHeating"),
            2631: RawCodec(4, "CompressorMinMaxSpeedCooling"),
            2632: RawCodec(4, "CompressorMinMaxSpeedDefrost"),
            2633: RawCodec(12, "MaxSpeedNoiseReductionMode"),
            2634: RawCodec(1, "NoiseReductionMode"),
            2784: RawCodec(9, "SecondaryHeatExchangerVaporPressureSensor"),
            2806: RawCodec(2, "RefrigerationCircuitOperationMode"),
            2844: RawCodec(2, "SecondaryHeatExchangerMinimumOutletTemperature"),
            2845: RawCodec(2, "SecondaryHeatExchangerMaximumOutletTemperature"),
            2894: RawCodec(1, "RefrigerantCycleAvailability"),
            2969: RawCodec(1, "ElectronicControlUnitSafeStateStatus"),
            3014: RawCodec(9, "OutdoorMiddleCoilTemperatureSensor"),
            3015: RawCodec(9, "HeatSinkTemperatureSensor"),
            3019: RawCodec(9, "CompressorOutletTargetTemperature"),
        }
    }
}
