"""
   Copyright 2023 abnoname
   
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

E3Enums = {
    "Errors" : {
        0:"NoErrorAvailable",
        1:"InterruptionFlowTemperatureSensor",
        2:"ShortCircuitFlowTemperatureSensor",
        3:"InterruptionReturnTemperatureSensor",
        4:"ShortCircuitReturnTemperatureSensor",
        5:"InterruptionWaterFlowSensor",
        6:"ShortCircuitWaterFlowSensor",
        7:"InterruptionDomesticHotWaterSensor",
        8:"ShortCircuitDomesticHotWaterSensor",
        9:"InterruptionDomesticHotWaterFlowSensor",
        10:"ShortCircuitDomesticHotWaterFlowSensor",
        11:"InterruptionSolarRoofSensor",
        12:"ShortCircuitSolarRoofSensor",
        13:"InterruptionOutsideTemperatureSensor",
        14:"ShortCircuitOutsideTemperatureSensor",
        15:"InterruptionSolarBottomSensor",
        16:"ShortCircuitSolarBottomSensor",
        17:"InterruptionSolarTopSensor",
        18:"ShortCircuitSolarTopSensor",
        19:"InterruptionBufferBottomSensor",
        20:"ShortCircuitBufferBottomSensor",
        21:"InterruptionBufferMidBottomSensor",
        22:"ShortCircuitBufferMidBottomSensor",
        23:"InterruptionBufferMidSensor",
        24:"ShortCircuitBufferMidSensor",
        25:"InterruptionBufferMidTopSensor",
        26:"ShortCircuitBufferMidTopSensor",
        27:"InterruptionBufferTopSensor",
        28:"ShortCircuitBufferTopSensor",
        29:"InterruptionLowLossTemperatureSensor",
        30:"ShortCircuitLowLossTemperatureSensor",
        31:"InterruptionMixerHeatingCircuitSensor",
        32:"ShortCircuitMixerHeatingCircuitSensor",
        33:"InterruptionPrimaryInletTemperatureSensor",
        34:"ShortCircuitPrimaryInletTemperatureSensor",
        35:"InterruptionBrineOutletTemperatureSensor",
        36:"ShortCircuitBrineOutletTemperatureSensor",
        37:"InterruptionWaterPressureSensor",
        38:"ShortCircuitWaterPressureSensor",
        39:"InterruptionBrinePresssureSensor",
        40:"ShortCircuitBrinePressureSensor",
        41:"InterruptionOutsideSupplyAirTemperatureSensor",
        42:"ShortCircuitOutsideSupplyAirTemperatureSensor",
        43:"InterruptionIncomingAirTemperatureSensor",
        44:"ShortCircuitIncomingAirTemperatureSensor",
        45:"InterruptionOutcomingAirTemperatureSensor",
        46:"ShortCircuitOutcomingAirTemperatureSensor",
        47:"InterruptionUsedAirTemperatureSensor",
        48:"ShortCircuitUsedAirTemperatureSensor",
        49:"InterruptionFlueGasTemperatureSensor",
        50:"ShortCircuitFlueGasTemperatureSensor",
        51:"InterruptionFlowOneSensorOrSwitch",
        52:"ShortCircuitFlowOneSensorOrSwitch",
        53:"InterruptionFlowTwoSensorOrSwitch",
        54:"ShortCircuitFlowTwoSensorOrSwitch",
        55:"InterruptionCoSensor",
        56:"ShortCiruitCoSensor",
        57:"InterruptionRoomTemperatureSensor",
        58:"ShortCircuitRoomTemperatureSensor",
        59:"PowerSupplyLowVoltageDetection",
        60:"PowerSupplyOverloadDetection",
        61:"FailureInternalPowerSupply",
        62:"OverHeatingProtectionSafetyTemperatureLimiter",
        63:"OverHeatingProtectionFlueGasSystem",
        64:"FlameLostDuringOperation",
        65:"NoFlameDuringStarting",
        66:"DefectIgnitor",
        67:"FailureIoniSignal",
        68:"FailureExtraneousLight",
        69:"FailureElectronicAirGasRatioSystem",
        70:"FailureInternalBurnerControlSystem",
        71:"FailureTargetFanSpeedNotAchieved",
        72:"FailureZeroFanSpeedNotAchieved",
        73:"InternalCommunicationError",
        74:"WaterPressureTooLow",
        75:"NoWaterFlowDetection",
        76:"NoValidViessmannIdentificationNumberAvailable",
        77:"FailurePersistentMemory",
        78:"FailureHmiCommunication",
        79:"FailureAdioModuleAnalogPortOne",
        80:"FailureAdioModuleAnalogPortTwo",
        81:"FailureAdioModuleAnalogPortThree",
        82:"FailureCommunicationMixerModule",
        83:"FailureMixerModuleDigitalOutput",
        84:"FailureMissingPowerSupplyPhase",
        85:"FailureWrongDirectionPowerSupplyPhaseAssignment",
        86:"FailureFlueGasRecirculationDetection",
        87:"OverloadSystemWaterPressure",
        88:"FailureSacrificialAnode",
        89:"FailureBlockingCentralHeatingPump",
        90:"FailureBlockingThreewayValve",
        91:"FailureCommunicationDioModule",
        92:"FailureCommunicationAdioModule",
        93:"FailureCommunicationMTwoIoModule",
        94:"FailureCommunicationSdioModule",
        95:"FailureCommunicationOpenTherm",
        96:"FailureDioModuleDigitalPortOne",
        97:"FailureDioModuleDigitalPortTwo",
        98:"FailureDioModuleDigitalPortThree",
        99:"FailurePlusBusCommunication",
        100:"FailurePlusBusVoltage",
        101:"FailurePlusBusShortCircuit",
        102:"FailureInternalCommunicationWiFiModule",
        103:"FailureInternalCommunicationHmiModule",
        104:"FailureExternalDevice",
        105:"FailureElectronicControlUnit",
        106:"FailureSuctionTemperatureSensor",
        107:"FailureDischargeTemperatureSensor",
        108:"FailureDischargePressureSensor",
        109:"FailureLiquidTemperatureOneSensor",
        110:"FailureLiquidTemperatureTwoSensor",
        111:"InterruptionPrimaryHeatExchangerLiquidTemperatureSensor",
        112:"ShortCircuitPrimaryHeatExchangerLiquidTemperatureSensor",
        113:"InterruptionCompressorInletPressureSensor",
        114:"ShortCircuitCompressorInletPressureSensor",
        115:"InterruptionIntermedPressureSensor",
        116:"ShortCircuitIntermedPressureSensor",
        117:"InterruptionEvaporatorVaporTemperatureSensor",
        118:"ShortCircuitEvaporatorVaporTemperatureSensor",
        119:"InterruptionLiquidLineTemperatureSensor",
        120:"ShortCircuitLiquidLineTemperatureSensor",
        121:"FailureCommunicationElectricalInverter",
        122:"FailureElectricalInverterIsUnsuitable",
        123:"InterruptionSecondaryHeatExchangerLiquidTemperatureSensor",
        124:"ShortCircuitSecondaryHeatExchangerLiquidTemperatureSensor",
        125:"InterruptionInverterAmbientTemperatureSensor",
        126:"ShortCircuitInverterAmbientTemperatureSensor",
        127:"FailureElectronicExpansionValveMotor",
        128:"OverHeatingDischargeSuperHeater",
        129:"InterruptionLiquidLevelSensor",
        130:"ShortCircuitLiquidLevelSensor",
        131:"FailureInrushCurrentLimiter",
        132:"FailureInverterDriver",
        133:"FailureElectronicControlUnitInverter",
        134:"FailureCommunicationInverter",
        135:"FailurePhaseLoss",
        136:"InterruptionPhaseOneSensor",
        137:"ShortCircuitPhaseOneSensor",
        138:"InterruptionPhaseTwoSensor",
        139:"ShortCircuitPhaseTwoSensor",
        140:"InterruptionPhaseThreeSensor",
        141:"ShortCircuitPhasethreeSensor",
        142:"FailureCommunicationFanModule",
        143:"OverheatingFanModule",
        144:"FailureSpeedSensorFanModule",
        145:"unused",
        146:"unusedTwo",
        147:"InterruptionCompressorInletTemperatureSensor",
        148:"ShortCircuitCompressorInletTemperatureSensor",
        149:"InterruptionEconomizerLiquidTemperatureSensor",
        150:"ShortCircuitEconomizerLiquidTemperatureSensor",
        151:"InterruptionCompressorOutletTemperatureSensor",
        152:"ShortCircuitCompressorOutletTemperatureSensor",
        153:"InterruptionCompressorOutletPressureSensor",
        154:"ShortCircuitCompressorOutletPressureSensor",
        155:"FailureElectronicExpansionValveOne",
        156:"FailureElectronicExpansionValveTwo",
        157:"WatchdogHasTriggered",
        158:"AnalogDigitalConverterException",
        159:"DigitalAnalogConverterException",
        160:"CanCommunicationException",
        161:"RandomAccessMemoryException",
        162:"MicroControllerLowVoltageDetection",
        163:"CyclicRedundancyCheckException",
        164:"ErrorCodeCorrectionException",
        165:"GridBlackout",
        166:"GridVoltageUnstableOverShoot",
        167:"GridVoltageUnstableUnderShoot",
        168:"GridFrequencyUnstableOverShoot",
        169:"GridFrequencyUnstableUnderShoot",
        170:"GridOverVoltageEffectiveValue",
        171:"GridUnderVoltageEffectiveValue",
        172:"GridVoltageSensorFailure",
        173:"GridCurrentSensorFailure",
        174:"GridOverCurrent",
        175:"DirectCurrentFailure",
        176:"DirectCurrentPowerSupplyFailure",
        177:"ParameterIdentificationNumberIsDifferent",
        178:"ParameterIdentificationNumberSynchroHasFailed",
        179:"ParameterIdentificationNumberIsNotEntered",
        180:"GasPressureLow",
        181:"NoCentralHeatingFlowWater",
        182:"ShortCircuitDomesticHotWaterOutletSensor",
        183:"InterruptionDomesticHotWaterOutletSensor",
        184:"ShortCircuitSafetyTemperatureLimiter",
        185:"InterruptionSafetyTemperatureLimiter",
        186:"ErrorFuelValve",
        187:"ErrorFuelValveDriver",
        188:"ErrorFuelValuePlausibilityCheck",
        189:"FuelCellBBFlameRodFailure",
        190:"FuelCellBBFlameRodFailureS",
        191:"FuelCellFlameRodFailure",
        192:"WaterNotFilled",
        193:"RunOutOfWaterFillingTime",
        194:"RunOutOfWaterRemovingProcedureTime",
        195:"CoDetection",
        196:"FlammableGasDetection",
        197:"FuelCellSoundnessCheckFailure",
        198:"IgnitionFailureOnStartUp",
        199:"IgnitionFailureAfterReignition",
        200:"HighCoConcentrationDetected",
        201:"FuelCellHighCoConcentrationDetectedS",
        202:"LowCoConcentrationDetected",
        203:"FuelCellLowCoConcentrationDetectedS",
        204:"FlameLostDuringHighCoConcentration",
        205:"FuelCellFlammableGasExhaustRisk",
        206:"FuelCellHighBackPressure",
        207:"RealtimeClockTemperatureAbnormityA",
        208:"RealtimeClockTemperatureAbnormityB",
        209:"RealtimeClockTemperatureAbnormityC",
        210:"StartUpFailureShiftCatalystThermocouple",
        211:"StartupFailurePreferentialOxidationTemperatureSensor",
        212:"ReformingThermocoupleTemperatureHigh",
        213:"ReformingThermocoupleDisconnection",
        214:"ReformingThermocoupleShortCircuit",
        215:"StartUpProcessWaterPumpTemperatureLow",
        216:"StoppingProcessWaterPumpTemperatureHigh",
        217:"ShiftCatalystThermocoupleLowTemperatureInGenerating",
        218:"ShiftCatalystThermocoupleHighTemperatureInOperation",
        219:"ShiftCatalystThermocoupleDisconnection",
        220:"ShiftCatalystThermocoupleShortCircuit",
        221:"ShiftCatalystThermocoupleLowTemperatureOnStartUp",
        222:"ShiftCatalystThermocoupleHighTemperatureInStopping",
        223:"PreferredOxidationTemperatureSensorLowTemperatureInGenerating",
        224:"PreferredOxidationTemperatureSensorHighTemperatureInOperating",
        225:"PreferredOxidationTemperatureSensorDisconnection",
        226:"PreferredOxidationTemperatureSensorShortCircuit",
        227:"PreferredOxidationTemperatureSensorLowTemperatureOnStartUp",
        228:"DesulfurizingThermocoupleLowTemperature",
        229:"DesulfurizingThermocoupleDisconnection",
        230:"DesulfurizingThermocoupleShortCircuit",
        231:"DesulfurizingThermocoupleHighTemperature",
        232:"DesulfurizingThermocoupleTemperatureErrorOnStartup",
        233:"FuelCellInletWaterThermistorDisconnection",
        234:"FuelCellInletWaterThermistorShortCircuit",
        235:"FuelCellOutletWaterThermistorDisconnection",
        236:"FuelCellOutletWaterThermistorShortCircuit",
        237:"FuelCellOutletWaterThermistorLowTemperature",
        238:"FuelCellOutletWaterThermistorHighTemperature",
        239:"CombustionAirFanBFailure",
        240:"CombustionAirFanBRotationSpeedFailureS",
        241:"CombustionAirFanBRotationSpeedFailureA",
        242:"FuelCellVentilationFanAFailure",
        243:"FuelCellGasValveAFailure",
        244:"FuelCellGasValveBFailure",
        245:"FuelCellFlammableGasDetector",
        246:"CoSensorFailure",
        247:"CoSensorSignalShift",
        248:"FuelCellCoolingWaterCirculationPumpAirAccumulation",
        249:"FuelCellCoolingWaterCirculationPumpAtTestRun",
        250:"FuelCellFuelProcessorElectricalHeaterRelayFailure",
        251:"ExhaustGasPressureSensorDisconnection",
        252:"ExhaustGasPressureSensorShortCircuit",
        253:"FuelCellVentilationFlapSticking",
        254:"SdCardFailure",
        255:"SdCardCommandError",
        256:"SdCardFormatError",
        257:"SdCardWriteProtection",
        258:"SdCardOutOfMemory",
        259:"SdCardUndetectable",
        260:"FuelCellPowerManagementSystemInverterFailure",
        261:"FuelCellElectricCircuitPowerFailure",
        262:"FuelCellEepromAccessFailureABoard",
        263:"FuelCellEepromAccessFailureVBoard",
        264:"FuelCellEepromAccessFailureSBoard",
        265:"FuelCellCommunicationErrorVBoard",
        266:"FuelCellCommunicationErrorABoard",
        267:"CommunicationErrorSdCard",
        268:"FuelCellCommunicationErrorSBoard",
        269:"FuelCellCommunicationErrorViBoardPanasonicBoard",
        270:"FuelCellSBoardInternalPartsFailure",
        271:"FuelCellSBoardCircuitFailure",
        272:"FuelCellSBoardSoftwareFailure",
        273:"FuelCellOperationControlFailure",
        274:"FuelCellSystemInletThermistorDisconnection",
        275:"FuelCellSystemInletThermistorShortCircuit",
        276:"FuelCellSystemOutletThermistorDisconnection",
        277:"FuelCellSystemOutletThermistorShortCircuit",
        278:"FuelCellAntiFreezingThermistorDisconnection",
        279:"FuelCellAntiFreezingThermistorShortCircuit",
        280:"FuelCellSystemInletTemperatureFailure",
        281:"FuelCellCondensDrainTankThermistorDisconnection",
        282:"FuelCellCondensDrainTankThermistorShortCircuit",
        283:"FuelCellCoolingWaterTankThermistorDisconnection",
        284:"FuelCellCoolingWaterTankThermistorShortCircuit",
        285:"FuelCellCoolingWaterTankThermistorHighTemperature",
        286:"FuelCellAmbientThermistorDisconnection",
        287:"FuelCellAmbientThermistorShortCircuit",
        288:"FuelCellIntegratedGasPurgeVolumeFailure",
        289:"FuelCellIntegratedGasPurgeVolumeAtFlameOut",
        290:"GasFlowMeterFailure",
        291:"FuelCellGasFlowMeterLowFlowRateOne",
        292:"FuelCellGasFlowMeterLowFlowRateTwo",
        293:"FuelCellDesulfurizerRunOutOfHydrogen",
        294:"ChimneyBlockage",
        295:"FuelCellPreferentialOxidationAirFlowMeterFailure",
        296:"FuelCellGasUtilityFailure",
        297:"GasPressureSensorFailure",
        298:"FuelCellIgniterCircuitFailure",
        299:"RealTimeClockFailure",
        300:"FuelCellPowerConditioningSystemOutputOverCurrentEffectiveValue",
        301:"FuelCellPowerConditioningSystemOutputOverCurrentInstantValue",
        302:"FuelCellPowerConditioningSystemOutputOverCurrentIpmFailure",
        303:"FuelCellPowerConditioningSystemInputVoltageDropOne",
        304:"FuelCellPowerConditioningSystemInputVoltageDropTwo",
        305:"FuelCellPowerConditioningSystemInputVoltageDropThree",
        306:"FuelCellCurrentSensorFailure",
        307:"PowerSupplyFailure",
        308:"LowPowerSupplyFailure",
        309:"LowPowerSupplyABoardFailure",
        310:"LowLowPowerSupplyFailure",
        311:"FuelCellPowerConditioningSystemInputOvervoltage",
        312:"DirectCurrentOvervoltageDetectedByHardware",
        313:"DirectCurrentOvervoltageDetectedBySoftware",
        314:"DirectCurrentVoltageDropDetectedBySoftware",
        315:"FuelCellPowerConditioningSystemFanFailure",
        316:"FuelCellPowerConditioningSystemInputOverCurrent",
        317:"FuelCellPowerConditioningSystemInputCurrentSensorFailure",
        318:"GridVoltageAnalogDigitalConverterFailure",
        319:"RemoteControlCommandFailure",
        320:"FuelCellSurplusPowerHeaterDisconnection",
        321:"FuelCellSurplusPowerConverterCurrentSensorFailure",
        322:"FuelCellSurplusPowerConverterVoltageSensorFailure",
        323:"AlternatingCurrentOvervoltageEffectiveValue",
        324:"AlternatingCurrentOvervoltageAverageValue",
        325:"AlternatingCurrentOvervoltageUandWPhaseEffectiveValue",
        326:"AlternatingCurrentOvervoltageUandWPhaseInstantValue",
        327:"IsolatingDetectionPassive",
        328:"IsolatingDetectionActive",
        329:"DirectCurrentPartDrain",
        330:"EmergencyEngineBlocked",
        331:"EmergencyEngineSecurityOverCurrent",
        332:"EmergencyEngineSecurityOverCurrentWaitActive",
        333:"EnergySaveStateValveUnknown",
        334:"EnergySaveStateMassflowSensorUnknown",
        335:"EnergySaveStateStepperMotorUnknown",
        336:"ActualMassflowDeviationStateValueUnusable",
        337:"ActualMassflowDeviationStateValueWrong",
        338:"ActualAirTempDeviationStateNotOk",
        339:"ActualMotorSpeedDeviationStateUnusable",
        340:"ActualMassflowSlowDeviationStateValueUnusable",
        341:"FailureCommunicationFuelCell",
        342:"FailureCommunicationBurnerControlUnit",
        343:"ShortCircuitLowLossHeaderReturnTemperatureSensor",
        344:"InterruptionLowLossHeaderReturnTemperatureSensor",
        345:"OverHeatingProtectionTemperatureLimiter",
        346:"FailureIonisationCalibration",
        347:"AirGasRatioFeedbackDetection",
        348:"FailureGasValveAdaption",
        349:"FailureAirMassFlowAdaption",
        350:"FailureIonisationVoltageGenerationMonitoring",
        351:"FailureIonisationCurrentPlausibilityCheck",
        352:"FailureInternalAirGasRatioMonitoring",
        353:"FailureRetractFunctionMonitoring",
        354:"FailureGasValveFactoryOffset",
        355:"FailureSignalReferenceCheck",
        356:"NoFlameDuringStartingGasPressureInsufficientSafetyShutDown",
        357:"NoFlameDuringStartingGasPressureInsufficientLockOut",
        358:"NoFlameDuringStartingNoIgnitionSafetyShutDown",
        359:"NoFlameDuringStartingNoIgnitionLockOut",
        360:"NoFlameDuringStartingAgedIonizationElectrodeShutDown",
        361:"NoFlameDuringStartingAgedIonizationElectrodeLockOut",
        362:"NoFlameDuringStartingIonisationValueReferenceExaminationShutDown",
        363:"NoFlameDuringStartingIonisationValueReferenceExaminationLockOut",
        364:"FiniteStateMachineSystemErrorEntry",
        365:"FiniteStateMachineGasValveRelayTestFailure",
        366:"FiniteStateMachineGasValveWatchdogChannelOneTestFailure",
        367:"FiniteStateMachineGasValveWatchdogChannelTwoTestFailure",
        368:"FiniteStateMachineLowGasPressure",
        369:"FiniteStateMachineFlameLostDuringSafetyTime",
        370:"FiniteStateMachineGasValveRelayPlausibilityCheckFailure",
        371:"FiniteStateMachineLowerFanSpeedBoundFailure",
        372:"FiniteStateMachineFlameLostDuringIoCalibration",
        373:"FiniteStateMachineIoCalibrationOverheatingProtection",
        374:"FiniteStateMachineIoCalibrationPreProcessingStationaryStateFailure",
        375:"FiniteStateMachineIoCalibrationMinimumIncreaseAbortConditionFailure",
        376:"FiniteStateMachineIoCalibrationIonisationMaximumPlausibilityCheckFailure",
        377:"FiniteStateMachineIoCalibrationPostProcessingStationaryStateFailure",
        378:"FiniteStateMachineFlameLostDuringFlameStabilisation",
        379:"FiniteStateMachineNoFlameDuringStartLockOut",
        380:"FiniteStateMachineFlameLostDuringStartLockOut",
        381:"FiniteStateMachineFlameLostDuringOperationLockOut",
        382:"FiniteStateMachineSystemErrorEntryLockOut",
        383:"FiniteStateMachineMainGasValveShutOffFailure",
        384:"FiniteStateMachineModulationGasValveShutOffFailure",
        385:"ShortCircuitIonisationCurrentSignalOne",
        386:"InterruptionIonisationCurrentSignalOne",
        387:"ShortCircuitIonisationCurrentSignalTwo",
        388:"InterruptionIonisationCurrentSignalTwo",
        389:"ShortCircuitInternalPumpFeedbackSignal",
        390:"InterruptionInternalPumpFeedbackSignal",
        391:"ShortCircuitFlowTemperatureSensorTwo",
        392:"InterruptionFlowTemperatureSensorTwo",
        393:"ShortCircuitFlueGasTemperatureSensorTwo",
        394:"InterruptionFlueGasTemperatureSensorTwo",
        395:"ShortCircuitFlameTemperatureSignalOne",
        396:"InterruptionFlameTemperatureSignalOne",
        397:"ShortCircuitFlameTemperatureSignalTwo",
        398:"InterruptionFlameTemperatureSignalTwo",
        399:"ShortCircuitIonisationVoltageOne",
        400:"InterruptionIonisationVoltageOne",
        401:"ShortCircuitIonisationVoltageTwo",
        402:"InterruptionIonisationVoltageTwo",
        403:"ShortCircuitDynamicIonisationCurrentSignalOne",
        404:"InterruptionDynamicIonisationCurrentSignalOne",
        405:"ShortCircuitDynamicIonisationCurrentSignalTwo",
        406:"InterruptionDynamicIonisationCurrentSignalTwo",
        407:"SignalEvaluationSafetyChain",
        408:"SignalEvaluationGasValveRelayOne",
        409:"SignalEvaluationGasValveRelayTwo",
        410:"FailureValidationMicroControllerSpecialFunctionRegister",
        411:"ShortCircuitInternalBoilerSensorOne",
        412:"InterruptionInternalBoilerSensorOne",
        413:"ShortCircuitInternalBoilerSensorTwo",
        414:"InterruptionInternalBoilerSensorTwo",
        415:"FailureCommunicationMBusGatewayOne",
        416:"FlueGasTemperatureSensorNotInPosition",
        417:"ShortCircuitLowPowerSupply",
        418:"InterruptionLowPowerSupply",
        419:"ShortCircuitPowerSupply",
        420:"InterruptionPowerSupply",
        421:"FailurePersistentMemorySafetyRelevant",
        422:"FailurePersistentMemorySupplierParameter",
        423:"FailurePersistentMemoryCodingParameter",
        424:"FailurePersistentMemoryApplicationParameter",
        425:"FailureTimeSynchronizationFailed",
        426:"ExternalUnlockSignalRangeLowValue",
        427:"ExternalUnlockSignalRangeHighValue",
        428:"ExternalAirMassFlowSensorRangeLowValue",
        429:"ExternalAirMassFlowSensorRangeHighValue",
        430:"FailureCommunicationAutomationGateway",
        431:"FailureKnxCommunication",
        432:"ExternalFanSpeedSensorRangeLowValue",
        433:"ExternalFanSpeedSensorRangeHighValue",
        434:"ExternalPowerSupplyMonitoringRangeLowValue",
        435:"ExternalPowerSupplyMonitoringRangeHighValue",
        436:"ExternalAllengraWaterFlowSensorRangeLowValue",
        437:"ExternalAllengraWaterFlowSensorRangeHighValue",
        438:"ExternalAllengraTemperatureSensorRangeLowValue",
        439:"ExternalAllengraTemperatureSensorRangeHighValue",
        440:"ExternalGasPressureSwitchRangeLowValue",
        441:"ExternalGasPressureSwitchRangeHighValue",
        442:"ExternalFlueGasFlapRangeLowValue",
        443:"ExternalFlueGasFlapRangeHighValue",
        444:"ExternalSafetyGasValveRangeLowValue",
        445:"ExternalSafetyGasValveRangeHighValue",
        446:"SignalCompareSafetyTemperatureLimiterDeviation",
        447:"SignalCompareIonisationVoltageDeviation",
        448:"SignalCompareIonisationCurrentDeviation",
        449:"WatchdogTimerLowSignalTrigger",
        450:"WatchdogTimerHighSignalTrigger",
        451:"FailureMainProgramRotationSynchronisation",
        452:"FailureControllerSynchronisation",
        453:"FailureFiniteStateMachineNextStepComparison",
        454:"FailureSoftwareConfiguration",
        455:"FailureLogicalProgramFlowMonitoring",
        456:"FailureStartupControllerSynchronisationToken",
        457:"FailureFanModuleEmergencyMessage",
        458:"FailureUnlockSignalPlausibilityCheck",
        459:"FiniteStateMachineCalibrationErrorSafetyShutDown",
        460:"FiniteStateMachineGeneralErrorSafetyShutDown",
        461:"FiniteStateMachineFlueGasFlapFailure",
        462:"FiniteStateMachineSafetyGasValveFailure",
        463:"FailureCalibrationMaximumIonisationLowerFactoryBound",
        464:"FailureCalibrationMaximumIonisationPredecessorValueBound",
        465:"FailureCalibrationMaximumIonisationStationaryStateNotReached",
        466:"FailureCalibrationMaximumIonisationNotPossible",
        467:"FailureCalibrationMaximumIonisationAbortConditionNotReached",
        468:"FailureCalibrationMaximumIonisationUpperFactoryBound",
        469:"FailureCalibrationMaximumIonisationOverheat",
        470:"UpdateError",
        471:"WaterPressureSensorNotAvailable",
        472:"FailureCommunicationEnergyMeter",
        473:"FailureCommunicationHMU",
        474:"FailureTimingProgramFlowMonitoring",
        475:"AirInFuelCellSeparationCircuit",
        476:"FuelCellAmbientTemperatureTooHigh",
        477:"FailureSolarDeltaTemperatureMonitoring",
        478:"FailureNightCirculationMonitoring",
        479:"ShortCircuitStepperMotorOne",
        480:"ShortCircuitStepperMotorTwo",
        481:"MixerFlowTemperatureSensorNotAvailable",
        482:"MixerOneFlowTemperatureSensorNotAvailable",
        483:"MixerTwoFlowTemperatureSensorNotAvailable",
        484:"MixerThreeFlowTemperatureSensorNotAvailable",
        485:"MixerFourFlowTemperatureSensorNotAvailable",
        486:"MixerFiveFlowTemperatureSensorNotAvailable",
        487:"MixerSixFlowTemperatureSensorNotAvailable",
        488:"MixerSevenFlowTemperatureSensorNotAvailable",
        489:"MixerEightFlowTemperatureSensorNotAvailable",
        490:"MixerNineFlowTemperatureSensorNotAvailable",
        491:"MixerTenFlowTemperatureSensorNotAvailable",
        492:"MixerElevenFlowTemperatureSensorNotAvailable",
        493:"MixerTwelveFlowTemperatureSensorNotAvailable",
        494:"MixerThirteenFlowTemperatureSensorNotAvailable",
        495:"MixerFifteenFlowTemperatureSensorNotAvailable",
        496:"MixerSixteenFlowTemperatureSensorNotAvailable",
        497:"MixerReturnTemperatureSensorNotAvailable",
        498:"MixerOneReturnTemperatureSensorNotAvailable",
        499:"MixerTwoReturnTemperatureSensorNotAvailable",
        500:"MixerThreeReturnTemperatureSensorNotAvailable",
        501:"MixerFourReturnTemperatureSensorNotAvailable",
        502:"MixerFiveReturnTemperatureSensorNotAvailable",
        503:"MixerSixReturnTemperatureSensorNotAvailable",
        504:"MixerSevenReturnTemperatureSensorNotAvailable",
        505:"MixerEightReturnTemperatureSensorNotAvailable",
        506:"MixerNineReturnTemperatureSensorNotAvailable",
        507:"MixerTenReturnTemperatureSensorNotAvailable",
        508:"MixerElevenReturnTemperatureSensorNotAvailable",
        509:"MixerTwelveReturnTemperatureSensorNotAvailable",
        510:"MixerThirteenReturnTemperatureSensorNotAvailable",
        511:"MixerFifteenReturnTemperatureSensorNotAvailable",
        512:"MixerSixteenReturnTemperatureSensorNotAvailable",
        513:"HydraulicSeparatorNotAvailable",
        514:"SolarFlowTemperatureSensorNotAvailable",
        515:"SolarReturnTemperatureSensorNotAvailable",
        516:"SolarRoofSensorNotAvailable",
        517:"FailureCommunicationWiredRemoteControl",
        518:"FailureCommunicationWirelessRemoteControl",
        519:"FailureBacNetCommunication",
        520:"FailureModbusCommunication",
        521:"MixerFourteenFlowTemperatureSensorNotAvailable",
        522:"MixerFourteenReturnTemperatureSensorNotAvailable",
        523:"NoFlameDuringStartingBeforeSupplyingReformingWater",
        524:"NoFlameDuringStartingAfterSupplyingReformingWater",
        525:"FailureCoDetectionUnit",
        526:"CoSensorSignalShiftA",
        527:"ParameterizationIncomplete",
        528:"BaseProgrammingIncomplete",
        529:"ProcessWaterValveOpenLocked",
        530:"SolarFunctionRestrictedDueToMissingSensorValue",
        531:"EnergyStorageCellDrift",
        532:"EnergyStorageCellOverVoltage",
        533:"EnergyStorageCellUnderVoltage",
        534:"FailureCommunicationEnergyStorage",
        535:"FailureCommunicationEnergyStorageCell",
        536:"InterruptionSystemFlowTemperatureSensor",
        537:"ShortCircuitSystemFlowTemperatureSensor",
        538:"InterruptionSystemReturnTemperatureSensor",
        539:"ShortCircuitSystemReturnTemperatureSensor",
        540:"HeatCellCondensatDetection",
        541:"FailureExhaustFlapFeedback",
        542:"InterruptionMixerOneFlowTemperatureSensor",
        543:"ShortCircuitMixerOneFlowTemperatureSensor",
        544:"InterruptionMixerTwoFlowTemperatureSensor",
        545:"ShortCircuitMixerTwoFlowTemperatureSensor",
        546:"InterruptionMixerThreeFlowTemperatureSensor",
        547:"ShortCircuitMixerThreeFlowTemperatureSensor",
        548:"InterruptionMixerFourFlowTemperatureSensor",
        549:"ShortCircuitMixerFourFlowTemperatureSensor",
        550:"InterruptionMixerFiveFlowTemperatureSensor",
        551:"ShortCircuitMixerFiveFlowTemperatureSensor",
        552:"InterruptionMixerSixFlowTemperatureSensor",
        553:"ShortCircuitMixerSixFlowTemperatureSensor",
        554:"InterruptionMixerSevenFlowTemperatureSensor",
        555:"ShortCircuitMixerSevenFlowTemperatureSensor",
        556:"InterruptionMixerEightFlowTemperatureSensor",
        557:"ShortCircuitMixerEightFlowTemperatureSensor",
        558:"InterruptionMixerNineFlowTemperatureSensor",
        559:"ShortCircuitMixerNineFlowTemperatureSensor",
        560:"InterruptionMixerTenFlowTemperatureSensor",
        561:"ShortCircuitMixerTenFlowTemperatureSensor",
        562:"InterruptionMixerElevenFlowTemperatureSensor",
        563:"ShortCircuitMixerElevenFlowTemperatureSensor",
        564:"InterruptionMixerTwelveFlowTemperatureSensor",
        565:"ShortCircuitMixerTwelveFlowTemperatureSensor",
        566:"InterruptionMixerThirteenFlowTemperatureSensor",
        567:"ShortCircuitMixerThirteenFlowTemperatureSensor",
        568:"InterruptionMixerFourteenFlowTemperatureSensor",
        569:"ShortCircuitMixerFourteenFlowTemperatureSensor",
        570:"InterruptionMixerFifteenFlowTemperatureSensor",
        571:"ShortCircuitMixerFifteenFlowTemperatureSensor",
        572:"InterruptionMixerSixteenFlowTemperatureSensor",
        573:"ShortCircuitMixerSixteenFlowTemperatureSensor",
        574:"MixerOneRoomTemperatureSensorNotAvailable",
        575:"InterruptionMixerOneRoomTemperatureSensor",
        576:"ShortCircuitMixerOneRoomTemperatureSensor",
        577:"MixerTwoRoomTemperatureSensorNotAvailable",
        578:"InterruptionMixerTwoRoomTemperatureSensor",
        579:"ShortCircuitMixerTwoRoomTemperatureSensor",
        580:"MixerThreeRoomTemperatureSensorNotAvailable",
        581:"InterruptionMixerThreeRoomTemperatureSensor",
        582:"ShortCircuitMixerThreeRoomTemperatureSensor",
        583:"MixerFourRoomTemperatureSensorNotAvailable",
        584:"InterruptionMixerFourRoomTemperatureSensor",
        585:"ShortCircuitMixerFourRoomTemperatureSensor",
        586:"MixerFiveRoomTemperatureSensorNotAvailable",
        587:"InterruptionMixerFiveRoomTemperatureSensor",
        588:"ShortCircuitMixerFiveRoomTemperatureSensor",
        589:"MixerSixRoomTemperatureSensorNotAvailable",
        590:"InterruptionMixerSixRoomTemperatureSensor",
        591:"ShortCircuitMixerSixRoomTemperatureSensor",
        592:"MixerSevenRoomTemperatureSensorNotAvailable",
        593:"InterruptionMixerSevenRoomTemperatureSensor",
        594:"ShortCircuitMixerSevenRoomTemperatureSensor",
        595:"MixerEightRoomTemperatureSensorNotAvailable",
        596:"InterruptionMixerEightRoomTemperatureSensor",
        597:"ShortCircuitMixerEightRoomTemperatureSensor",
        598:"MixerNineRoomTemperatureSensorNotAvailable",
        599:"InterruptionMixerNineRoomTemperatureSensor",
        600:"ShortCircuitMixerNineRoomTemperatureSensor",
        601:"MixerTenRoomTemperatureSensorNotAvailable",
        602:"InterruptionMixerTenRoomTemperatureSensor",
        603:"ShortCircuitMixerTenRoomTemperatureSensor",
        604:"MixerElevenRoomTemperatureSensorNotAvailable",
        605:"InterruptionMixerElevenRoomTemperatureSensor",
        606:"ShortCircuitMixerElevenRoomTemperatureSensor",
        607:"MixerTwelveRoomTemperatureSensorNotAvailable",
        608:"InterruptionMixerTwelveRoomTemperatureSensor",
        609:"ShortCircuitMixerTwelveRoomTemperatureSensor",
        610:"MixerThirteenRoomTemperatureSensorNotAvailable",
        611:"InterruptionMixerThirteenRoomTemperatureSensor",
        612:"ShortCircuitMixerThirteenRoomTemperatureSensor",
        613:"MixerFourteenRoomTemperatureSensorNotAvailable",
        614:"InterruptionMixerFourteenRoomTemperatureSensor",
        615:"ShortCircuitMixerFourteenRoomTemperatureSensor",
        616:"SoftwareVersionCheckFailed",
        617:"MixerFifteenRoomTemperatureSensorNotAvailable",
        618:"InterruptionMixerFifteenRoomTemperatureSensor",
        619:"ShortCircuitMixerFifteenRoomTemperatureSensor",
        620:"MixerSixteenRoomTemperatureSensorNotAvailable",
        621:"InterruptionMixerSixteenRoomTemperatureSensor",
        622:"ShortCircuitMixerSixteenRoomTemperatureSensor",
        623:"InterruptionMixerOneReturnTemperatureSensor",
        624:"ShortCircuitMixerOneReturnTemperatureSensor",
        625:"InterruptionMixerTwoReturnTemperatureSensor",
        626:"ShortCircuitMixerTwoReturnTemperatureSensor",
        627:"InterruptionMixerThreeReturnTemperatureSensor",
        628:"ShortCircuitMixerThreeReturnTemperatureSensor",
        629:"InterruptionMixerFourReturnTemperatureSensor",
        630:"ShortCircuitMixerFourReturnTemperatureSensor",
        631:"InterruptionMixerFiveReturnTemperatureSensor",
        632:"ShortCircuitMixerFiveReturnTemperatureSensor",
        633:"InterruptionMixerSixReturnTemperatureSensor",
        634:"ShortCircuitMixerSixReturnTemperatureSensor",
        635:"InterruptionMixerSevenReturnTemperatureSensor",
        636:"ShortCircuitMixerSevenReturnTemperatureSensor",
        637:"InterruptionMixerEightReturnTemperatureSensor",
        638:"ShortCircuitMixerEightReturnTemperatureSensor",
        639:"InterruptionMixerNineReturnTemperatureSensor",
        640:"ShortCircuitMixerNineReturnTemperatureSensor",
        641:"InterruptionMixerTenReturnTemperatureSensor",
        642:"ShortCircuitMixerTenReturnTemperatureSensor",
        643:"InterruptionMixerElevenReturnTemperatureSensor",
        644:"ShortCircuitMixerElevenReturnTemperatureSensor",
        645:"InterruptionMixerTwelveReturnTemperatureSensor",
        646:"ShortCircuitMixerTwelveReturnTemperatureSensor",
        647:"InterruptionMixerThirteenReturnTemperatureSensor",
        648:"ShortCircuitMixerThirteenReturnTemperatureSensor",
        649:"InterruptionMixerFourteenReturnTemperatureSensor",
        650:"ShortCircuitMixerFourteenReturnTemperatureSensor",
        651:"InterruptionMixerFifteenReturnTemperatureSensor",
        652:"ShortCircuitMixerFifteenReturnTemperatureSensor",
        653:"InterruptionMixerSixteenReturnTemperatureSensor",
        654:"ShortCircuitMixerSixteenReturnTemperatureSensor",
        655:"InterruptionIncreasedReturnTemperatureSensor",
        656:"ShortCircuitIncreasedReturnTemperatureSensor",
        657:"PreChargePeriodExceedsMaximumTime",
        658:"CurrentMeassuringCircuitFailure",
        659:"MainPowerPathVoltageFeedback",
        660:"PreChargeCircuitVoltageFeedback",
        661:"SignalCompareCurrentDeviation",
        662:"ChargingOvercurrentFailureFirstProtection",
        663:"ChargingOvercurrentFailureSecondProtection",
        664:"DischargingOvercurrentFailureFirstProtection",
        665:"DischargingOvercurrentFailureSecondProtection",
        666:"InterruptionDifferentialTemperatureControllerHeatSourceTemperatureSensor",
        667:"ShortCircuitDifferentialTemperatureControllerHeatSourceTemperatureSensor",
        668:"InterruptionDifferentialTemperatureControllerHeatSinkTemperatureSensor",
        669:"ShortCircuitDifferentialTemperatureControllerHeatSinkTemperatureSensor",
        670:"InterruptionHeatingSupportBufferTemperatureSensor",
        671:"ShortCircuitHeatingSupportBufferTemperatureSensor",
        672:"InterruptionPreheatingReferenceTemperatureSensor",
        673:"ShortCircuitPreheatingReferenceTemperatureSensor",
        674:"UnderTemperatureFailureFirstProtection",
        675:"OverTemperatureFailureFirstProtection",
        676:"UnderTemperatureFailureSecondProtection",
        677:"OverTemperatureFailureSecondProtection",
        678:"UnderVoltageFailureFirstProtection",
        679:"OverVoltageFailureFirstProtection",
        680:"UnderVoltageFailureSecondProtection",
        681:"OverVoltageFailureSecondProtection",
        682:"AirMassFlowSensorNotAvailable",
        683:"AirMassFlowSensorDefective",
        684:"AirBackflowFlapDefective",
        685:"FailureCommunicationHPMU",
        686:"FailureCommunicationRefrigerantController",
        687:"FailureCommunicationEHCU",
        688:"FailureCommunicationMZIOModule",
        689:"ElectricalEnergyStorageCellVoltageStatusError",
        690:"ElectricalEnergyStorageCellTemperatureStatusError",
        691:"CombustionAirInterlockMissingFeedback",
        692:"CombustionAirInterlockClosedDuringActivation",
        693:"InterruptionFlueGasSafetyTemperatureLimiter",
        694:"DeviationFlueGasSafetyTemperatureLimiter",
        695:"PyrofuseDetonated",
        696:"ShortCircuitFlueGasSafetyTemperatureLimiter",
        697:"MainRelayLifeCycleExpired",
        698:"ElectricalEnergyStorageStateInconsistency",
        699:"ElectricalEnergyStoragePrechargeTimeout",
        700:"ElectricalEnergyStorageOvervoltage",
        701:"ElectricalEnergyStorageUndervoltage",
        702:"ElectricalEnergyStorageOvercurrentCharge",
        703:"ElectricalEnergyStorageOvercurrentDischarge",
        704:"ElectricalEnergyStorageOvertemperature",
        705:"ElectricalEnergyStorageUndertemperature",
        706:"GridVoltageTooLowForReconnect",
        707:"GridVoltageTooHighForReconnect",
        708:"GridVoltageAverageTooLow",
        709:"GridVoltageAverageTooHigh",
        710:"GridFrequencyTooLowForReconnect",
        711:"GridFrequencyTooHighForReconnect",
        712:"ResidualCurrentTooHigh",
        713:"ElectricalIsolationFailure",
        714:"CSCConfigurationChanged",
        715:"GridRelaisDefect",
        716:"Phasereversed",
        717:"GridVoltagePhaseOneTooLow",
        718:"GridVoltagePhaseTwoTooLow",
        719:"FailureCommunicationEnergyManager",
        720:"FailureCommunicationDemandResponseModeControl",
        721:"TestExternalWatchdogFailed",
        722:"EmergencyCircuitShortCircuit",
        723:"CSCCountNotPlausible",
        724:"CSCTypeNotPlausible",
        725:"AmbientTemperatureSensorInterruption",
        726:"AmbientTemperatureSensorShortCircuit",
        727:"CSCBatteryVoltageNotPlausible",
        728:"ElectronicalThermostateValveTemperatureSensor",
        729:"ElectronicControlUnitHardwareFailure",
        730:"ElectronicalThermostateValveMotorError",
        731:"ElectronicalThermostateValveClosingError",
        732:"ElectronicalThermostateCriticalLowBattery",
        733:"FloorHeatingThermostateInletTemperatureSensor",
        734:"FloorHeatingThermostateSecondaryTemperatureSensor",
        735:"FloorHeatingThermostateExternalEnvironmentSensor",
        736:"ClimateSensorTemperatureSensor",
        737:"EnergyStorageTemperatureDrift",
        738:"OpenThermDeviceBlockedBySystemConfiguration",
        739:"LostCommunicationCanOpenBox",
        740:"MainRelayControlCircuitFeedbackSignalError",
        741:"PyroFuseControlCircuitFeedbackSignalError",
        742:"WatchdogControlCircuitFeedbackSignalError",
        743:"RefrigerationCircuitAvailabilityNotInitialized",
        744:"UnsupportedConfiguration",
        745:"NoMatchingApplication",
        746:"ApplicationFlashingFailed",
        747:"InternalHumanMachineInterfaceError",
        748:"DisplayDriverTouchFoilIssue",
        749:"FirmwareCompatibilityIssue",
        750:"ShortCircuitControllerBoardTemperatureSensor",
        751:"InterruptionControllerBoardTemperatureSensor",
        752:"GridFrequencyTooLow",
        753:"GridFrequencyTooHigh",
        754:"GridVoltageTooLow",
        755:"PowerUnitBatteryVoltageError",
        756:"InverterInputBWrongPolarity",
        757:"InverterInputCWrongPolarity",
        758:"DualHtsVersionIncompatible",
        759:"DualHtsNoBranding",
        760:"DualHtsOemVariantMismatch",
        761:"InverterInputAWrongPolarity",
        762:"LowWaterCutOff",
        763:"GasPressureHigh",
        764:"LagDeviceDtcReported",
        765:"LostCommunicationLagDevice",
        766:"FlueGasTemperatureDeratingWarningThresholdReached",
        767:"FlueGasTemperatureDeratingErrorThresholdReached",
        768:"ShortCircuitCondensateDetectionSensor",
        769:"InterruptionCondensateDetectionSensor",
        770:"InterruptionSecondaryOutletTemperatureSensor",
        771:"ShortCircuitSecondaryOutletTemperatureSensor",
        772:"InterruptionCompressorOilTemperatureSensor",
        773:"ShortCircuitCompressorOilTemperatureSensor",
        774:"InterruptionEnhancedVapourInjectionTemperatureSensor",
        775:"ShortCircuitEnhancedVapourInjectionTemperatureSensor",
        776:"InterruptionReceiverTemperatureSensor",
        777:"ShortCircuitReceiverTemperatureSensor",
        778:"InterruptionCompressorMotorChamberTemperatureSensor",
        779:"ShortCircuitCompressorMotorChamberTemperatureSensor",
        780:"RelayTestNotExecuted",
        781:"RelayTestError",
        782:"FanIntermediateCircuitVoltageLow",
        783:"GeneralFanError",
        784:"AdditionalElectricHeaterFailure",
        785:"ExternalLockTriggeredFanShutdownButNotConfigured",
        786:"FailedDeviceAssignmentToSrcRoom",
        787:"PowerUnitIslandOverload",
        788:"InterruptionFourThreeWayValve",
        789:"ShortCircuitFourThreeWayValve",
        790:"MechanicalFailureFourThreeWayValve",
        791:"FailureElectricalHeaterPhaseOne",
        792:"FailureElectricalHeaterPhaseTwo",
        793:"FailureElectricalHeaterPhaseThree",
        794:"InterruptionElectricalHeater",
        795:"ShortCircuitDomesticHotWaterCirculationPump",
        796:"InterruptionDomesticHotWaterCirculationPump",
        797:"MechanicalFailureCentralHeatingPump",
        798:"MechanicalFailureMixerTwoCircuitPump",
        799:"ElectricalFailureCentralHeatingPump",
        800:"ElectricalFailureMixerTwoCircuitPump",
        801:"FailureRefrigerationCircuitFourWayValve",
        802:"InterruptionRefrigerationCircuitFourWayValve",
        803:"ShortCircuitPrimaryHeatExchangerBaseHeater",
        804:"InterruptionPrimaryHeatExchangerBaseHeater",
        805:"ShortCircuitPrimaryCircuitFanOne",
        806:"InterruptionPrimaryCircuitFanOne",
        807:"InterruptionTachoSignalPrimaryCircuitFanOne",
        808:"FailurePrimaryCircuitFanOne",
        809:"ShortCircuitPrimaryCircuitFanTwo",
        810:"InterruptionPrimaryCircuitFanTwo",
        811:"InterruptionTachoSignalPrimaryCircuitFanTwo",
        812:"FailurePrimaryCircuitFanTwo",
        813:"ShortCircuitCrankCaseHeater",
        814:"InterruptionCrankCaseHeater",
        815:"ShortCircuitHumidityProtectionSensorMixerOne",
        816:"OpenLoadDetectionHumidityProtectionSensorMixerOne",
        817:"ShortCircuitHumidityProtectionSensorMixerTwo",
        818:"OpenLoadDetectionHumidityProtectionSensorMixerTwo",
        819:"InterruptionExpansionValveOne",
        820:"InterruptionExpansionValveTwo",
        821:"ShortCircuitMixerTwoCircuitPump",
        822:"InterruptionMixerTwoCircuitPump",
        823:"ShortCircuitElectronicExpansionValveOne",
        824:"ShortCircuitElectronicExpansionValveTwo",
        825:"ShortCircuitCentralHeatingPump",
        826:"InterruptionCentralHeatingPump",
        827:"OverHeatingTemperatureSafetySwitchActivated",
        828:"HydraulicFilterMissing",
        829:"StrongContaminationHydraulicFilter",
        830:"InverterCompressorCurrentSensorFault",
        831:"InverterPowerFactorCorrectionCurrentSensorFault",
        832:"InverterBridgeTemperatureSensorFault",
        833:"InverterPowerFactorCorrectionTemperatureSensorFault",
        834:"InverterAcGridPhaseLostFault",
        835:"InverterCompressorCodeMismatch",
        836:"InverterBridgeOverCurrent",
        837:"InverterCompressorLostOfPhase",
        838:"InverterControlFault",
        839:"InverterLockedRotorFault",
        840:"InverterGroundFault",
        841:"InverterCompressorOverLoad",
        842:"InverterBridgeShortCircuit",
        843:"InverterHardwarePowerFactorCorrectionOverCurrent",
        844:"InverterReferenceVoltageFault",
        845:"InverterWrongRegisterAddress",
        846:"InverterCompressorSpeedReverseError",
        847:"InverterCurrentNotChange",
        848:"InverterCurrentChangeToFast",
        849:"InverterSafetyTorqueOffOneFault",
        850:"InverterSafetyTorqueOffTwoFault",
        851:"InverterSafetyTorqueOffThreeFault",
        852:"InverterSafetyTorqueOffOneSensorFault",
        853:"InverterSafetyTorqueOffTwoSensorFault",
        854:"InverterSafetyTorqueOffThreeSensorFault",
        855:"InverterOverVoltageProtectionFault",
        856:"InverterHardwareDcLinkOverCurrent",
        857:"InverterSoftwareDcLinkOverCurrent",
        858:"InverterDcLinkCurrentSensorFault",
        859:"InverterSpeedFault",
        860:"InverterUnderTemperature",
        861:"InverterMicroElectronicsFault",
        862:"InverterInternalFault",
        863:"StartAbortedIgnitionSparkError",
        864:"DefrostingUnsuccessful",
        865:"HighPressureShutOffRefrigerantCircuit",
        866:"LowPressureShutOffRefrigerantCircuit",
        867:"ActivatedSafetyValveHydraulicCircuit",
        868:"FailureCommunicationPreheaterModule",
        869:"FailureCommunicationPostheaterModule",
        870:"PreheaterTwentyFourVoltPowerSupplyFailure",
        871:"PostheaterTwentyFourVoltPowerSupplyFailure",
        872:"InternalTwentyFourVoltPowerSupplyMonitoringFailure",
        873:"InterruptionCommonFlowTemperatureSensor",
        874:"ShortCircuitCommonFlowTemperatureSensor",
        875:"FailureCommunicationToLeadDevice",
        876:"InterruptionCombinedVolumeFlowAndTemperatureSensor",
        877:"ShortCircuitOutdoorMiddleCoilTemperatureSensor",
        878:"InterruptionOutdoorMiddleCoilTemperatureSensor",
        879:"ShortCircuitSecondaryHeatExchangerVaporPressureSensor",
        880:"InterruptionSecondaryHeatExchangerVaporPressureSensor",
        881:"InverterSafetyOperationalShutDown",
        882:"GasOutputPressureTooHigh",
        883:"GasValveCheckGasValveElectronics",
        884:"GasValveCheckNoGasValvePressureIncrease",
        885:"GasValveCheckVTwoTestNotPassed",
        886:"GasValveCheckNoGasValvePressureDecrease",
        887:"GasValveCheckVOneTestNotPassed",
        888:"OxygenProbeControllerCommunication",
        889:"OxygenProbeMonitoringVsTest",
        890:"OxygenProbeMonitoringVsOutOfRange",
        891:"OxygenProbeCalibrationNotReady",
        892:"OxygenProbeCalibrationDifference",
        893:"OxygenProbeCalibrationOutOfRange",
        894:"OxygenProbeMonitoringMeasuringCellShunt",
        895:"OxygenProbeMonitoringMeasuringCellInternalResistance",
        896:"SafetyChainInputOneLockout",
        897:"SafetyChainInputTwoLockout",
        898:"OutdoorAirTemperatureSensorNotAvailable",
        899:"OutdoorAirHumiditySensorNotAvailable",
        900:"ExtractAirTemperatureSensorNotAvailable",
        901:"ExtractAirHumiditySensorNotAvailable",
        902:"SupplyAirTemperatureSensorNotAvailable",
        903:"SupplyAirHumiditySensorNotAvailable",
        904:"ExhaustAirTemperatureSensorNotAvailable",
        905:"ExhaustAirHumiditySensorNotAvailable",
        906:"PowerMismatchOutdoorToIndoorUnit",
        907:"ShortCircuitFanHeater",
        908:"InterruptionFanHeater",
        909:"ElectricalEnergyMatrixInvalidValue",
        910:"MultipleLeadDeviceCollisionDetection",
        911:"InconsistentVentilationVolumeFlowConfiguration",
        912:"InverterAmbientTemperatureSensorFault",
        913:"InverterAmbientTemperatureProtectionActive",
        914:"InverterHeatSinkOverTemperatureProtection",
        915:"ShortCircuitInverterHeatSinkOverTemperature",
        916:"InterruptionCircuitInverterHeatSinkOverTemperature",
        917:"SignalCompareInternalPowerSupply",
        918:"SignalCompareInternalEmergencyPowerSupply",
        919:"SignalCompareInternalPyrofuseCapacitorVoltage",
        920:"ExternalSafetyEquipmentOneFailure",
        921:"ExternalSafetyEquipmentTwoFailure",
        922:"ExternalSafetyEquipmentThreeFailure",
        923:"ElectricalEnergyMatrixMeterOneDisconnection",
        924:"ElectricalEnergyMatrixMeterTwoDisconnection",
        925:"ElectricalEnergyMatrixMeterThreeDisconnection",
        926:"ElectricalEnergyMatrixMeterFourDisconnection",
        927:"ElectricalEnergyMatrixMeterFiveDisconnection",
        928:"ElectricalEnergyMatrixMeterSixDisconnection",
        929:"ElectricalEnergyMatrixMeterSevenDisconnection",
        930:"ElectricalEnergyMatrixMeterEightDisconnection",
        931:"ElectricalEnergyMatrixMeterNineDisconnection",
        932:"ElectricalEnergyMatrixMeterTenDisconnection",
        933:"ElectricalEnergyMatrixMeterElevenDisconnection",
        934:"ElectricalEnergyMatrixMeterTwelveDisconnection",
        935:"ElectricalEnergyMatrixMeterThirteenDisconnection",
        936:"ElectricalEnergyMatrixMeterFourteenDisconnection",
        937:"ElectricalEnergyMatrixMeterFifteenDisconnection",
        938:"ElectricalEnergyMatrixInverterOneDisconnection",
        939:"ElectricalEnergyMatrixInverterTwoDisconnection",
        940:"ElectricalEnergyMatrixInverterThreeDisconnection",
        941:"ElectricalEnergyMatrixInverterFourDisconnection",
        942:"ElectricalEnergyMatrixInverterFiveDisconnection",
        943:"ElectricalEnergyMatrixInverterSixDisconnection",
        944:"ElectricalEnergyMatrixConsumerOneDisconnection",
        945:"ElectricalEnergyMatrixConsumerTwoDisconnection",
        946:"ElectricalEnergyMatrixConsumerThreeDisconnection",
        947:"ElectricalEnergyMatrixConsumerFourDisconnection",
        948:"ElectricalEnergyMatrixConsumerFiveDisconnection",
        949:"ElectricalEnergyMatrixConsumerSixDisconnection",
        950:"ElectricalEnergyMatrixConsumerSevenDisconnection",
        951:"ElectricalEnergyMatrixConsumerEightDisconnection",
        952:"ElectricalEnergyMatrixConsumerNineDisconnection",
        953:"ElectricalEnergyMatrixConsumerTenDisconnection",
        954:"ElectricalEnergyMatrixConsumerElevenDisconnection",
        955:"ElectricalEnergyMatrixConsumerTwelveDisconnection",
        956:"ElectricalEnergyMatrixConsumerThirteenDisconnection",
        957:"ElectricalEnergyMatrixConsumerFourteenDisconnection",
        958:"ElectricalEnergyMatrixConsumerFifteenDisconnection",
        959:"ElectricalEnergyMatrixProducerOneDisconnection",
        960:"ElectricalEnergyMatrixProducerTwoDisconnection",
        961:"ElectricalEnergyMatrixProducerThreeDisconnection",
        962:"ElectricalEnergyMatrixProducerFourDisconnection",
        963:"ElectricalEnergyMatrixProducerFiveDisconnection",
        964:"ElectricalEnergyMatrixProducerSixDisconnection",
        965:"ElectricalEnergyMatrixStorageOneDisconnection",
        966:"ElectricalEnergyMatrixStorageTwoDisconnection",
        967:"ElectricalEnergyMatrixStorageThreeDisconnection",
        968:"ElectricalEnergyMatrixStorageFourDisconnection",
        969:"ElectricalEnergyMatrixStorageFiveDisconnection",
        970:"ElectricalEnergyMatrixStorageSixDisconnection",
        971:"GasVolumeFactoryOffsetNotSet",
        972:"FanSpeedTooHigh",
        973:"PreHeaterNoHeatOperation",
        974:"BypassMotorNotMoving",
        975:"FuelCellPowerConditioningSystemInputVoltageDropFour",
        976:"FuelCellInverterPBoardFailure",
        977:"FuelCellHydrogenFlowMeterFailure",
        978:"SensorDataInsufficientForAutomaticMode",
        979:"ThermostatInputDoubleConfiguration",
        980:"DomesticHotWaterLoadingTerminatedInsufficientVolumeFlow",
        981:"DomesticHotWaterLoadingTerminatedVolumeFlowDroppedBelowThreshold",
        982:"DryRunCentralHeatingPump",
        983:"InverterFailurePersistentMemory",
        984:"ElectricalFailureElectronicExpansionValveOneMotor",
        985:"ElectricalFailureElectronicExpansionValveTwoMotor",
        986:"BurnerControlUnitParameterMismatch",
        987:"SignalEvaluationExhaustFlapFeedback",
        988:"SignalEvaluationGasPressureSwitch",
        989:"SignalEvaluationIgnitionRelay",
        990:"ShortCircuitHydraulicSeperatorTemperatureSensor",
        991:"InterruptionHydraulicSeperatorTemperatureSensor",
        992:"ShortCircuitHeatingCoolingBufferTemperatureSensor",
        993:"InterruptionHeatingCoolingBufferTemperatureSensor",
        994:"ShortCircuitHeatingBufferTemperatureSensor",
        995:"InterruptionHeatingBufferTemperatureSensor",
        996:"ShortCircuitCoolingBufferTemperatureSensor",
        997:"InterruptionCoolingBufferTemperatureSensor",
        998:"CombinedVolumeFlowAndTemperatureSensorTimeOut",
        999:"FailureCommunicationHIO",
        1000:"ShowtimeBaby",
        1001:"OxygenProbeNotCalibrated",
        1002:"OxygenProbeCurrentValueCompensationOffsetParameter",
        1003:"OxygenProbeCurrentValueCompensationOffsetBoundary",
        1004:"OxygenContentLow",
        1005:"FiniteStateMachineIgnitionRelayFailure",
        1006:"StartupFailureCounterRefrigerantCircuitExceeded",
        1007:"RefrigerantCircuitLocked",
        1008:"NumberOfSupportedLagDevicesExceeded",
        1009:"FailureCrankCaseHeater",
        1010:"FailureHydraulicWaterPressureSensor",
        1011:"FailureCompressorOutletPressureSensor",
        1012:"FailureCompressorInletPressureSensor",
        1013:"FailureConfigurationOutdoorUnitMissing",
        1014:"FailureUndefinedOutdoorModel",
        1015:"FailureMismatchHardwareTypeOutdoorUnit",
        1016:"ReturnTemperatureSensorNotAvailable",
        1017:"SecondaryOutletTemperatureSensorNotAvailable",
        1018:"SecondaryHeatExchangerVaporPressureSensorNotAvailable",
        1019:"SecondaryHeatExchangerLiquidTemperatureSensorNotAvailable",
        1020:"InverterOverTemperature",
        1021:"GridSupportConfiguration",
        1022:"EnergyMeter",
        1023:"GridVoltagePhaseThreeTooLow",
        1024:"GridVoltagePhaseOneTooHigh",
        1025:"GridVoltagePhaseTwoTooHigh",
        1026:"GridVoltagePhaseThreeTooHigh",
        1027:"InverterSelfTestFailed",
        1028:"PhotovoltaicsInput",
        1029:"BatteryInput",
        1030:"BalancingFailed",
        1031:"CollectiveGridError",
        1032:"FailureCommunicationEEBUS",
        1033:"ConfigurationDC",
        1034:"CanExternalCommunicationException",
        1035:"CanInternalCommunicationException",
        1036:"CanBatteryCommunicationException",
        1037:"CSCCountNoneInstalled",
        1038:"CSCCountMoreInstalled",
        1039:"CSCCountLessInstalled",
        1040:"FailureReversedFlowDirectionEnergyMeter",
        1041:"WrongInverterVariantInstalled",
        1042:"InverterLinkVoltageDivergence",
        1043:"EnergyMeterFunctionConfigurationMismatch",
        1044:"EnergyMonitoringMeterDisconnection",
        1045:"FailureExternalThermalDeviceOne",
        1046:"FailureExternalThermalDeviceTwo",
        1047:"FailureExternalThermalDeviceThree",
        1048:"FailureExternalThermalDeviceFour",
        1049:"FailureBivalenceMixer",
        1050:"ShortCircuitTemperatureSensorExternalThermalDeviceOne",
        1051:"InterruptionTemperatureSensorExternalThermalDeviceOne",
        1052:"ShortCircuitTemperatureSensorExternalThermalDeviceTwo",
        1053:"InterruptionTemperatureSensorExternalThermalDeviceTwo",
        1054:"TemperatureSensorExternalThermalDeviceOneTemperatureThreasholdExeeded",
        1055:"TemperatureSensorExternalThermalDeviceTwoTemperatureThreasholdExeeded",
        1056:"InverterFailurePreChargeRelay",
        1057:"FailureSecondaryHeatExchangerVaporPressureSensor",
        1058:"SignalEvaluationAirFilter",
        1059:"LateIgnitionPossibleFlameDeflagrationDetected",
        1060:"OxygenProbeControllerSupervisionCellVoltageDrift",
        1061:"OxygenProbeControllerSupervisionProbeCurrentDrift",
        1062:"InverterDcLinkUnderVoltageFailure",
        1063:"InverterDcLinkOverVoltageFailure",
        1064:"InverterDcOverCurrentFailure",
        1065:"InverterAcGridUnderVoltageFailure",
        1066:"InverterAcGridOverVoltageFailure",
        1067:"InverterAcInputZeroCrossingFailure",
        1068:"OverheatingIndoorHeatExchangerHeatingFailure",
        1069:"OverheatingOutdoorHeatExchangerHeatingFailure",
        1070:"FuelCellModuleCondensateBlockageDetection",
        1071:"CoContentFuelCellExhaustGasOutOfToleranceRange",
        1072:"FailureWaterShutoffValve",
        1073:"FailureWaterFloorLeakDetector",
        1074:"PressureImbalanceRefrigerantCycle",
        1075:"SupplyAirTemperatureBelowCriticalThreshold",
        1076:"CompressorStartCounterCriticalOilTemperatureExceeded",
        1077:"FailureMinimumCompressorOnTimeViolation",
        1078:"FailureFrequentInsufficientWaterFlowAtCompressorStart",
        1079:"DefrostUnsuccessfullDueToLowWaterFlow",
        1080:"FailureLowEvaportingTemperatureCooling",
        1081:"FailureLowSecondaryOutletTemperatureCooling",
        1082:"FailureTooLowCondensingTemperatureDefrost",
        1083:"FailureTooHighEvaporatingTemperatureCooling",
        1084:"CompressorBlocked",
        1085:"MechanicalFailureDomesticHotWaterTankLoadPump",
        1086:"ElectricalFailureDomesticHotWaterTankLoadPump",
        1087:"DryRunDomesticHotWaterTankLoadPump",
        1088:"ShortCircuitDhwReturnTemperaturTankLoadSystem",
        1089:"InterruptionDhwReturnTemperaturTankLoadSystem",
        1090:"ShortCirucitDhwFlowTemperaturTankLoadSystem",
        1091:"InterruptionDhwFlowTemperaturTankLoadSystem",
        1092:"FailureInvalidOduTypeConfiguration",
        1093:"FailureCommunicationTankLoadController",
        1094:"NoWaterFlowDHWTankLoadSystem",
        1095:"ViewedErrorList",
        1096:"ErrorHasBeenConfirmed"
    },

    "Warnings" : {
        0: "NoWarningAvailable",
        1: "FrostprotectionLevelOne",
        2: "FrostprotectionLevelTwo",
        3: "LossOfWaterDetection",
        4: "SolarCollectorTemperatureInvalidAtNight",
        5: "FortyFiveDaysToRegularMaintenance",
        6: "ThirtyDaysToRegularMaintenance",
        7: "OverhaulRequired",
        8: "DurationOfLife",
        9: "ChangeVentilationFilter",
        10: "LowGasPressure",
        11: "WaterPressureLevelCriticallyLow",
        12: "RealTimeClockBatteryLow",
        13: "RealTimeClockResetRequired",
        14: "FuelCellRestartSuppressed",
        15: "FiniteStateMachineErrorMode",
        16: "WaterFlowInsufficient",
        17: "LegionellaProtectionTemperatureNotReached",
        18: "HeatCellCondensatDetectionPossible",
        19: "OverHeatingProtectionTemperatureLimiter",
        20: "ServiceIntervalFailed",
        21: "WaterPressureLevelCriticallyHigh",
        22: "ExternalPowerGridSeparation",
        23: "InverterFanFailure",
        24: "ValveMountingModeActive",
        25: "InvalidCommunication",
        26: "InvalidInternalClock",
        27: "LowBattery",
        28: "FloorHeatingThermostateOutputShortCircuit",
        29: "FloorHeatingThermostatInternalFuse",
        30: "FloorHeatingThermostateInletTemperatureMissing",
        31: "FloorHeatingThermostateInletTemperatureShutDown",
        32: "FloorHeatingThermostateCondensationShutDown",
        33: "CscConfigurationChanged",
        34: "NoEnergyFeed",
        35: "InverterSwitchOpen",
        36: "IslandModeFault",
        37: "LostCommunicationBmcuEmcu",
        38: "LostCommunicationEmcuInverter",
        39: "StateInconsistencyBmcuEmcuFunctionalSoftware",
        40: "AmbientTemperatureSensorOvertemperature",
        41: "AmbientTemperatureSensorUndertemperature",
        42: "ControllerBoardTemperatureTooHigh",
        43: "PowerUnitDirectCurrentInputConfigurationIncomplete",
        45: "InverterInputACurrentTooHigh",
        46: "DualHtsDirectCurrentInputConfigurationIncomplete",
        47: "UnassignedInverterTroubleCode",
        48: "HeatCellCondensateJamReductionLimitReached",
        49: "OutOfOptimalWorkingPointCentralHeating",
        50: "OutOfOptimalWorkingPointDomesticHotWater",
        51: "OutOfOptimalWorkingPointCentralCooling",
        52: "FanIntermediateCircuitVoltageHigh",
        53: "FanSensorCableBreak",
        54: "CurrentTargetFanSpeedToLow",
        55: "FanIntermediateCircuitVoltageLow",
        56: "FanElectronicsTemperatureHigh",
        57: "FanMotorTemperatureHigh",
        58: "ValueRangeViolation",
        59: "ExternalAirPressureMonitoringTriggeredFanShutdown",
        60: "ExternalFireProtectionFlapTriggeredFanShutdown",
        61: "ElectricalHeaterReducedOutputPower",
        62: "OpenLoadFeedbackSignalCentralHeatingPump",
        63: "OpenLoadFeedbackSignalMixerTwoCircuitPump",
        64: "DryRunCentralHeatingPump",
        65: "DryRunMixerTwoCircuitPump",
        66: "DecodingErrorFeedbackSignalCentralHeatingPump",
        67: "PumpHeadMismatchCentralHeatingPump",
        68: "DecodingErrorFeedbackSignalMixerTwoCircuitPump",
        69: "PumpHeadMismatchMixerTwoCircuitPump",
        70: "ContaminationHydraulicFilter",
        71: "InverterCompressorOverCurrent",
        72: "InverterSoftwarePowerFactorCorrectionOverVoltage",
        73: "InverterFrequencySpeedMismatch",
        74: "WaterPressureDropDetected",
        75: "HydraulicSystemPressurePeaksDetected",
        76: "FrostprotectionSolarCircuit",
        77: "IgnitionElectrodeAging",
        78: "BypassFlapMonitoringTriggered",
        79: "InvalidTemperatureSensorDriftDetected",
        80: "FanBlockadeDueToIcing",
        81: "ConstraintHeatExchangerOperation",
        82: "VoltageReferenceCalibrationFailure",
        83: "DomesticHotWaterSensorNotPlausible",
        84: "ReturnTemperatureSensorNotPlausible",
        85: "SecondaryOutletTemperatureSensorNotPlausible",
        86: "FlowTemperatureSensorNotPlausible",
        87: "MixerTwoCircuitFlowTemperatureSensorNotPlausible",
        88: "OverheatingOutdoorHeatExchangerCoolingAlert",
        89: "OverheatingIndoorHeatExchangerHeatingAlert",
        90: "CompressorOverheatingProtectionActive",
        91: "ComfortEnsuringModeActive",
        92: "FrostprotectionDomesticHotWater",
        93: "CompressorOutletPressureNotPlausible",
        94: "CompressorInletPressureNotPlausible",
        95: "VolumeFlowSIgnalNotPlausible",
        96: "VentingHydraulicSystemInsufficient",
        97: "FuelCellPowerOnResetRequestAfterFailureReset",
        98: "Reuse",
        99: "SecondaryOutletTemperatureTooLow",
        100: "RestoreEepromToDefault",
        101: "CompressorOutletTemperatureSensorNotPlausible",
        102: "CompressorInletTemperatureSensorNotPlausible",
        103: "DynamicAirVolumeFlowCorrectionLimitViolation",
        104: "LagDeviceDtcReported",
        105: "RTCLostInverter",
        106: "CondtionsIsolationMonitoring",
        107: "InverterSwitchOpenDuringOperation",
        108: "InverterBatteryValuesMissing",
        109: "TargetTemperatureSetpointNotReached",
        110: "TemperatureSensorExternalThermalDeviceOneTemperatureThreasholdReached",
        111: "TemperatureSensorExternalThermalDeviceTwoTemperatureThreasholdReached",
        112: "InverterDcLinkUnderVoltageAlert",
        113: "InverterDcLinkOverVoltageAlert",
        114: "InverterDcOverCurrentAlert",
        115: "InverterAcGridUnderVoltageAlert",
        116: "InverterAcGridOverVoltageAlert",
        117: "InverterAcInputZeroCrossingAlert",
        118: "InverterAcGridOverCurrentAlert",
        119: "OutdoorUnitOverPowerProtectionAlert",
        120: "OutdoorUnitFaultyCompressorStart",
        121: "InverterHeatSinkOverTemperatureAlert",
        122: "LowEvaporatingTemperatureCoolingAlert",
        123: "LowEvaporatingTemperatureHeatingAlert",
        124: "MinimumSecondaryOutletTemperatureAlert",
        125: "OverheatingOutdoorHeatExchangerHeatingAlert",
        126: "IndoorDefrostRequestDuringNonDeicerProcessAlert",
        127: "SecondaryOutletTemperatureCountermeasureAlert",
        128: "LowPressureCountermeasureAlert",
        129: "HeatSinkOverTemperatureAlert",
        130: "LowOutsideTemperatureCoolingAlert",
        131: "HighOutsideTemperatureCoolingAlert",
        132: "LowOutsideTemperatureHeatingAlert",
        133: "HighOutsideTemperatureHeatingAlert",
        134: "LowSaltAlert",
        135: "FlowMonitorAlert",
        136: "ExcessiveWaterUseAlert",
        137: "CompressorUnexpectedStop",
        138: "CompressorDueToHeadache",
        139: "InverterAmbientTemperatureProtection",
        140: "ParameterFileNotSuitable",
        141: "DesiredCompressorOutletTemperatureHeatingExceeded",
        142: "DesiredCompressorOutletTemperatureCoolingExceeded",
        143: "DefrostingProcessAborted",
        144: "NoChangeOffPeakElectricitySignal",
        145: "BypassValveNotWorking",
        146: "BufferTopTemperatureSensorNotPlausible",
        147: "BufferMidTemperatureSensorNotPlausible",
        148: "BufferBottomTemperatureSensorNotPlausible",
        149: "DecodingErrorFeedbackSignalDhwTankLoadPump",
        150: "OpenLoadFeedbackSignalDhwTankLoadPump",
        151: "PumpHeadMismatchDhwPump",
        152: "ViewedWarningList",
        153: "WarningHasBeenConfirmed"
    },

    "States" : {
        0: "NoStatus",
        1: "PowerOn",
        2: "InitialisationOperationSystem",
        3: "PowerOnSelftest",
        4: "AktorSensorSelftest",
        5: "HvacTopologieScan",
        6: "Standby",
        7: "PrerunCentralHeatingPump",
        8: "DomesticHotWaterPumpIsActive",
        9: "FanInPrerunModeCentralHeating",
        10: "FanInPrerunModeDomesticHotWater",
        11: "FanInPrerunModeDomesticHotWaterTapping",
        12: "PreIgnitionCentralHeating",
        13: "PreIgnitionDomesticHotWater",
        14: "PreIgnitionDomesticHotWaterTapping",
        15: "IgnitionCentralHeating",
        16: "IgnitionDomesticHotWater",
        17: "IgnitionDomesticHotWaterTapping",
        18: "FlameDetectionCentralHeating",
        19: "FlameDetectionDomesticHotWater",
        20: "FlameDetectionDomesticHotWaterTapping",
        21: "FlameStabilisationCentralHeating",
        22: "FlameStabilisationDomesticHotWater",
        23: "FlameStabilisationDomesticHotWaterTapping",
        24: "ModulationBlockingTimeCentralHeating",
        25: "ModulationBlockingTimeDomesticHotWater",
        26: "ModulationBlockingTimeDomesticHotWaterTapping",
        27: "ActiveHeaterGeneratorCentralHeatingReducedMode",
        28: "ActiveHeaterGeneratorCentralHeatingEcoMode",
        29: "ActiveHeaterGeneratorCentralHeatingComfortMode",
        30: "ActiveHeaterGeneratorCentralHeatingPartyMode",
        31: "ActiveHeaterGeneratorDomesticHotWaterReducedMode",
        32: "ActiveHeaterGeneratorDomesticHotWaterEcoMode",
        33: "ActiveHeaterGeneratorDomesticHotWaterComfortMode",
        34: "ActiveHeaterGeneratorDomesticHotWaterPartyMode",
        35: "ActiveHeaterGeneratorDomesticHotWaterTappingEcoMode",
        36: "ActiveHeaterGeneratorDomesticHotWaterTappingComfortMode",
        37: "PassiveNaturalCoolingMode",
        38: "ActiveCoolingMode",
        39: "FanInPostrunMode",
        40: "ProstrunCentralHeatingPump",
        41: "PostrunDomesticHotWaterPump",
        42: "CentralHeatingPumpCirculationMode",
        43: "MinimumPowerTestModeCentralHeating",
        44: "PartloadPowerTestModeCentralHeating",
        45: "MaximumPowerTestModeCentralHeating",
        46: "MinimumPowerTestModeDomesticHotWater",
        47: "PartloadPowerTestModeDomesticHotWater",
        48: "MaximumPowerTestModeDomesticHotWater",
        49: "MinimumPowerTestModeDomesticHotWaterTapping",
        50: "PartloadPowerTestModeDomesticHotWaterTapping",
        51: "MaximumPowerTestModeDomesticHotWaterTapping",
        52: "SafetyTemperatureLimiterTestModeCentralHeating",
        53: "SafetyTemperatureLimiterTestModeDomesticHotWater",
        54: "SafetyExhaustTemperatureLimiterTestMode",
        55: "ChimneySweeperTestModeCentralHeating",
        56: "ChimneySweeperTestModeDomesticHotWater",
        57: "ChimneySweeperTestModeDomesticHotWaterTapping",
        58: "FlueGasSensorDetectionStart",
        59: "FlueGasSensorDetectionActive",
        60: "SummerMode",
        61: "FuelCellRegenerationActive",
        62: "FuelCellStandby",
        63: "FuelCellHeatingActive",
        64: "FuelCellDomesticHotWaterActive",
        65: "IdleStateCheck",
        66: "FanPreRunRotationCheck",
        67: "FanPostRunRotationCheck",
        68: "BurnerInRaisedMode",
        69: "ValveCheck",
        70: "RelaisCheck",
        71: "StartUpSignalCheck",
        72: "FanForcedVentilationRotationCheck",
        73: "FanInForcedVentilationMode",
        74: "SolarHeatingSuppression",
        75: "DomesticHotWaterCirculationPumpIsActive",
        76: "CentralHeatingPumpIsActive",
        77: "AirBackflowFlapCheckActive",
        78: "BatteryPreCharging",
        79: "BatteryIdle",
        80: "BatteryCharging",
        81: "BatteryDischarging",
        82: "BatterySelftest",
        83: "FuelCellStartup",
        84: "FuelCellGeneration",
        85: "FuelCellStop",
        86: "FuelCellMaintenance",
        87: "FuelCellStopWithForcedCooling",
        88: "PrimarySolarPumpIsActive",
        89: "SolarSystemInStagnation",
        90: "MinimumBurnerBlocking",
        91: "CalibrationRequest",
        92: "CalibrationIsActive",
        93: "MountingMode",
        94: "MixerOneCircuitExternalHookupNoDemandFromZones",
        95: "MixerTwoCircuitExternalHookupNoDemandFromZones",
        96: "MixerThreeCircuitExternalHookupNoDemandFromZones",
        97: "MixerFourCircuitExternalHookupNoDemandFromZones",
        98: "MixerFiveCircuitExternalHookupNoDemandFromZones",
        99: "MixerSixCircuitExternalHookupNoDemandFromZones",
        100: "MixerSevenCircuitExternalHookupNoDemandFromZones",
        101: "MixerEightCircuitExternalHookupNoDemandFromZones",
        102: "MixerNineCircuitExternalHookupNoDemandFromZones",
        103: "MixerTenCircuitExternalHookupNoDemandFromZones",
        104: "MixerElevenCircuitExternalHookupNoDemandFromZones",
        105: "MixerTwelveCircuitExternalHookupNoDemandFromZones",
        106: "MixerThirteenCircuitExternalHookupNoDemandFromZones",
        107: "MixerFourteenCircuitExternalHookupNoDemandFromZones",
        108: "MixerFifteenCircuitExternalHookupNoDemandFromZones",
        109: "MixerSixteenCircuitExternalHookupNoDemandFromZones",
        110: "RefrigerationCircuitReadyForOperation",
        111: "AdditionalElectricHeaterIsActive",
        112: "FourThreeWayValveInitializationPhase",
        113: "FourThreeWayValveFromRoomSpaceClimateToDomesticHotWater",
        114: "FourThreeWayValveFromDomesticHotWaterToRoomSpaceClimate",
        115: "FourThreeWayValveDomesticHotWaterPosition",
        116: "FourThreeWayValveRoomSpaceClimateOnePosition",
        117: "FourThreeWayValveRoomSpaceClimateTwoPosition",
        118: "FourThreeWayValveInternalBufferPosition",
        119: "DefrostingModeOutDoorUnitActive",
        120: "NormalOperation",
        121: "SmartGridRecommendedOperation",
        122: "SmartGridForcedOperation",
        123: "HeatPumpOff",
        124: "HeatPumpPreRun",
        125: "HeatPumpHeatingActive",
        126: "HeatPumpCoolingActive",
        127: "HeatPumpPrepDefrost",
        128: "HeatPumpDefrost",
        129: "HeatPumpPostRun",
        130: "ElectricalHeaterOff",
        131: "ElectricalHeaterPhaseOneActive",
        132: "ElectricalHeaterPhaseTwoActive",
        133: "ElectricalHeaterPhaseThreeActive",
        134: "FourThreeWayValveIdlePosition",
        135: "FourThreeWayValveDefrostPosition",
        136: "FourThreeWayValveRoomSpaceClimateOneTwoPosition",
        137: "ControlLoopHeatingStateStartup",
        138: "ControlLoopHeatingStateRun",
        139: "ControlLoopHeatingStateShutdown",
        140: "ControlLoopDhwStateStartup",
        141: "ControlLoopDhwStateRun",
        142: "ControlLoopDhwStateShutdown",
        143: "ControlLoopCoolingStateStartup",
        144: "ControlLoopCoolingStateRun",
        145: "ControlLoopCoolingStateShutdown",
        146: "ControlLoopDefrostStateStartup",
        147: "ControlLoopDefrostStatePrepareDefrostEnergy",
        148: "ControlLoopDefrostStateDefrosting",
        149: "ControlLoopDefrostStateShutdown",
        150: "ControlLoopBufferUnloadStateStartup",
        151: "ControlLoopBufferUnloadStateRun",
        152: "ControlLoopBufferUnloadStateShutdown",
        153: "AllControlLoopsIdle",
        154: "NoBurnerOperationDueToInsufficientWaterFlow",
        155: "HeatingRoomSetpointActive",
        156: "ReducedHeatingRoomSetpointActive",
        157: "CoolingSetpointActive",
        158: "ReducedCoolingSetpointActive",
        159: "HumidityRoomSetpointActive",
        160: "DomesticHotWaterSetpointActive",
        161: "FillingActive",
        162: "VentingActive",
        163: "ApplicationSoftwareSystemStateInactive",
        164: "ApplicationSoftwareSystemStateServiceStandby",
        165: "ApplicationSoftwareSystemStateControl",
        166: "ComfortEnsuringModeActive",
        167: "ActuatorTestModeActive",
        168: "VentilationBypassOpen",
        169: "ExternalSafetyEquipmentOneFailureSignalInput",
        170: "ExternalSafetyEquipmentTwoFailureSignalInput",
        171: "ExternalSafetyEquipmentThreeFailureSignalInput",
        172: "ServiceStateFilterExchangeActive",
        173: "ServiceStateAirVolumeFlowBalancingActive",
        174: "Reuse",
        175: "ReuseOne",
        176: "RefrigerantCycleRequestForDefrost",
        177: "ReuseTwo",
        178: "ReuseThree",
        179: "ReuseFour",
        180: "ReuseFive",
        181: "PassiveFrostProtectionMixerCircuitOne",
        182: "PassiveFrostProtectionMixerCircuitTwo",
        183: "PassiveFrostProtectionMixerCircuitThree",
        184: "PassiveFrostProtectionMixerCircuitFour",
        185: "PassiveFrostProtectionElectricalHeater",
        186: "PassiveFrostProtectionDomesticHotWaterCylinder",
        187: "PassiveFrostProtectionHeatEngine",
        188: "PassiveFrostProtectionHeatingCoolingBuffer",
        189: "PassiveFrostProtectionHeatingBuffer",
        190: "PassiveFrostProtectionCoolingBuffer",
        191: "ElectronicControlUnitSafeStateOverTheAirIsActive",
        192: "ElectronicControlUnitSafeStateCommissioningIsActive",
        193: "ExternalHeaterActive",
        194: "ReuseSix",
        195: "SmartGridLock",
        196: "PowerSupplierLock",
        197: "ClimateCircuitOneHeatingDemand",
        198: "ClimateCircuitOneCoolingDemand",
        199: "ClimateCircuitTwoHeatingDemand",
        200: "ClimateCircuitTwoCoolingDemand",
        201: "ClimateCircuitThreeHeatingDemand",
        202: "ClimateCircuitThreeCoolingDemand",
        203: "ClimateCircuitFourHeatingDemand",
        204: "ClimateCircuitFourCoolingDemand",
        205: "BufferHeatingDemand",
        206: "BufferCoolingDemand",
        207: "DomesticHotWaterDemand",
        208: "HeatPumpDomesticHotWaterLoadingActive",
        209: "FillingAborted",
        210: "VentingAborted",
        211: "FillingFinished",
        212: "VentingFinished",
        213: "SystemCommissioningActivated",
        214: "SystemCommissioningAborted",
        215: "SystemCommissioningFinished",
        216: "FunctionTestModeActive",
        217: "ElectHeaterPhaseOneDeactivated",
        218: "ElectHeaterPhaseTwoDeactivated",
        219: "ElectHeaterPhaseThreeDeactivated",
        220: "RefrigerantCycleAppStateOff",
        221: "RefrigerantCycleAppStateHeatingStartup",
        222: "RefrigerantCycleAppStateCoolingStartup",
        223: "RefrigerantCycleAppStateDefrostStartup",
        224: "RefrigerantCycleAppStateHeatingControl",
        225: "RefrigerantCycleAppStateCoolingControl",
        226: "RefrigerantCycleAppStateDefrostControl",
        227: "RefrigerantCycleAppStateNaturalDefrost",
        228: "RefrigerantCycleAppStateStopping",
        229: "RefrigerantCycleAppStateTransitionHeatingToCooling",
        230: "RefrigerantCycleAppStateTransitionCoolingToHeating",
        231: "RefrigerantCycleAppStateTransitionDefrostToHeating",
        232: "RefrigerantCycleAppStateTransitionHeatingToNaturalDefrost",
        233: "RefrigerantCycleAppStateTransitionNaturalDefrostToHeating",
        234: "RefrigerantCycleAppStatePumpDownStartup",
        235: "RefrigerantCycleAppStatePumpDownControl",
        236: "RefrigerantCycleAppStatePumpDownStopping",
        237: "RefrigerantCycleAppStateManual",
        238: "RefrigerantCycleAppStateAlarm",
        239: "RefrigerantCycleAppStateWaiting",
        240: "RefrigerantCycleAppStateStandby",
        241: "RefrigerantCycleAppStateGridOperatorLock",
        242: "RefrigerantCycleAppStatePreStart",
        243: "RefrigerantCycleAppStatePostStop",
        244: "RefrigerantCycleAppStateUnintialized",
        245: "CompressorManualModeActivated",
        246: "CompressorManualModeDeactivated",
        247: "CompressorMaxEngineRoomTemperatureReached",
        248: "CompressorMaxEngineRoomTemperatureQuit",
        249: "CompressorMaxPressureDiffZoneTwoReached",
        250: "CompressorMaxPressureDiffZoneTwoQuit",
        251: "CompressorMaxCondensingPressureZoneThreeReached",
        252: "CompressorMaxCondensingPressureZoneThreeQuit",
        253: "CompressorStartup",
        254: "CompressorStartupFinished",
        255: "CompressorMaxEvaporatingTemperatureZoneFiveReached",
        256: "CompressorMaxEvaporatingTemperatureZoneFiveQuit",
        257: "CompressorFixLimitedSetpointToActualSpeedReached",
        258: "CompressorFixLimitedSetpointToActualSpeedQuit",
        259: "CompressorMaxDischargeTemperatureControlActivated",
        260: "CompressorMaxDischargeTemperatureControlDeactivated",
        261: "CompressorMinEvaporatingPressureZoneEightReached",
        262: "CompressorMinEvaporatingPressureZoneEightQuit",
        263: "CompressorFlowTemperatureControlActivated",
        264: "CompressorFlowTemperatureControlDeactivated",
        265: "CompressorMaximumSpeedDueToCondensingPressureActivated",
        266: "CompressorMaximumSpeedDueToCondensingPressureDeactivated",
        267: "CompressorMaxLimitedSpeedActivated",
        268: "CompressorMaxLimitedSpeedDeactivated",
        269: "CompressorNoiseReductionModeActivated",
        270: "CompressorNoiseReductionModeDeactivated",
        271: "CompressorMinSpeedIncreaseHeatingActivated",
        272: "CompressorMinSpeedIncreaseHeatingDeactivated",
        273: "CompressorMinSpeedDueToCondensingPressureActivated",
        274: "CompressorMinSpeedDueToCondensingPressureDeactivated",
        275: "CompressorMinLimitedSpeedActivated",
        276: "CompressorMinLimitedSpeedDeactivated",
        277: "CompressorIdle",
        278: "CompressorInputCurrentSpeedDropProtectionActivated",
        279: "CompressorInputCurrentSpeedDropProtectionDeactivated",
        280: "CompressorCurrentSpeedDropProtectionActivated",
        281: "CompressorCurrentSpeedDropProtectionDeactivated",
        282: "CompressorInternalPowerModulTemperatureSpeedDropProtectionActivated",
        283: "CompressorInternalPowerModulTemperatureSpeedDropProtectionDeactivated",
        284: "CompressorPowerFactorCorrectionTemperatureSpeedDropProtectionActivated",
        285: "CompressorPowerFactorCorrectionTemperatureSpeedDropProtectionDeactivated",
        286: "CompressorFieldWeakingProtectionActivated",
        287: "CompressorFieldWeakingProtectionDeactivated",
        288: "CompressorEngineRoomControlActivated",
        289: "CompressorEngineRoomControlDeactivated",
        290: "CompressorInverterParameterReset",
        291: "CompressorInverterDriveFaultActivated",
        292: "CompressorInverterDriveFaultDeactivated",
        293: "CompressorInverterReStartupActivated",
        294: "CompressorInverterReStartupDeactivated",
        295: "CompressorInverterSpeedStableActivated",
        296: "CompressorInverterSpeedStableDeactivated",
        297: "CompressorInverterSpeedLimitProtectionActivated",
        298: "CompressorInverterSpeedLimitProtectionDeactivated",
        299: "CompressorInverterParameterReadingStart",
        300: "CompressorInverterParameterReadingFinished",
        301: "ExpansionValveOneIdle",
        302: "ExpansionValveOneCalibrationActivated",
        303: "ExpansionValveOneCalibrationDeactivated",
        304: "ExpansionValveOnePressureEqualizationActivated",
        305: "ExpansionValveOnePressureEqualizationDeactivated",
        306: "ExpansionValveOneStartupActivated",
        307: "ExpansionValveOneStartupDeactivated",
        308: "ExpansionValveOneOpenLoopControlActivated",
        309: "ExpansionValveOneOpenLoopControlDeactivated",
        310: "ExpansionValveOneSuperHeatControlActivated",
        311: "ExpansionValveOneSuperHeatControlDeactivated",
        312: "ExpansionValveOneSubcoolingControlActivated",
        313: "ExpansionValveOneSubcoolingControlDeactivated",
        314: "ExpansionValveOneDischargeTemperatureControlActivated",
        315: "ExpansionValveOneDischargeTemperatureControlDeactivated",
        316: "ExpansionValveOneFullyOpenedActivated",
        317: "ExpansionValveOneFullyOpenedDeactivated",
        318: "ExpansionValveOneHoldOnActivated",
        319: "ExpansionValveOneHoldOnDeactivated",
        320: "ExpansionValveOneManualModeActivated",
        321: "ExpansionValveOneManualModeDeactivated",
        322: "ExpansionValveOneMaxEvaporatingPressureControlActivated",
        323: "ExpansionValveOneMaxEvaporatingPressureControlDeactivated",
        324: "ExpansionValveOneMinEvaporatingPressureControlActivated",
        325: "ExpansionValveOneMinEvaporatingPressureControlDeactivated",
        326: "ExpansionValveOneMaxSuctionSuperheatControlActivated",
        327: "ExpansionValveOneMaxSuctionSuperheatControlDeactivated",
        328: "ExpansionValveOneMaxSubcoolingControlActivated",
        329: "ExpansionValveOneMaxSubcoolingControlDeactivated",
        330: "ExpansionValveOneDischargeSuperheatControlActivated",
        331: "ExpansionValveOneDischargeSuperheatControlDeactivated",
        332: "ExpansionValveTwoIdle",
        333: "ExpansionValveTwoCalibrationActivated",
        334: "ExpansionValveTwoCalibrationDeactivated",
        335: "ExpansionValveTwoPressureEqualizationActivated",
        336: "ExpansionValveTwoPressureEqualizationDeactivated",
        337: "ExpansionValveTwoStartupActivated",
        338: "ExpansionValveTwoStartupDeactivated",
        339: "ExpansionValveTwoOpenLoopControlActivated",
        340: "ExpansionValveTwoOpenLoopControlDeactivated",
        341: "ExpansionValveTwoSuperHeatControlActivated",
        342: "ExpansionValveTwoSuperHeatControlDeactivated",
        343: "ExpansionValveTwoSubcoolingControlActivated",
        344: "ExpansionValveTwoSubcoolingControlDeactivated",
        345: "ExpansionValveTwoDischargeTemperatureControlActivated",
        346: "ExpansionValveTwoDischargeTemperatureControlDeactivated",
        347: "ExpansionValveTwoFullyOpenedActivated",
        348: "ExpansionValveTwoFullyOpenedDeactivated",
        349: "ExpansionValveTwoHoldOnActivated",
        350: "ExpansionValveTwoHoldOnDeactivated",
        351: "ExpansionValveTwoManualModeActivated",
        352: "ExpansionValveTwoManualModeDeactivated",
        353: "ExpansionValveTwoMaxEvaporatingPressureControlActivated",
        354: "ExpansionValveTwoMaxEvaporatingPressureControlDeactivated",
        355: "ExpansionValveTwoMinEvaporatingPressureControlActivated",
        356: "ExpansionValveTwoMinEvaporatingPressureControlDeactivated",
        357: "ExpansionValveTwoMaxSuctionSuperheatControlActivated",
        358: "ExpansionValveTwoMaxSuctionSuperheatControlDeactivated",
        359: "ExpansionValveTwoMaxSubcoolingControlActivated",
        360: "ExpansionValveTwoMaxSubcoolingControlDeactivated",
        361: "ExpansionValveTwoDischargeSuperheatControlActivated",
        362: "ExpansionValveTwoDischargeSuperheatControlDeactivated",
        363: "HeatPumpPrimaryPumpOneOff",
        364: "HeatPumpPrimaryPumpOneManualModeActivated",
        365: "HeatPumpPrimaryPumpOneManualModeDeactivated",
        366: "HeatPumpPrimaryPumpOneControlModeActivated",
        367: "HeatPumpPrimaryPumpOneControlModeDeactivated",
        368: "HeatPumpPrimaryPumpOneMaxEvaporatingPressureControlActivated",
        369: "HeatPumpPrimaryPumpOneMaxEvaporatingPressureControlDeactivated",
        370: "HeatPumpPrimaryPumpOneDefrostAvoidingModeActivated",
        371: "HeatPumpPrimaryPumpOneDefrostAvoidingModeDeactivated",
        372: "HeatPumpPrimaryPumpTwoOff",
        373: "HeatPumpPrimaryPumpTwoManualModeActivated",
        374: "HeatPumpPrimaryPumpTwoManualModeDeactivated",
        375: "HeatPumpPrimaryPumpTwoControlModeActivated",
        376: "HeatPumpPrimaryPumpTwoControlModeDeactivated",
        377: "HeatPumpPrimaryPumpTwoMaxEvaporatingPressureControlActivated",
        378: "HeatPumpPrimaryPumpTwoMaxEvaporatingPressureControlDeactivated",
        379: "HeatPumpPrimaryPumpTwoDefrostAvoidingModeActivated",
        380: "HeatPumpPrimaryPumpTwoDefrostAvoidingModeDeactivated",
        381: "BaseHeaterActivated",
        382: "BaseHeaterDeactivated",
        383: "CrankCaseHeaterActivated",
        384: "CrankCaseHeaterDeactivated",
        385: "FanDuctHeaterActivated",
        386: "FanDuctHeaterDeactivated",
        387: "RefrigerantCycleOperationModeValveSwitchToHeating",
        388: "RefrigerantCycleOperationModeValveSwitchToCooling",
        389: "ExternalHeaterDeactivated",
        390: "BivalenzMixerForExternalSupportActivated",
        391: "BivalenzMixerForExternalSupportDeactivated",
        392: "RefrigerantCycleAppStateTransitionHeatingToDefrost",
        393: "ActiveFrostProtectionMixerCircuitOne",
        394: "ActiveFrostProtectionMixerCircuitTwo",
        395: "ActiveFrostProtectionMixerCircuitThree",
        396: "ActiveFrostProtectionMixerCircuitFour",
        397: "ActiveFrostProtectionElectricalHeater",
        398: "ActiveFrostProtectionDomesticHotWaterCylinder",
        399: "ActiveFrostProtectionHeatEngine",
        400: "ActiveFrostProtectionHeatingCoolingBuffer",
        401: "ActiveFrostProtectionHeatingBuffer",
        402: "ActiveFrostProtectionCoolingBuffer",
        403: "Unused"
    },

    "Infos" : {
        0: "NoInfo",
        1: "EcoModeIsActive",
        2: "ChimneySweeperIsActive",
        3: "ModulationBlockingTimeIsActive",
        4: "LimpHomeModeIsActive",
        5: "UnreadyInstallationWizard",
        6: "UnreadySparePartCase",
        7: "CloudCommunicationDisrupted",
        8: "ExternalPowerOff",
        9: "FloorDryingIsActive",
        10: "DomesticHotWaterRunningTimeLimitation",
        11: "GasAirRatioSystemCalibrationActive",
        12: "SolarHeatingSupportIsActive",
        13: "IgnitionFailureOnStopping",
        14: "FlameOutDuringFuelProcessorPurge",
        15: "ProcessWaterPumpFailure",
        16: "ProcessWaterPumpInStopping",
        17: "ReformingThermocoupleTemperatureLow",
        18: "StoppingReformingThermocoupleShortCirctuit",
        19: "ShiftCatalystThermocoupleLowTemperatureInStopping",
        20: "ShiftCatalystThermocoupleShortCircuitInStopping",
        21: "PreferedOxidationTemperatureSensorLowTemperatureInStopping",
        22: "PreferedOxidationTemperatureSensorHighTemperatureInStopping",
        23: "InletWaterLowTemperature",
        24: "InletWaterHighTemperatureInStopping",
        25: "OutletWaterTemperature",
        26: "OutletWaterHighTemperatureInStopping",
        27: "CombustionAirFlowMeterBFailure",
        28: "CombustionAirLineFailure",
        29: "CombustionAirFanBFailure",
        30: "CirculationPumpFailure",
        31: "CoolingWaterCirculationPumpFailure",
        32: "FuelProcessorElectricalHeaterFailure",
        33: "FuelProcessorElectricalHeaterOffFailure",
        34: "FuelProcessorElectricalHeaterOnFailure",
        35: "DesulfurizingHeaterFailure",
        36: "DesulfurizingHeaterOffFailure",
        37: "DesulfurizingHeaterOnFailure",
        38: "SystemOutletTemperature",
        39: "SystemOutletTemperatureHigh",
        40: "SystemOutletTemperatureHighInStopping",
        41: "CoolingWaterTankThermistorHighTemperatureInStopping",
        42: "GasFlowMeterHighFlowRate",
        43: "PreferentialOxidationAirFlowMeterFailureInGenerating",
        44: "PreferentialOxidationAirBlowerFailureInGenerating",
        45: "PreferentialOxidationAirBlowPath",
        46: "PreferentialOxidationAirNeedleValveFailure",
        47: "PreferentialOxidationAirFlowMeterFailureOnStartUp",
        48: "PreferentialOxidationAirBlowerFailureOnStartUp",
        49: "PreferentialOxidationAirFlowMeterFailureInStopping",
        50: "BoosterPumpOverLimit",
        51: "BoosterPumpUnderLimit",
        52: "IgniterDisconnection",
        53: "ExternalControlActive",
        54: "CheckVentilationFilter",
        55: "FuelCellDomestichotWaterMaximumTemperature",
        56: "ExternalHeatDemandActive",
        57: "ExternalLockActive",
        58: "IncorrectPasswordForWifi",
        59: "ParameterRestored",
        60: "KeyPadLookSet",
        61: "DisplayOrientationRotated",
        62: "WindowOpenDetection",
        63: "RefrigerationCircuitNotReadyForOperation",
        64: "FREE",
        65: "RecalibrationInProgress",
        66: "BatteryStateOfHealthBelowEightyPercent",
        67: "ZigbeeCommunicationDeactivated",
        68: "OperatingHoursCentralHeatingPump",
        69: "OperatingHoursMixerTwoCircuitPump",
        70: "InverterAcGridOverCurrent",
        71: "InverterAcGridOverVoltage",
        72: "InverterAcGridUnderVoltage",
        73: "InverterDcLinkOverVoltage",
        74: "InverterDcLinkUnderVoltage",
        75: "InverterBridgeOverTemperature",
        76: "InverterPowerFactorCorrectionOverTemperature",
        77: "InverterSoftwarePowerFactorCorrectionOverCurrent",
        78: "InverterInputCurrentSpeedDropProtection",
        79: "InverterCompressorCurrentSpeedDropProtection",
        80: "InverterFieldWeakeningSpeedDropProtection",
        81: "InverterBridgeTemperatureDerating",
        82: "InverterPowerFactorCorrectionTemperatureDerating",
        83: "FourThreeWayValveMinimumMassflowControl",
        84: "FourThreeWayValveMinimumReturnTemperatureControl",
        85: "ControlledLowPressureShutOffRefrigerantCircuit",
        86: "ControlledHighPressureShutOffRefrigerantCircuit",
        87: "DomesticHotWaterLoadingWaitingTimeActive",
        88: "FillingCompleted",
        89: "SetSystemTimeForward",
        90: "SetTimeBackward",
        91: "RestoreEepromToDefault",
        92: "ResetEnergyBalanceData",
        93: "BurnerBlockedDueToHeatingPumpMalfunction",
        94: "DeviceServiceUpcoming",
        95: "VentilationFilterExchangeUpcoming",
        96: "UnknownLagDeviceRecognized",
        97: "DeletedNodeIdSerialListOnLead",
        98: "SystemLagDeviceAdded",
        99: "LegionellaProtectionTemperatureReached",
        100: "CompressorMaxCondensionPressureReached",
        101: "CompressorMinEvaporatingPressureHeatingReached",
        102: "CompressorMinEvaporatingPressureCoolingReached",
        103: "CompressorMaxEvaporatingPressureReached",
        104: "CompressorMaxDischargeTemperatueReached",
        105: "CompressorMaxRuntimeAtLowEvaporatingTemperatureReached",
        106: "CompressorMaxPressureDifferenceReached",
        107: "CompressorMaxCondensingTemperature",
        108: "CompressorMaxTorqueReached",
        109: "CompressorMaxEvaporatorTemperatureReached",
        110: "CompressorMInPressureRatioReached",
        111: "CompressorMInEvaporatingTemperatureReached",
        112: "MinimumSecondaryOutletTemperatureReached",
        113: "SmartGridLock",
        114: "NormalOperation",
        115: "SmartGridRecommendedOperation",
        116: "SmartGridForcedOperation",
        117: "HomeEnergyManagementSystemActive",
        118: "FloorHeatingCircuitOneTemperatureLimiterActivated",
        119: "FloorHeatingCircuitTwoTemperatureLimiterActivated",
        120: "NoiseReductionModeActive",
        121: "MixerOneCircuitHumidityProtectionActivated",
        122: "MixerTwoCircuitHumidityProtectionActivated",
        123: "MaximumReturnTemperatureRefrigerantCircuitReached",
        124: "MinimumReturnTemperatureRefrigerantCircuitReached",
        125: "MaximumPrimaryInletTemperatureReached",
        126: "MinimumPrimaryInletTemperatureReached",
        127: "MaximumCompressorPressureDifferenceAtStartReached",
        128: "MinimumOilSumpTemperatureReached",
        129: "PressureImbalanceRefrigerantCircuitFourWayValve",
        130: "RefrigerantCircuitMaximumStartupDurationExceeded",
        131: "MinimumEvaporatingTemperatureReached",
        132: "ResetOutdoorControllerMainUnit",
        133: "ResetCommunicationControlUnit",
        134: "ForcedDefrostingActivated",
        135: "ControlledDefrostingActivated",
        136: "InverterDcOverCurrent",
        137: "LagDeviceDtcReported",
        138: "BackUpPowerFunctionInstalled",
        139: "OnePhaseGridDetected",
        140: "ThreePhaseGridDetected",
        141: "InverterGatewayActive",
        142: "MinimumCompressorOnTimeViolated",
        143: "PowerSupplierLock",
        144: "InverterAcInputZeroCrossing",
        145: "OutdoorUnitOverPowerProtection",
        146: "OverheatingOutdoorHeatExchangerCooling",
        147: "OverheatingIndoorHeatExchangerHeating",
        148: "OverheatingOutdoorHeatExchangerHeating",
        149: "IndoorNonDefrostRequestDuringDeicerProcess",
        150: "IndoorDefrostRequestDuringNonDeicerProcess",
        151: "SecondaryOutletTemperatureCountermeasure",
        152: "LowPressureCountermeasure",
        153: "ElectricalFailureElectronicExpansionValveOneMotor",
        154: "ElectricalFailureElectronicExpansionValveTwoMotor",
        155: "FloorDryingAbortedByUser",
        156: "DefrostAlertDueToLowWaterFlow",
        157: "DesiredCompressorOutletTemperatureHeatingExceeded",
        158: "DesiredCompressorOutletTemperatureCoolingExceeded",
        159: "HeatSinkOverTemperature",
        160: "RoomFrostProtectionDomesticHotWaterHeatPump",
        161: "OffPeakElectricitySignalActive",
        162: "AcknowledgeInformationMessage",
        163: "InfoHasBeenConfirmed"
    },

    "TimeSettingSources" : {
        0: "Local",
        1: "SuperordinateSystem",
        2: "NetworkTimeProtocol",
        3: "TCU"
    },
    
    "RegulationTypes" : {
        0: "Nothing",
        1: "ConstantControlled",
        4: "WeatherByOutsideSensorControlled",
        7: "WeatherByOutsideSensorAndRoomCorrectionControlled",
        10: "ConstantControlledWithExternalThermostat",
        13: "WeatherByOutsideAndZones",
        15: "WeatherByOutsideSensorAndAutomaticAdaptationControlled",
    }, 

    "Priorities" : {
        0: "Off",
        1: "DomesticHotWater",
    },
    
    "RemoteControls" : {
        0: "Nothing",
        48: "RemoteControlOne",
        49: "RemoteControlTwo",
        50: "RemoteControlThree",
        51: "RemoteControlFour",
    },
    
    "BusTypes" : {
        0: "OwnBus",
        1: "PlusBus",
        2: "CanInternal",
        3: "CanExternal",
        4: "InternalUart",
        5: "Zigbee",
        6: "CanRaw",
        7: "Unkown",
        8: "ModBus",
        9: "EEBUS",
        10: "PlusBusTwo",
        11: "ISquaredCBus",
    },  
    
    "MixerCircuitTypes" : {
        0: "NormalCentralHeating",
        1: "UnderFloorCentralHeating",
        2: "SwimmingPool",
        3: "Baseboard",
        4: "Radiator",
        5: "RadiantUnderfloorHeating",
        6: "Snowmelt",
        7: "AirHandler",
        8: "FanCoil",
    }, 
    
    "DigitalInputConfigurations" : { 
        0: "Nothing",
        1: "FaultSignal",
        2: "DhwCirculation",
        3: "FaultSignalAndLocked",
        4: "ExternalHeatDemand",
        5: "ExternalLocked",
        6: "ExternalThermostat",
        7: "RoomTemperatureLimiter",
        8: "CallForHeat",
        9: "SmartGridReadyInputOne",
        10: "SmartGridReadyInputTwo",
        11: "PowerSupplierLock",
        12: "ExternalCoolingDemand",
        13: "PrioritizedDemandDeactivationOtherCircuits",
        14: "LockCircuitOne",
        15: "LockCircuitTwo",
        16: "ExternalDemandAutomatic",
        17: "FanControl",
        18: "FanRpmControl",
        19: "DefrostHeaterControlOne",
        20: "DefrostHeaterControlTwo",
        21: "DayNigthOperation",
        22: "DayNigthOperationPlusDirectControlDigitalOutputOne",
        23: "PermanentHeating",
        24: "DirectControlDryContactOne",
        25: "DirectControlDryContactTwo",
        26: "DirectControlDryContactThree",
        27: "DirectControlDigitalOutputTwentyFourVolt",
    },
}