"""
   Copyright 2023 abnoname
   
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""


E3Infos = {
    0: "NoInfo",
    1: "EcoModeIsActive",
    2: "ChimneySweeperIsActive",
    3: "ModulationBlockingTimeIsActive",
    4: "LimpHomeModeIsActive",
    5: "UnreadyInstallationWizard",
    6: "UnreadySparePartCase",
    7: "CloudCommunicationDisrupted",
    8: "ExternalPowerOff",
    9: "FloorDryingIsActive",
    10: "DomesticHotWaterRunningTimeLimitation",
    11: "GasAirRatioSystemCalibrationActive",
    12: "SolarHeatingSupportIsActive",
    13: "IgnitionFailureOnStopping",
    14: "FlameOutDuringFuelProcessorPurge",
    15: "ProcessWaterPumpFailure",
    16: "ProcessWaterPumpInStopping",
    17: "ReformingThermocoupleTemperatureLow",
    18: "StoppingReformingThermocoupleShortCirctuit",
    19: "ShiftCatalystThermocoupleLowTemperatureInStopping",
    20: "ShiftCatalystThermocoupleShortCircuitInStopping",
    21: "PreferedOxidationTemperatureSensorLowTemperatureInStopping",
    22: "PreferedOxidationTemperatureSensorHighTemperatureInStopping",
    23: "InletWaterLowTemperature",
    24: "InletWaterHighTemperatureInStopping",
    25: "OutletWaterTemperature",
    26: "OutletWaterHighTemperatureInStopping",
    27: "CombustionAirFlowMeterBFailure",
    28: "CombustionAirLineFailure",
    29: "CombustionAirFanBFailure",
    30: "CirculationPumpFailure",
    31: "CoolingWaterCirculationPumpFailure",
    32: "FuelProcessorElectricalHeaterFailure",
    33: "FuelProcessorElectricalHeaterOffFailure",
    34: "FuelProcessorElectricalHeaterOnFailure",
    35: "DesulfurizingHeaterFailure",
    36: "DesulfurizingHeaterOffFailure",
    37: "DesulfurizingHeaterOnFailure",
    38: "SystemOutletTemperature",
    39: "SystemOutletTemperatureHigh",
    40: "SystemOutletTemperatureHighInStopping",
    41: "CoolingWaterTankThermistorHighTemperatureInStopping",
    42: "GasFlowMeterHighFlowRate",
    43: "PreferentialOxidationAirFlowMeterFailureInGenerating",
    44: "PreferentialOxidationAirBlowerFailureInGenerating",
    45: "PreferentialOxidationAirBlowPath",
    46: "PreferentialOxidationAirNeedleValveFailure",
    47: "PreferentialOxidationAirFlowMeterFailureOnStartUp",
    48: "PreferentialOxidationAirBlowerFailureOnStartUp",
    49: "PreferentialOxidationAirFlowMeterFailureInStopping",
    50: "BoosterPumpOverLimit",
    51: "BoosterPumpUnderLimit",
    52: "IgniterDisconnection",
    53: "ExternalControlActive",
    54: "CheckVentilationFilter",
    55: "FuelCellDomestichotWaterMaximumTemperature",
    56: "ExternalHeatDemandActive",
    57: "ExternalLockActive",
    58: "IncorrectPasswordForWifi",
    59: "ParameterRestored",
    60: "KeyPadLookSet",
    61: "DisplayOrientationRotated",
    62: "WindowOpenDetection",
    63: "RefrigerationCircuitNotReadyForOperation",
    64: "FREE",
    65: "RecalibrationInProgress",
    66: "BatteryStateOfHealthBelowEightyPercent",
    67: "ZigbeeCommunicationDeactivated",
    68: "OperatingHoursCentralHeatingPump",
    69: "OperatingHoursMixerTwoCircuitPump",
    70: "InverterAcGridOverCurrent",
    71: "InverterAcGridOverVoltage",
    72: "InverterAcGridUnderVoltage",
    73: "InverterDcLinkOverVoltage",
    74: "InverterDcLinkUnderVoltage",
    75: "InverterBridgeOverTemperature",
    76: "InverterPowerFactorCorrectionOverTemperature",
    77: "InverterSoftwarePowerFactorCorrectionOverCurrent",
    78: "InverterInputCurrentSpeedDropProtection",
    79: "InverterCompressorCurrentSpeedDropProtection",
    80: "InverterFieldWeakeningSpeedDropProtection",
    81: "InverterBridgeTemperatureDerating",
    82: "InverterPowerFactorCorrectionTemperatureDerating",
    83: "FourThreeWayValveMinimumMassflowControl",
    84: "FourThreeWayValveMinimumReturnTemperatureControl",
    85: "ControlledLowPressureShutOffRefrigerantCircuit",
    86: "ControlledHighPressureShutOffRefrigerantCircuit",
    87: "DomesticHotWaterLoadingWaitingTimeActive",
    88: "FillingCompleted",
    89: "SetSystemTimeForward",
    90: "SetTimeBackward",
    91: "RestoreEepromToDefault",
    92: "ResetEnergyBalanceData",
    93: "BurnerBlockedDueToHeatingPumpMalfunction",
    94: "DeviceServiceUpcoming",
    95: "VentilationFilterExchangeUpcoming",
    96: "UnknownLagDeviceRecognized",
    97: "DeletedNodeIdSerialListOnLead",
    98: "SystemLagDeviceAdded",
    99: "LegionellaProtectionTemperatureReached",
    100: "CompressorMaxCondensionPressureReached",
    101: "CompressorMinEvaporatingPressureHeatingReached",
    102: "CompressorMinEvaporatingPressureCoolingReached",
    103: "CompressorMaxEvaporatingPressureReached",
    104: "CompressorMaxDischargeTemperatueReached",
    105: "CompressorMaxRuntimeAtLowEvaporatingTemperatureReached",
    106: "CompressorMaxPressureDifferenceReached",
    107: "CompressorMaxCondensingTemperature",
    108: "CompressorMaxTorqueReached",
    109: "CompressorMaxEvaporatorTemperatureReached",
    110: "CompressorMInPressureRatioReached",
    111: "CompressorMInEvaporatingTemperatureReached",
    112: "MinimumSecondaryOutletTemperatureReached",
    113: "SmartGridLock",
    114: "NormalOperation",
    115: "SmartGridRecommendedOperation",
    116: "SmartGridForcedOperation",
    117: "HomeEnergyManagementSystemActive",
    118: "FloorHeatingCircuitOneTemperatureLimiterActivated",
    119: "FloorHeatingCircuitTwoTemperatureLimiterActivated",
    120: "NoiseReductionModeActive",
    121: "MixerOneCircuitHumidityProtectionActivated",
    122: "MixerTwoCircuitHumidityProtectionActivated",
    123: "MaximumReturnTemperatureRefrigerantCircuitReached",
    124: "MinimumReturnTemperatureRefrigerantCircuitReached",
    125: "MaximumPrimaryInletTemperatureReached",
    126: "MinimumPrimaryInletTemperatureReached",
    127: "MaximumCompressorPressureDifferenceAtStartReached",
    128: "MinimumOilSumpTemperatureReached",
    129: "PressureImbalanceRefrigerantCircuitFourWayValve",
    130: "RefrigerantCircuitMaximumStartupDurationExceeded",
    131: "MinimumEvaporatingTemperatureReached",
    132: "ResetOutdoorControllerMainUnit",
    133: "ResetCommunicationControlUnit",
    134: "ForcedDefrostingActivated",
    135: "ControlledDefrostingActivated",
    136: "InverterDcOverCurrent",
    137: "LagDeviceDtcReported",
    138: "BackUpPowerFunctionInstalled",
    139: "OnePhaseGridDetected",
    140: "ThreePhaseGridDetected",
    141: "InverterGatewayActive",
    142: "MinimumCompressorOnTimeViolated",
    143: "PowerSupplierLock",
    144: "InverterAcInputZeroCrossing",
    145: "OutdoorUnitOverPowerProtection",
    146: "OverheatingOutdoorHeatExchangerCooling",
    147: "OverheatingIndoorHeatExchangerHeating",
    148: "OverheatingOutdoorHeatExchangerHeating",
    149: "IndoorNonDefrostRequestDuringDeicerProcess",
    150: "IndoorDefrostRequestDuringNonDeicerProcess",
    151: "SecondaryOutletTemperatureCountermeasure",
    152: "LowPressureCountermeasure",
    153: "ElectricalFailureElectronicExpansionValveOneMotor",
    154: "ElectricalFailureElectronicExpansionValveTwoMotor",
    155: "FloorDryingAbortedByUser",
    156: "DefrostAlertDueToLowWaterFlow",
    157: "DesiredCompressorOutletTemperatureHeatingExceeded",
    158: "DesiredCompressorOutletTemperatureCoolingExceeded",
    159: "HeatSinkOverTemperature",
    160: "RoomFrostProtectionDomesticHotWaterHeatPump",
    161: "OffPeakElectricitySignalActive",
    162: "AcknowledgeInformationMessage",
    163: "InfoHasBeenConfirmed"

}