"""
  Copyright 2023 abnoname
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
"""

import Open3Ecodecs
from Open3Ecodecs import *

dataIdentifiersVcal = {
    256	: RawCodec(36, "BusIdentification"),
    268	: O3EInt16(9, "FlowTemperatureSensor", signed=True),
    269	: O3EInt16(9, "ReturnTemperatureSensor", signed=True),
    271	: O3EInt16(9, "DomesticHotWaterSensor", signed=True),
    274	: O3EInt16(9, "OutsideTemperatureSensor", signed=True),
    284	: O3EInt16(9, "MixerOneCircuitFlowTemperatureSensor", signed=True),
    285	: O3EInt16(9, "MixerOneCircuitReturnTemperatureSensor", signed=True),
    286	: O3EInt16(9, "MixerTwoCircuitFlowTemperatureSensor", signed=True),
    287	: O3EInt16(9, "MixerTwoCircuitReturnTemperatureSensor", signed=True),
    318	: O3EInt16(9, "WaterPressureSensor"),
    320	: O3EInt16(9, "PrimaryHeatExchangerLiquidTemperatureSensor", signed=True),
    321	: O3EInt16(9, "CompressorInletTemperatureSensor", signed=True),
    322 : O3EInt16(9, "CompressorInletPressureSensor", scale = 100),
    324	: O3EInt16(9, "CompressorOutletTemperatureSensor", signed=True),
    325 : O3EInt16(9, "CompressorOutletPressureSensor", scale = 100),
    354	: O3EInt8(1, "PrimaryHeatExchangerBaseHeater"),
    355	: O3EInt16(9, "SecondaryHeatExchangerLiquidTemperatureSensor", signed=True),
    377	: RawCodec(16, "ViessmannIdentificationNumber"),
    381	: O3EInt8(4, "CentralHeatingPump", offset = 1),
    389	: O3EInt8(1, "ElectronicExpansionValveOneCurrentPositionPercent"),
    391	: O3EInt8(1, "ElectronicExpansionValveTwoCurrentPositionPercent"),
    396	: O3EInt16(2, "DomesticHotWaterTemperatureSetpoint", signed=True),
    424	: O3EInt16(9, "MixerOneCircuitRoomTemperatureSetpoint", signed=True),
    426	: O3EInt16(9, "MixerTwoCircuitRoomTemperatureSetpoint", signed=True),
    428	: O3EInt16(9, "MixerThreeCircuitRoomTemperatureSetpoint", signed=True),
    430	: O3EInt16(9, "MixerFourCircuitRoomTemperatureSetpoint", signed=True),
    497	: RawCodec(5, "DomesticHotWaterCirculationPumpMode"),
    503	: RawCodec(2, "ScaldProtection"),
    504	: RawCodec(14, "DomesticHotWaterSetpointMetaData"),
    874	: RawCodec(3, "LegionellaProtectionTargetTemperatureSetpoint"),
    880	: O3EHeatingCurve(4, "MixerOneCircuitCentralHeatingCurve"),
    881	: O3EHeatingCurve(4, "MixerTwoCircuitCentralHeatingCurve"),
    882	: O3EHeatingCurve(4, "MixerThreeCircuitCentralHeatingCurve"),
    883	: O3EHeatingCurve(4, "MixerFourCircuitCentralHeatingCurve"),
    896	: RawCodec(2, "OutsideTemperatureOffset"),
    897	: O3EInt8(1, "ScreedDryingProfileActivation"),
    901	: O3EInt8(1, "ServiceManagerIsRequired"),
    902	: O3EInt8(1, "MalfunctionIdentification"),
    919	: RawCodec(2, "OutsideTemperatureDampingFactor"),
    933	: O3EInt16(9, "MixerOneCircuitProperty"),
    934	: O3EInt16(9, "MixerTwoCircuitProperty"),
    935	: O3EInt16(9, "MixerThreeCircuitProperty"),
    936	: O3EInt16(9, "MixerFourCircuitProperty"),
    1043	: O3EInt16(5, "AllengraSensor"),
    1085	: RawCodec(4, "DomesticHotWaterHysteresis"),
    1087	: RawCodec(2, "MaximumDomesticHotWaterLoadingTime"),
    1100	: RawCodec(3, "CentralHeatingPumpMinimumMaximumLimit"),
    1101	: RawCodec(3, "DomesticHotWaterPumpMinimumMaximumLimit"),
    1192	: RawCodec(10, "MixerOneCircuitFlowTemperatureMinimumMaximumLimit"),
    1193	: RawCodec(10, "MixerTwoCircuitFlowTemperatureMinimumMaximumLimit"),
    1194	: RawCodec(10, "MixerThreeCircuitFlowTemperatureMinimumMaximumLimit"),
    1195	: RawCodec(10, "MixerFourCircuitFlowTemperatureMinimumMaximumLimit"),
    1240	: O3EInt8(1, "CentralHeatingPumpMode"),
    1339	: O3EInt8(1, "MalfunctionHeatingUnitBlocked"),
    1395	: RawCodec(3, "MixerOneCircuitSummerSavingTemperatureThreshold"),
    1396	: RawCodec(3, "MixerTwoCircuitSummerSavingTemperatureThreshold"),
    1397	: RawCodec(3, "MixerThreeCircuitSummerSavingTemperatureThreshold"),
    1398	: RawCodec(3, "MixerFourCircuitSummerSavingTemperatureThreshold"),
    1415	: O3EInt8(2, "MixerOneCircuitOperationState", offset = 1),
    1416	: O3EInt8(2, "MixerTwoCircuitOperationState", offset = 1),
    1417	: O3EInt8(2, "MixerThreeCircuitOperationState", offset = 1),
    1418	: O3EInt8(2, "MixerFourCircuitOperationState", offset = 1),
    1607	: O3EInt8(1, "MalfunctionUnitBlocked"),
    1769	: O3EInt16(9, "PrimaryInletTemperatureSensor", signed=True),
    1770	: O3EInt16(9, "SecondaryOutletTemperatureSensor", signed=True),
    1773	: O3EInt8(1, "RefrigerantCircuitFourWayValve"),
    1774	: O3EInt8(1, "CompressorCrankCaseHeater"),
    1775	: O3EInt8(1, "PrimaryCircuitFanOne"),
    1776	: O3EInt8(1, "PrimaryCircuitFanTwo"),
    1815	: O3EInt8(1, "ElectricalHeaterPhaseOne"),
    1816	: O3EInt8(1, "ElectricalHeaterPhaseTwo"),
    1817	: O3EInt8(1, "ElectricalHeaterPhaseThree"),
    2256	: O3EInt16(2, "DesiredThermalEnergyDefrost"),
    2259	: O3EInt8(1, "RefrigerationCircuitStatus"),
    2320	: O3EInt8(1, "DomesticHotWaterStatus"),
    2340	: RawCodec(2, "ElectricalHeaterConfiguration"),
    2346	: O3EInt8(1, "CompressorSpeedPercent"),
    2350	: O3EInt8(1, "EnergyManagmentSystemResultingControlState"),
    2351	: O3EInt8(2, "HeatPumpCompressor", offset = 0),
    2369	: O3ECompStat(14, "HeatPumpCompressorStatistical"),
    2370	: O3EAddElHeaterStat(11, "AdditionalElectricHeaterStatistical"),
    2404	: RawCodec(6, "BivalenceControlMode"),
    2405	: RawCodec(6, "MixerOneCircuitConstantFlowSetTemperatureCooling"),
    2406	: RawCodec(6, "MixerTwoCircuitConstantFlowSetTemperatureCooling"),
    2407	: RawCodec(6, "MixerThreeCircuitConstantFlowSetTemperatureCooling"),
    2408	: RawCodec(6, "MixerFourCircuitConstantFlowSetTemperatureCooling"),
    2409	: RawCodec(12, "MixerOneCircuitMinimumMaximumFlowSetTemperatureCooling"),
    2410	: RawCodec(12, "MixerTwoCircuitMinimumMaximumFlowSetTemperatureCooling"),
    2411	: RawCodec(12, "MixerThreeCircuitMinimumMaximumFlowSetTemperatureCooling"),
    2412	: RawCodec(12, "MixerFourCircuitMinimumMaximumFlowSetTemperatureCooling"),
    2426	: RawCodec(6, "MixerOneCircuitRoomEcoFunctionSettings"),
    2427	: RawCodec(6, "MixerTwoCircuitRoomEcoFunctionSettings"),
    2428	: RawCodec(6, "MixerThreeCircuitRoomEcoFunctionSettings"),
    2429	: RawCodec(6, "MixerFourCircuitRoomEcoFunctionSettings"),
    2452	: RawCodec(4, "MixerOneCircuitRoomTemperatureThresholdCooling"),
    2453	: RawCodec(4, "MixerTwoCircuitRoomTemperatureThresholdCooling"),
    2454	: RawCodec(4, "MixerThreeCircuitRoomTemperatureThresholdCooling"),
    2455	: RawCodec(4, "MixerFourCircuitRoomTemperatureThresholdCooling"),
    2457	: O3EInt16(9, "CalculatedOutsideTemperature", signed=True),
    2486	: O3EInt16(4, "CurrentElectricalPowerConsumptionRefrigerantCircuit", scale = 1),
    2487	: O3EInt16(4, "CurrentElectricalPowerConsumptionElectricHeater", scale = 1),
    2488	: O3EInt16(4, "CurrentElectricalPowerConsumptionSystem", scale = 1),
    2494	: O3EInt16(4, "CurrentThermalCapacityRefrigerantCircuit", scale = 1),
    2495	: O3EInt16(4, "CurrentThermalCapacityElectricHeater", scale = 1),
    2496	: O3EInt16(4, "CurrentThermalCapacitySystem", scale = 1),
    2540	: RawCodec(6, "NoiseReductionSettings"),
    2543	: RawCodec(10, "SmartGridTemperatureOffsets"),
    2544	: O3EInt8(1, "EnableElectricalHeaterSmartGridLock"),
    2545	: O3EInt8(1, "EnableElectricalHeaterSmartGridIncreaseMaxDemand"),
    2546	: O3EInt16(9, "MixerOneCircuitRoomTemperatureSetpointCooling", signed=True),
    2547	: O3EInt16(9, "MixerTwoCircuitRoomTemperatureSetpointCooling", signed=True),
    2548	: O3EInt16(9, "MixerThreeCircuitRoomTemperatureSetpointCooling", signed=True),
    2549	: O3EInt16(9, "MixerFourCircuitRoomTemperatureSetpointCooling", signed=True),
    2557	: O3EInt8(1, "HeatPumpState"),
    2560	: O3EInt8(1, "SmartGridFeatureSelection"),
    2569	: O3EInt16(2, "CompressorSpeedRps", scale = 10),
    2626	: O3EInt16(4, "MaximumPowerElectricalHeater", scale = 1),
    2629	: O3EInt16(4, "DesiredThermalCapacity", scale = 1),
    2634	: O3EInt8(1, "NoiseReductionMode"),
    2735	: O3EInt8(1, "FourThreeWayValveValveCurrentPosition"),
    2784	: O3EInt16(9, "SecondaryHeatExchangerVaporPressureSensor", scale = 100),
    2796	: RawCodec(2, "ExternalHeaterConfiguration"),
    2806	: O3EInt8(2, "RefrigerationCircuitOperationMode", offset = 1),
    2853	: RawCodec(2, "ExternalHeaterTimeIntegralThershold"),
    2940	: RawCodec(3, "ExternalHeaterDelayTimer"),
    3015	: O3EInt16(9, "HeatSinkTemperatureSensor", signed=True),
}
