"""
  Copyright 2023 abnoname
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
"""

import Open3Ecodecs
from Open3Ecodecs import *

# Datapoints sourced from ViGuide Demo Mode:
# https://viguide.viessmann.com/installations/10000008?gatewaySerial=7571381-gw-serial&deviceSerial=7690296-device-serial

dataIdentifiersVdens = {
    # HMU Führungsgerät Interner CAN-BUS: 1
    # Heat Management Unit 
    0x680 : {
        "name": "HMU", "tx": 0x680, "rx": 0x690, 
        "dids" : 
        {
            256	: O3EComplexType(36, "BusIdentification", [O3EByteVal(1, "BusAddress"), O3EEnum(1, "BusType", "BusTypes"),O3EByteVal(1, "DeviceProperty"),O3EByteVal(1, "DeviceFunction"), O3ESoftVers(8, "SW-Version"), O3ESoftVers(8, "HW-Version"),O3EUtf8(16, "VIN")]),
            257	: O3EDtcList(122, "StatusDtcList", dtcType ="States"),
            258	: O3EDtcList(122, "StatusDtcHistory", dtcType ="States" ),
            259	: O3EDtcList(122, "InfoDtcList", dtcType ="Infos"),
            260	: O3EDtcList(122, "InfoDtcHistory", dtcType ="Infos"),
            261	: O3EDtcList(122, "ServiceDtcList", dtcType ="Services"),
            262	: O3EDtcList(122, "ServiceDtcHistory", dtcType ="Services"),
            263	: O3EDtcList(122, "WarningDtcList", dtcType ="Warnings"),
            264	: O3EDtcList(124, "WarningDtcHistory", dtcType ="Warnings", subType="History" ),
            265	: O3EDtcList(122, "ErrorDtcList",dtcType ="Errors"),
            266	: O3EDtcList(124, "ErrorDtcHistory", dtcType ="Errors", subType="History"),
            268	: O3EComplexType(9, "FlowTemperatureSensor", [O3EInt16(2, "Vorlauf_Ist", signed=True), O3EInt16(2, "Vorlauf_Min", signed=True), O3EInt16(2, "Vorlauf_Max", signed=True), O3EInt16(2, "Vorlauf_Mittelwert", signed=True)]),
            271	: O3EComplexType(9, "DomesticHotWaterSensor", [O3EInt16(2, "WW_Ist", signed=True), O3EInt16(2, "WW_Min", signed=True), O3EInt16(2, "WW_Max", signed=True), O3EInt16(2, "WW_Mittelwert", signed=True)]),
            272 : RawCodec(10, "DomesticHotWaterFlowSensor"),
            273 : O3EInt16(9, "SolarRoofTemperatureSensor", signed=True),
            274	: O3EComplexType(9, "OutsideTemperatureSensor", [O3EInt16(2, "AT_Ist", signed=True), O3EInt16(2, "AT_Min", signed=True), O3EInt16(2, "AT_Max", signed=True), O3EInt16(2, "AT_Mittelwert", signed=True)]),
            275 : O3EInt16(9, "SolarBottomTemperatureSensor", signed=True),
            277 : O3EInt16(9, "BufferBottomTemperatureSensor", signed=True),
            278 : O3EInt16(9, "BufferMidBottomTemperatureSensor", signed=True),
            279 : O3EInt16(9, "BufferMidTemperatureSensor", signed=True),
            281 : O3EInt16(9, "BufferTopTemperatureSensor", signed=True),
            282 : O3EInt16(9, "HydraulicSeparatorTemperatureSensor", signed=True),
            283 : O3EInt16(9, "HydraulicSeparatorReturnTemperatureSensor", signed=True),
            284	: O3EComplexType(9, "MixerOneCircuitFlowTemperatureSensor", [O3EInt16(2, "Vorlauf_Ist", signed=True), O3EInt16(2, "Vorlauf_Min", signed=True), O3EInt16(2, "Vorlauf_Max", signed=True), O3EInt16(2, "Vorlauf_Mittelwert", signed=True)]),
            286	: O3EComplexType(9, "MixerTwoCircuitFlowTemperatureSensor", [O3EInt16(2, "Vorlauf_Ist", signed=True), O3EInt16(2, "Vorlauf_Min", signed=True), O3EInt16(2, "Vorlauf_Max", signed=True), O3EInt16(2, "Vorlauf_Mittelwert", signed=True)]),
            288	: O3EComplexType(9, "MixerThreeCircuitFlowTemperatureSensor", [O3EInt16(2, "Vorlauf_Ist", signed=True), O3EInt16(2, "Vorlauf_Min", signed=True), O3EInt16(2, "Vorlauf_Max", signed=True), O3EInt16(2, "Vorlauf_Mittelwert", signed=True)]),
            290	: O3EComplexType(9, "MixerFourCircuitFlowTemperatureSensor", [O3EInt16(2, "Vorlauf_Ist", signed=True), O3EInt16(2, "Vorlauf_Min", signed=True), O3EInt16(2, "Vorlauf_Max", signed=True), O3EInt16(2, "Vorlauf_Mittelwert", signed=True)]),
            318	: O3EInt16(9, "WaterPressureSensor"),
            331	: O3EComplexType(9, "FlueGasTemperatureSensor", [O3EInt16(2, "Abgas_Ist", signed=True), O3EInt16(2, "Abgas_Min", signed=True), O3EInt16(2, "Abgas_Max", signed=True), O3EInt16(2, "Abgas_Mittelwert", signed=True)]),
            334 : O3EInt16(9, "MixerOneCircuitRoomTemperatureSensor", signed=True),
            335 : O3EInt16(9, "MixerTwoCircuitRoomTemperatureSensor", signed=True),
            336 : O3EInt16(9, "MixerThreeCircuitRoomTemperatureSensor", signed=True),
            337 : O3EInt16(9, "MixerFourCircuitRoomTemperatureSensor", signed=True),
            360 : O3EInt16(9, "DomesticHotWaterOutletSensor", signed=True),
            364 : O3EInt8(6, "Flame"),
            365 : O3EInt16(42, "FlameStatistical", offset = 38, scale = 1),
            373 : RawCodec(2, "FanTargetSpeed"),
            377	: RawCodec(16, "ViessmannIdentificationNumber"),
            381	: O3EInt8(4, "CentralHeatingPump"),
            382 : RawCodec(5, "UnitsAndFormats"),
            386 : O3EInt8(1, "DiverterValveTargetPosition"),
            392	: RawCodec(4, "DomesticHotWaterPump"),
            396	: O3EInt16(2, "DomesticHotWaterTemperatureSetpoint", signed=True),
            401 : O3EInt16(5, "MixerOneCircuitPump", signed=True),
            402 : O3EInt16(5, "MixerTwoCircuitPump", signed=True),
            403 : O3EInt16(5, "MixerThreeCircuitPump", signed=True),
            404 : O3EInt16(5, "MixerFourCircuitPump", signed=True),
            405 : O3EInt16(5, "MixerFiveCircuitPump", signed=True),
            406 : O3EInt16(5, "MixerSixCircuitPump", signed=True),
            407 : O3EInt16(5, "MixerSevenCircuitPump", signed=True),
            408 : O3EInt16(5, "MixerEightCircuitPump", signed=True),						
            417 : O3EInt8(5, "SolarCircuitPump"),
            424	: O3EComplexType(9, "MixerOneCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            426	: O3EComplexType(9, "MixerTwoCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            428	: O3EComplexType(9, "MixerThreeCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            430	: O3EComplexType(9, "MixerFourCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            432 : O3EComplexType(9, "MixerFiveCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            434 : O3EComplexType(9, "MixerSixCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            436 : O3EComplexType(9, "MixerSevenCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            438 : O3EComplexType(9, "MixerEightCircuitRoomTemperatureSetpoint", [O3EInt16(2, "Raum_Komfort", signed=True), O3EInt16(2, "Raum_Standard", signed=True), O3EInt16(2, "Raum_Reduziert", signed=True)]),
            475 : RawCodec(2, "MixerOneCircuitThreeWayValvePositionPercent"),
            476 : O3EInt8(2,  "MixerTwoCircuitThreeWayValvePositionPercent", signed=True),
            477 : RawCodec(2, "MixerThreeCircuitThreeWayValvePositionPercent"),
            478 : RawCodec(2, "MixerFourCircuitThreeWayValvePositionPercent"),
            491 : RawCodec(2, "DomesticHotWaterCirculationPump"),		
            497	: O3EInt16(5, "DomesticHotWaterCirculationPumpMode", signed=True),
            500 : RawCodec(2, "CentralHeatDemandExternalAc"),
            503	: RawCodec(2, "ScaldProtection"),
            504	: RawCodec(10, "DomesticHotWaterSetpointMetaData"),
            505 : RawCodec(3, "Date"),
            506 : RawCodec(3, "Time"),
            507 : RawCodec(4, "UniversalTimeCoordinated"),
            508 : RawCodec(1, "UniversalTimeCoordinatedOffset"),
            510 : RawCodec(1, "Language"),
            513 : RawCodec(8, "HolidayPhaseCircuitOne"),
            514 : RawCodec(8, "HolidayAtHomePhaseCircuitOne"),
            515 : RawCodec(8, "HolidayPhaseCircuitTwo"),
            516 : RawCodec(8, "HolidayAtHomePhaseCircuitTwo"),
            517 : RawCodec(8, "HolidayPhaseCircuitThree"),
            518 : RawCodec(8, "HolidayAtHomePhaseCircuitThree"),
            519 : RawCodec(8, "HolidayPhaseCircuitFour"),
            520 : RawCodec(8, "HolidayAtHomePhaseCircuitFour"),
            521 : RawCodec(2, "OperatingHoursTillService"),
            522 : RawCodec(4, "ServiceDateNext"),
            524 : RawCodec(2, "ModulationTargetSetpoint"),
            525 : RawCodec(2, "ExternalModulationSetpoint"),
            526 : O3EInt16(2, "ModulationCurrentValue"),
            527 : O3EInt16(2, "FlowTemperatureTargetSetpoint", signed=True),
            528 : RawCodec(2, "ExternalTargetFlowTemperatureSetpoint"),
            531 : O3EOperationState(2, "DomesticHotWaterOperationState"),
            534 : RawCodec(2, "DomesticHotWaterPumpPostRunTime"),
            535 : RawCodec(12, "ObjectElectricalEnergyStatistical"),
            537 : O3EOperationState(2, "ExternalMixerOneCircuitTargetOperationMode"),
            538 : O3EOperationState(2, "ExternalDomesticHotWaterTargetOperationMode"),	
            544 : O3EComplexType(12, "GasConsumptionCentralHeating", [O3EInt16(2, "aktueller_Tag"), O3EInt16(2, "letzte_7_Tage"), O3EInt16(2, "aktueller_Monat"), O3EInt16(2, "letzter_Monat"), O3EInt16(2, "aktuelles_Jahr"), O3EInt16(2, "letztes_Jahr")]),
            545 : O3EComplexType(12, "GasConsumptionDomesticHotWater", [O3EInt16(2, "aktueller_Tag"), O3EInt16(2, "letzte_7_Tage"), O3EInt16(2, "aktueller_Monat"), O3EInt16(2, "letzter_Monat"), O3EInt16(2, "aktuelles_Jahr"), O3EInt16(2, "letztes_Jahr")]),
            548 : RawCodec(24, "EnergyConsumptionCentralHeating"),
            565 : RawCodec(24, "EnergyConsumptionDomesticHotWater"),
            567 : RawCodec(24, "GeneratedElectricity"),
            568 : RawCodec(24, "CoTwoSavings"),
            569 : RawCodec(1, "ResetSensorMinMaxAverageStatistics"),
            570 : RawCodec(1, "ResetStatistics"),
            572 : RawCodec(3, "SetDefaultValuesDate"),
            573 : RawCodec(2, "RemoteReset"),
            576 : RawCodec(3, "SetDeliveryStatusDate"),
            580 : RawCodec(8, "SoftwareVersion"),
            581 : RawCodec(8, "HardwareVersion"),
            592 : RawCodec(6, "MacAddressLan"),
            593 : RawCodec(6, "GatewayMac"),
            596 : RawCodec(1, "CentralHeatingPartLoadPercent"),
            597 : O3EInt8(1, "DomesticHotWaterPartLoadPercent", scale = 1),
            600 : RawCodec(3, "FuelCellReset"),
            602 : O3EInt8(1, "GatewayRemoteLocalNetworkStatus"),
            603 : O3EInt8(1, "GatewayApEnable"),
            604 : RawCodec(76, "GatewayApDataSet"),
            607 : RawCodec(20, "GatewayRemoteIp"),
            616 : O3EInt8(1, "GatewayRemoteEnable"),
            618 : O3EInt8(1, "GatewayRemoteIpStatic"),
            619 : RawCodec(2, "GatewayRemoteScanNetwork"),
            621 : O3EInt8(181, "ObjectContactDetails"),
            622 : RawCodec(181, "CustomerDetails"),
            623 : RawCodec(181, "ServiceEngineer"),
            625 : RawCodec(26, "ObjectDetails"),
            627 : RawCodec(12, "CentralHeatingOneCircuitName"),
            628 : RawCodec(12, "CentralHeatingTwoCircuitName"),
            629 : RawCodec(12, "CentralHeatingThreeCircuitName"),
            630 : RawCodec(12, "CentralHeatingFourCircuitName"),
            631 : RawCodec(12, "CentralHeatingFiveCircuitName"),
            632 : RawCodec(12, "CentralHeatingSixCircuitName"),
            633 : RawCodec(12, "CentralHeatingSevenCircuitName"),
            634 : RawCodec(12, "CentralHeatingEightCircuitName"),
            645 : O3EInt8(1, "GenericAnalogDigitalAccessoryOneModulFunction"),
            646 : O3EInt8(1, "GenericAnalogDigitalAccessoryTwoModulFunction"),
            647 : O3EInt8(1, "GenericAnalogDigitalAccessoryThreeModulFunction"),
            648 : O3EInt8(1, "GenericAnalogDigitalAccessoryFourModulFunction"),
            649 : O3EInt8(1, "GenericAnalogDigitalAccessoryFiveModulFunction"),
            650 : O3EInt8(1, "GenericDigitalAccessoryOneModulFunction"),
            651 : O3EInt8(1, "GenericDigitalAccessoryTwoModulFunction"),
            652 : O3EInt8(1, "GenericDigitalAccessoryThreeModulFunction"),
            653 : O3EInt8(1, "GenericDigitalAccessoryFourModulFunction"),
            654 : O3EInt8(1, "GenericDigitalAccessoryFiveModulFunction"),
            691 : RawCodec(57, "DomesticHotWaterTimeScheduleMonday"),
            692 : RawCodec(57, "DomesticHotWaterTimeScheduleTuesday"),
            693 : RawCodec(57, "DomesticHotWaterTimeScheduleWednesday"),
            694 : RawCodec(57, "DomesticHotWaterTimeScheduleThursday"),
            695 : RawCodec(57, "DomesticHotWaterTimeScheduleFriday"),
            696 : RawCodec(57, "DomesticHotWaterTimeScheduleSaturday"),
            697 : RawCodec(57, "DomesticHotWaterTimeScheduleSunday"),
            726 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleMonday"),
            727 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleTuesday"),
            728 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleWednesday"),
            729 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleThursday"),
            730 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleFriday"),
            731 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleSaturday"),
            732 : RawCodec(57, "DomesticHotWaterCirculationTimeScheduleSunday"),
            761 : RawCodec(57, "MixerOneCircuitTimeScheduleMonday"),
            762 : RawCodec(57, "MixerOneCircuitTimeScheduleTuesday"),
            763 : RawCodec(57, "MixerOneCircuitTimeScheduleWednesday"),
            764 : RawCodec(57, "MixerOneCircuitTimeScheduleThursday"),
            765 : RawCodec(57, "MixerOneCircuitTimeScheduleFriday"),
            766 : RawCodec(57, "MixerOneCircuitTimeScheduleSaturday"),
            767 : RawCodec(57, "MixerOneCircuitTimeScheduleSunday"),
            768 : RawCodec(57, "MixerTwoCircuitTimeScheduleMonday"),
            769 : RawCodec(57, "MixerTwoCircuitTimeScheduleTuesday"),
            770 : RawCodec(57, "MixerTwoCircuitTimeScheduleWednesday"),
            771 : RawCodec(57, "MixerTwoCircuitTimeScheduleThursday"),
            772 : RawCodec(57, "MixerTwoCircuitTimeScheduleFriday"),
            773 : RawCodec(57, "MixerTwoCircuitTimeScheduleSaturday"),
            774 : RawCodec(57, "MixerTwoCircuitTimeScheduleSunday"),
            775 : RawCodec(57, "MixerThreeCircuitTimeScheduleMonday"),
            776 : RawCodec(57, "MixerThreeCircuitTimeScheduleTuesday"),
            777 : RawCodec(57, "MixerThreeCircuitTimeScheduleWednesday"),
            778 : RawCodec(57, "MixerThreeCircuitTimeScheduleThursday"),
            779 : RawCodec(57, "MixerThreeCircuitTimeScheduleFriday"),
            780 : RawCodec(57, "MixerThreeCircuitTimeScheduleSaturday"),
            781 : RawCodec(57, "MixerThreeCircuitTimeScheduleSunday"),
            782 : RawCodec(57, "MixerFourCircuitTimeScheduleMonday"),
            783 : RawCodec(57, "MixerFourCircuitTimeScheduleTuesday"),
            784 : RawCodec(57, "MixerFourCircuitTimeScheduleWednesday"),
            785 : RawCodec(57, "MixerFourCircuitTimeScheduleThursday"),
            786 : RawCodec(57, "MixerFourCircuitTimeScheduleFriday"),
            787 : RawCodec(57, "MixerFourCircuitTimeScheduleSaturday"),
            788 : RawCodec(57, "MixerFourCircuitTimeScheduleSunday"),
            873 : RawCodec(2, "LegionellaProtectionActivation"),
            874	: O3EInt16(2, "LegionellaProtectionTargetTemperatureSetpoint"),
            875 : RawCodec(2, "LegionellaProtectionStartTime"),
            876 : O3EInt8(1, "LegionellaProtectionWeekday"),
            877 : RawCodec(3, "LegionellaProtectionLastSuccessfulStartTime"),
            878 : O3EInt8(1, "LegionellaProtectionLastSuccessfulWeekday"),
            880	: O3EHeatingCurve(4, "MixerOneCircuitCentralHeatingCurve"),
            881	: O3EHeatingCurve(4, "MixerTwoCircuitCentralHeatingCurve"),
            882	: O3EHeatingCurve(4, "MixerThreeCircuitCentralHeatingCurve"),
            883	: O3EHeatingCurve(4, "MixerFourCircuitCentralHeatingCurve"),
            884 : O3EHeatingCurve(4, "MixerFiveCircuitCentralHeatingCurve"),
            885 : O3EHeatingCurve(4, "MixerSixCircuitCentralHeatingCurve"),
            886 : O3EHeatingCurve(4, "MixerSevenCircuitCentralHeatingCurve"),
            887 : O3EHeatingCurve(4, "MixerEightCircuitCentralHeatingCurve"),	            	          
            896	: O3EInt8(2, "OutsideTemperatureOffset"),
            897	: O3EInt8(1, "ScreedDryingProfileActivation"),
            900 : O3EInt8(1, "GatewayRemoteSignalStrength"),
            901	: O3EInt8(1, "ServiceManagerIsRequired"),
            902	: O3EInt8(1, "MalfunctionIdentification"),
            903 : RawCodec(4, "DisplaySettings"),
            906 : RawCodec(3, "ExhaustFlap"),
            908 : O3EInt8(1, "ExternalFaultSignal"),
            912 : RawCodec(5, "DaylightSavingTimeActive"),
            915 : RawCodec(3, "LastBackupDate"),
            917 : RawCodec(20, "RemoteWeatherService"),
            918 : O3EInt8(1, "TradeFairMode"),
            919	: O3EInt16(2, "OutsideTemperatureDampingFactor"),
            920 : RawCodec(36, "ThreeAxisAccelerationSensor"),
            921 : O3EOperationState(2, "ExternalAccessInProgress"),
            924 : O3EInt8(1, "StartUpWizard"),
            925 : RawCodec(5, "FillingVenting"),
            927 : O3EInt8(1, "BuildingType"),
            928 : RawCodec(16, "ElectronicTraceabilityNumber"),
            929 : O3EInt8(1, "GasType"),
            930 : RawCodec(10, "ExternalTargetCentralHeatingFlowSetpointMetaData"),
            931 : RawCodec(10, "DomesticHotWaterFlowSetpointMetaData"),	            	
            933	: O3EComplexType(9, "MixerOneCircuitProperty", [O3EEnum(1,"MixerCircuitType","MixerCircuitTypes"), O3EEnum(1,"BusType","BusTypes"), O3EEnum(1,"RemoteControl","RemoteControls"), O3EEnum(1,"Priority","Priorities"), O3EByteVal(1,"BusAddress"), O3EInt16(2,"FlowTemperatureOffset"), O3EEnum(1,"RegulationType","RegulationTypes"), O3EByteVal(1,"RoomTemperatureCorrectionFactor")]),
            934	: O3EInt16(9, "MixerTwoCircuitProperty"),
            935	: O3EInt16(9, "MixerThreeCircuitProperty"),
            936	: O3EInt16(9, "MixerFourCircuitProperty"),
            937 : O3EInt16(9, "MixerFiveCircuitProperty"),
            938 : O3EInt16(9, "MixerSixCircuitProperty"),
            939 : O3EInt16(9, "MixerSevenCircuitProperty"),
            940 : O3EInt16(9, "MixerEightCircuitProperty"),		
            950 : O3EInt8(4, "SolarCircuitWaterFlowRate", signed=True),
            951	: RawCodec(8, "SolarCircuitExtendedFunctions"),
            952	: RawCodec(51, "HydraulicMatrix"),
            953	: RawCodec(24, "SolarEnergyYield"),
            954	: RawCodec(181, "BusTopologyMatrix"),
            960	: O3EInt8(1, "ExhaustPipeType"),
            961	: O3EInt8(1, "SecurityAlgorithmNumber"),
            962	: RawCodec(8, "BootLoaderVersion"),
            964	: O3EInt8(1, "ActiveDiagnosticSession"),
            987	: O3EInt16(2, "MixerOneCircuitFlowTemperatureTargetSetpoint", signed=True),	
            988 : O3EInt16(2, "MixerTwoCircuitFlowTemperatureTargetSetpoint", signed=True),
            989 : O3EInt16(2, "MixerThreeCircuitFlowTemperatureTargetSetpoint", signed=True),
            990 : O3EInt16(2, "MixerFourCircuitFlowTemperatureTargetSetpoint", signed=True),
            1004 : O3EInt8(1, "CentralHeatingRegulationMode"),
            1006 : RawCodec(3, "TargetQuickMode"),
            1007 : RawCodec(3, "CurrentQuickMode"),
            1008 : RawCodec(3, "MixerOneCircuitTargetQuickMode"),
            1009 : RawCodec(3, "MixerTwoCircuitTargetQuickMode"),
            1010 : RawCodec(3, "MixerThreeCircuitTargetQuickMode"),
            1011 : RawCodec(3, "MixerFourCircuitTargetQuickMode"),
            1024 : RawCodec(3, "MixerOneCircuitCurrentQuickMode"),
            1025 : RawCodec(3, "MixerTwoCircuitCurrentQuickMode"),
            1026 : RawCodec(3, "MixerThreeCircuitCurrentQuickMode"),
            1027 : RawCodec(3, "MixerFourCircuitCurrentQuickMode"),
            1042 : RawCodec(9, "PrimaryHeatExchangerTemperatureSensor"),	            	
            1043 : O3EComplexType(5, "AllengraSensor", [O3EInt16(2, "Volumenstrom_Ist"), O3EInt16(2, "Volumenstrom_Min")]),
            1044 : RawCodec(2, "SecondaryCentralHeatingPump"),
            1047 : RawCodec(11, "TimeSeriesRecordedFlowTemperatureSensor"),
            1084 : RawCodec(4, "FlowTemperatureMinimumMaximumLimit"),	
            1085 : O3EInt16(4, "DomesticHotWaterHysteresis"),
            1087 : O3EInt8(2, "MaximumDomesticHotWaterLoadingTime"),
            1093 : RawCodec(2, "ExhaustPipeLength"),
            1096 : RawCodec(1, "ResetEnergyManagerDataCollector"),
            1097 : RawCodec(16, "ElectricityPrice"),
            1098 : RawCodec(20, "GasProperties"),	         	
            1100 : O3EInt8(3, "CentralHeatingPumpMinimumMaximumLimit"),
            1101 : O3EInt8(3, "DomesticHotWaterPumpMinimumMaximumLimit", offset = 2),
            1102 : O3EInt8(3, "MixerOneCircuitPumpMinimumMaximumLimit"),
            1103 : O3EInt8(3, "MixerTwoCircuitPumpMinimumMaximumLimit"),
            1104 : O3EInt8(3, "MixerThreeCircuitPumpMinimumMaximumLimit"),
            1105 : O3EInt8(3, "MixerFourCircuitPumpMinimumMaximumLimit"),
            1118 : O3EInt8(3, "SolarCircuitPumpMinimumMaximumLimit"),	
            1125 : O3EInt16(2, "SolarMaximumLoadingTemperature", signed=True),
            1128 : O3EInt16(2, "SolarStagnationHours", signed=True),
            1136 : RawCodec(4, "SolarProperty"),
            1138 : RawCodec(1, "AccentLedBar"),
            1139 : RawCodec(7, "CentralHeatingCurveAdaptionParameter"),
            1165 : RawCodec(1, "BackendConnectionStatus"),
            1166 : RawCodec(5, "ResetDtcHistory"),
            1167 : RawCodec(2, "ExternalDomesticHotWaterTemperatureSetpoint"),
            1172 : RawCodec(14, "SolarCircuitPumpStatistical"),
            1175 : RawCodec(1, "AcknowledgeInfoAlarmMessage"),
            1176 : RawCodec(1, "AcknowledgeWarningAlarmMessage"),
            1177 : RawCodec(1, "AcknowledgeServiceAlarmMessage"),
            1178 : RawCodec(1, "AcknowledgeErrorAlarmMessage"),	
            1190 : O3EInt16(4, "ThermalPower"),
            1191 : RawCodec(1, "FuelCellStatus"),	
            1192 : O3EComplexType(10, "MixerOneCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1193 : O3EComplexType(10, "MixerTwoCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1194 : O3EComplexType(10, "MixerThreeCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1195 : O3EComplexType(10, "MixerFourCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1196 : O3EComplexType(10, "MixerFiveCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1197 : O3EComplexType(10, "MixerSixCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1198 : O3EComplexType(10, "MixerSevenCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1199 : O3EComplexType(10, "MixerEightCircuitFlowTemperatureMinimumMaximumLimit", [O3EInt16(2, "Vorlauf_Minimum", signed=True), O3EInt16(2, "Vorlauf_Maximum", signed=True)]),
            1210 : RawCodec(13, "FuelCellStatistical"),
            1211 : RawCodec(24, "GeneratedCentralHeatingOutput"),
            1214 : RawCodec(2, "ElectricalPowerOutput"),
            1215 : RawCodec(1, "FuelCellState"),
            1216 : RawCodec(1, "FuelCellStateTwo"),
            1217 : RawCodec(1, "FuelCellGenerationMode"),
            1218 : RawCodec(1, "FuelCellInstruction"),
            1220 : RawCodec(1, "FuelCellMode"),
            1221 : RawCodec(1, "FuelCellModeResult"),
            1222 : RawCodec(1, "FuelCellRunRequest"),
            1223 : RawCodec(1, "FuelCellRunRequestResult"),
            1224 : RawCodec(1, "FuelCellStopRequest"),
            1226 : RawCodec(1, "FuelCellProcessNumber"),
            1227 : RawCodec(1, "FuelCellRequestAction"),
            1228 : RawCodec(1, "FuelCellCompletionNotification"),
            1229 : RawCodec(1, "FuelCellGasTypeSetting"),
            1230 : RawCodec(1, "FuelCellCountrySetting"),
            1231 : RawCodec(4, "FuelCellPrimaryPump"),
            1232 : O3EEnum(1, "GenericDigitalInputConfigurationOnBoardOne", "DigitalInputConfigurations"),
            1233 : RawCodec(68, "GatewayRemoteVisibleOneTwo"),
            1234 : RawCodec(68, "GatewayRemoteVisibleThreeFour"),
            1235 : RawCodec(68, "GatewayRemoteVisibleFiveSix"),
            1236 : RawCodec(68, "GatewayRemoteVisibleSevenEight"),
            1237 : RawCodec(68, "GatewayRemoteVisibleNineTen"),
            1238 : RawCodec(31, "AvailableActorSensorComponents"),
            1239 : RawCodec(2, "ActorSensorTest"),
            1240 : O3EInt8(1, "CentralHeatingPumpMode"),
            1263 : RawCodec(2, "DiverterValveBoilerHydraulicTower"),
            1264 : RawCodec(2, "DiverterValveFuelCellHydraulicTower"),
            1265 : RawCodec(8, "FanTargetSpeedMeta"),	           	
            1266 : O3EInt16(8, "DiverterValveStatistical", scale = 1),
            1286 : RawCodec(181, "BusTopologyMatrixTwo"),
            1287 : RawCodec(181, "BusTopologyMatrixThree"),
            1288 : RawCodec(181, "BusTopologyMatrixFour"),
            1289 : RawCodec(181, "BusTopologyMatrixFive"),
            1290 : RawCodec(4, "DomesticHotWaterShiftLoadPump"),
            1294 : RawCodec(124, "EnergyConsumptionCentralHeatingMonthMatrix"),
            1311 : RawCodec(124, "EnergyConsumptionDomesticHotWaterMonthMatrix"),
            1313 : RawCodec(124, "GeneratedElectricityMonthMatrix"),
            1314 : RawCodec(124, "SolarEnergyYieldMonthMatrix"),
            1315 : RawCodec(124, "GeneratedCentralHeatingOutputMonthMatrix"),
            1316 : RawCodec(96, "EnergyConsumptionCentralHeatingYearMatrix"),
            1333 : RawCodec(96, "EnergyConsumptionDomesticHotWaterYearMatrix"),
            1335 : RawCodec(96, "GeneratedElectricityYearMatrix"),
            1336 : RawCodec(96, "SolarEnergyYieldYearMatrix"),
            1337 : RawCodec(96, "GeneratedCentralHeatingOutputYearMatrix"),	
            1339 : O3EInt8(1, "MalfunctionHeatingUnitBlocked"),
            1340 : RawCodec(124, "FuelCellGeneratedHeatOutputMonthMatrix"),
            1341 : RawCodec(96, "FuelCellGeneratedHeatOutputYearMatrix"),
            1342 : RawCodec(124, "GasConsumptionCentralHeatingMonthMatrix"),
            1343 : RawCodec (48, "GasConsumptionCentralHeatingYearMatrix"),
            1344 : RawCodec(124, "GasConsumptionDomesticHotWaterMonthMatrix"),
            1345 : RawCodec(48, "GasConsumptionDomesticHotWaterYearMatrix"),
            1346 : O3EComplexType(12, "HeatEngineStatistical", [O3EInt32(4, "Betriebsstunden", scale = 1), O3EInt32(4, "Brennerstunden", scale = 1), O3EInt32(4, "Brennerstarts", scale = 1)]),
            1347 : RawCodec(10, "ObjectElectricalEnergyStatus"),
            1348 : RawCodec(12, "FuelCellGasConsumption"),
            1349 : RawCodec(124, "FuelCellGasConsumptionMonthMatrix"),
            1350 : RawCodec(48, "FuelCellGasConsumptionYearMatrix"),
            1351 : RawCodec(24, "FeedInEnergy"),
            1352 : RawCodec(124, "FeedInEnergyMonthMatrix"),
            1353 : RawCodec(96, "FeedInEnergyYearMatrix"),
            1354 : RawCodec(6, "ProductionCoverageRate"),
            1355 : RawCodec(62, "ProductionCoverageRateMonthMatrix"),
            1356 : RawCodec(24, "ProductionCoverageRateYearMatrix"),
            1357 : RawCodec(11, "FuelCellOperationTime"),
            1358 : RawCodec(124, "FuelCellOperationTimeMonthMatrix"),
            1359 : RawCodec(48, "FuelCellOperationTimeYearMatrix"),
            1360 : RawCodec(11, "FuelCellRunTime"),
            1361 : RawCodec(124, "FuelCellRunTimeMonthMatrix"),
            1362 : RawCodec(48, "FuelCellRunTimeYearMatrix"),
            1363 : RawCodec(1, "FuelCellTargetOperationMode"),
            1364 : RawCodec(1, "GenericSdioAccessoryOneModulFunction"),
            1367 : RawCodec(2, "FuelCellThermalPower"),
            1371 : RawCodec(6, "DemandCoverageRate"),
            1372 : RawCodec(62, "DemandCoverageRateMonthMatrix"),
            1373 : RawCodec(24, "DemandCoverageRateYearMatrix"),
            1383 : RawCodec(11, "FuelCellBreakdownRate"),
            1384 : RawCodec(124, "FuelCellBreakdownRateMonthMatrix"),
            1385 : RawCodec(48, "FuelCellBreakdownRateYearMatrix"),
            1389 : RawCodec(124, "CoTwoSavingsMonthMatrix"),
            1390 : RawCodec(96, "CoTwoSavingsYearMatrix"),
            1391 : RawCodec(24, "GeneratedDomesticHotWaterOutput"),
            1392 : RawCodec(124, "GeneratedDomesticHotWaterOutputMonthMatrix"),
            1393 : RawCodec(96, "GeneratedDomesticHotWaterOutputYearMatrix"),	
            1394 : O3EInt16(2, "SolarChargingDomesticHotWaterSetpoint", signed=True),
            1395 : O3EInt16(3, "MixerOneCircuitSummerSavingTemperatureThreshold", offset = 1),
            1396 : O3EInt16(3, "MixerTwoCircuitSummerSavingTemperatureThreshold", offset = 1),
            1397 : O3EInt16(3, "MixerThreeCircuitSummerSavingTemperatureThreshold", offset = 1),
            1398 : O3EInt16(3, "MixerFourCircuitSummerSavingTemperatureThreshold", offset = 1),
            1411 : RawCodec(1, "ResetServiceInterval"),	            	            	
            1415 : O3EOperationState(2, "MixerOneCircuitOperationState"),
            1416 : O3EOperationState(2, "MixerTwoCircuitOperationState"),
            1417 : O3EOperationState(2, "MixerThreeCircuitOperationState"),
            1418 : O3EOperationState(2, "MixerFourCircuitOperationState"),
            1419 : O3EOperationState(2, "MixerFiveCircuitOperationState"),
            1420 : O3EOperationState(2, "MixerSixCircuitOperationState"),
            1421 : O3EOperationState(2, "MixerSevenCircuitOperationState"),
            1422 : O3EOperationState(2, "MixerEightCircuitOperationState"),
            1431 : RawCodec(8, "CarbonEmissionSettings"),
            1432 : RawCodec(4, "CentralHeatingPumpPerformance"),
            1434 : RawCodec(1, "ResetFuelCellStatistics"),
            1435 : RawCodec(9, "FuelCellFlowTemperatureSensor"),
            1436 : RawCodec(9, "FuelCellReturnTemperatureSensor"),
            1467 : RawCodec(2, "SafetyRelevantRemoteUnlock"),
            1468 : RawCodec(9, "FuelCellGasPressure"),
            1469 : RawCodec(31, "SensorActuatorTestGroupHeatEngine"),
            1470 : RawCodec(31, "SensorActuatorTestGroupDomesticHotWater"),
            1471 : RawCodec(31, "SensorActuatorTestGroupFuelCell"),
            1472 : RawCodec(31, "SensorActuatorTestGroupHeatingCircuit"),
            1473 : RawCodec(31, "SensorActuatorTestGroupSolar"),
            1492 : RawCodec(4, "SolarCircuitPumpHysteresis"),
            1493 : RawCodec(16, "HeatEnginePerformanceStatistics"),
            1494 : RawCodec(8, "OemProductVersion"),
            1503 : RawCodec(1, "MinimumLoadPercent"),
            1504 : RawCodec(1, "TimeSettingSource"),
            1505 : RawCodec(2, "SolarStagnationTemperatureOffset"),
            1529 : RawCodec(1, "SolarRechargeSuppressionImpact"),
            1533 : RawCodec(2, "InstallationWizardInProgress"),
            1535 : RawCodec(3, "FlueGasSensorTestMode"),
            1536 : RawCodec(3, "PrimaryCircuitWaterFlowTestMode"),
            1537 : RawCodec(3, "ChimneySweeperTestMode"),
            1538 : RawCodec(1, "ZigbeeEnable"),
            1539 : RawCodec(1, "ZigbeeStatus"),
            1540 : RawCodec(26, "ZigbeeIdentification"),
            1541 : RawCodec(5, "LegionellaProtectionPump"),
            1549 : RawCodec(97, "HydraulicMatrixConfiguration"),
            1550 : RawCodec(22, "FunctionMatrix"),
            1551 : RawCodec(1, "FuelCellExternalControl"),
            1553 : RawCodec(6, "ElectronicControlUnitOdxVersion"),
            1554 : RawCodec(2, "HeatingSupport"),
            1555 : RawCodec(6, "MixerOneCircuitFixedValueFlowTemperatureSetpoint"),
            1556 : RawCodec(6, "MixerTwoCircuitFixedValueFlowTemperatureSetpoint"),
            1557 : RawCodec(6, "MixerThreeCircuitFixedValueFlowTemperatureSetpoint"),
            1558 : RawCodec(6, "MixerFourCircuitFixedValueFlowTemperatureSetpoint"),
            1559 : RawCodec(6, "MixerFiveCircuitFixedValueFlowTemperatureSetpoint"),
            1560 : RawCodec(6, "MixerSixCircuitFixedValueFlowTemperatureSetpoint"),
            1561 : RawCodec(6, "MixerSevenCircuitFixedValueFlowTemperatureSetpoint"),
            1562 : RawCodec(6, "MixerEightCircuitFixedValueFlowTemperatureSetpoint"),
            1573 : RawCodec(9, "SystemReturnTemperatureSensor"),
            1585 : RawCodec(2, "IncreasedReturnTemperatureSetpoint"),
            1593 : RawCodec(4, "BufferHysteresis"),
            1594 : RawCodec(3, "LastApplicationUpdate"),
            1595 : RawCodec(8, "ParameterIdentificationVersionFactory"),
            1596 : RawCodec(9, "IncreasedReturnTemperatureSensor"),
            1598 : RawCodec(4, "SolarStaticTemperatureControlHysteresis"),
            1599 : RawCodec(4, "SolarSecondaryDeltaTemperatureHysteresis"),
            1600 : RawCodec(2, "BufferDischargeFunctionThreeWayValvePositionPercent"),
            1601 : RawCodec(1, "FuelCellCondition"),
            1604 : RawCodec(2, "GatewayExternalTargetFlowTemperatureSetpoint"),
            1605 : O3EOperationState(2, "GatewayExternalHeatEngineTargetOperationMode"),
            1606 : RawCodec(8, "IntervalStrategyProperties"),
            1608 : RawCodec(9, "DifferentialTemperatureControllerHeatSourceTemperatureSensor"),
            1609 : RawCodec(9, "DifferentialTemperatureControllerHeatSinkTemperatureSensor"),
            1610 : RawCodec(9, "HeatingSupportBufferTemperatureSensor"),
            1611 : RawCodec(9, "PreheatingReferenceTemperatureSensor"),
            1612 : O3EOperationState(2, "ExternalMixerTwoCircuitTargetOperationMode"),
            1613 : O3EOperationState(2, "ExternalMixerThreeCircuitTargetOperationMode"),
            1614 : O3EOperationState(2, "ExternalMixerFourCircuitTargetOperationMode"),
            1627 : RawCodec(2, "ExternalMixerOneCircuitFixedValueTargetTemperatureSetpoint"),
            1628 : RawCodec(2, "ExternalMixerTwoCircuitFixedValueTargetTemperatureSetpoint"),
            1629 : RawCodec(2, "ExternalMixerThreeCircuitFixedValueTargetTemperatureSetpoint"),
            1630 : RawCodec(2, "ExternalMixerFourCircuitFixedValueTargetTemperatureSetpoint"),
            1643 : RawCodec(2, "MixerOneCircuitCurrentTemperatureSetpoint"),
            1644 : RawCodec(2, "MixerTwoCircuitCurrentTemperatureSetpoint"),
            1645 : RawCodec(2, "MixerThreeCircuitCurrentTemperatureSetpoint"),
            1646 : RawCodec(2, "MixerFourCircuitCurrentTemperatureSetpoint"),
            1659 : RawCodec(3, "EndResultDomesticHotWaterTemperatureSetpoint"),
            1660 : RawCodec(16, "SupportedFeatures"),
            1661 : RawCodec(5, "SolarSecondaryTransferPump"),
            1662 : RawCodec(2, "HeatingSupportBufferThreeWayValvePositionPercent"),
            1663 : RawCodec(41, "TestStatus"),
            1667 : RawCodec(2, "MixerOneCircuitPumpOscillationTime"),
            1668 : RawCodec(2, "MixerTwoCircuitPumpOscillationTime"),
            1669 : RawCodec(2, "MixerThreeCircuitPumpOscillationTime"),
            1670 : RawCodec(2, "MixerFourCircuitPumpOscillationTime"),
            1694 : RawCodec(1, "GatewayEthernetEnable"),
            1695 : RawCodec(21, "GatewayEthernetConfig"),
            1696 : RawCodec(20, "GatewayEthernetIp"),
            1697 : RawCodec(1, "GatewayEthernetNetworkStatus"),
            1706 : RawCodec(1, "GenericMZIOAccessoryTwoModuleFunction"),
            1719 : RawCodec(3, "SolarIntervalFunction"),
            1721 : RawCodec(8, "WaterPressureConfiguration"),
            1728 : RawCodec(2, "ThermostatTerminalOneCircuitPump"),
            1729 : RawCodec(2, "ThermostatTerminalTwoCircuitPump"),
            1730 : RawCodec(2, "ThermostatTerminalThreeCircuitPump"),
            1731 : RawCodec(1, "ExternalLockActive"),
            1732 : RawCodec(6, "FixedRoomTemperatureSetpoint"),
            1749 : RawCodec(176, "TimeSeriesRecordedModulationCurrentValueStepsAndDurationOne"),
            1750 : RawCodec(176, "TimeSeriesRecordedModulationCurrentValueStepsAndDurationTwo"),
            1751 : RawCodec(132, "TimeSeriesRecordedModulationCurrentValueStepsAndDurationThree"),
            1752 : RawCodec(176, "TimeSeriesRecordedFlowTemperatureSensorStepsAndDurationOne"),
            1753 : RawCodec(176, "TimeSeriesRecordedFlowTemperatureSensorStepsAndDurationTwo"),
            1754 : RawCodec(132, "TimeSeriesRecordedFlowTemperatureSensorStepsAndDurationThree"),
            1759 : RawCodec(40, "TimeSeriesRecordedDomesticHotWaterOutletTemperature"),
            1760 : RawCodec(40, "TimeSeriesRecordedCombustionAirInletTemperature"),
            1761 : RawCodec(40, "TimeSeriesRecordedCentralHeatingPumpSpeed"),
            1762 : RawCodec(1, "LowWaterCutOffSignalInput"),
            1763 : RawCodec(1, "LowGasPressureSignalInput"),
            1764 : RawCodec(1, "HighGasPressureSignalInput"),
            1765 : RawCodec(2, "CombustionAirInterlock"),
            1777 : RawCodec(176, "TimeSeriesRecordedFlueGasTemperatureSensorStepsAndDurationOne"),
            1778 : RawCodec(176, "TimeSeriesRecordedFlueGasTemperatureSensorStepsAndDurationTwo"),
            1779 : RawCodec(132, "TimeSeriesRecordedFlueGasTemperatureSensorStepsAndDurationThree"),
            1780 : RawCodec(80, "TimeSeriesRecordedIgnitionTimeSteps"),
            1781 : RawCodec(16, "TimeSeriesRecordedCalibrationCount"),
            1782 : RawCodec(56, "TimeSeriesRecordedMonitoringIonizationMaximum"),
            1783 : RawCodec(120, "TimeSeriesRecordedHeatingBurnerStopEvents"),
            1784 : RawCodec(120, "TimeSeriesRecordedDomesticHotWaterBurnerStopEvents"),
            1785 : RawCodec(40, "TimeSeriesRecordedFlameLossModulation"),
            1786 : RawCodec(52, "TimeSeriesRecordedWaterPressureStagnation"),
            1787 : RawCodec(32, "TimeSeriesRecordedWaterPressurePeaks"),
            1788 : RawCodec(8, "CanInterfaceVersion"),	            	
            1791 : O3EInt8(1, "DiverterValveDefaultPositionConfiguration"),
            1792 : RawCodec(1, "ResetElectricalEnergyHistory"),
            1793 : RawCodec(1, "BurnerPreconditions"),
            1794 : RawCodec(4, "HeatingCircuitHeatDeficit"),
            1795 : RawCodec(1, "FuelCellRuntimePrediction"),
            1796 : RawCodec(2, "DomesticElectricalEnergyConsumption"),
            1797 : RawCodec(2, "PredictionDomesticElectricalEnergyConsumptionNextHour"),
            1798 : RawCodec(1, "FuelCellHoursTillNextStart"),
            1799 : RawCodec(2, "PrimaryCircuitCurrentTemperatureSetpoint"),
            1800 : RawCodec(4, "ResetTimeSeriesRecordingGroups"),	
            2158 : RawCodec(16, "ActivatedFeatures"),
            2166 : RawCodec(1, "MixerOneCircuitExternalHookupDemandInput"),
            2167 : RawCodec(1, "MixerTwoCircuitExternalHookupDemandInput"),
            2168 : RawCodec(1, "MixerThreeCircuitExternalHookupDemandInput"),
            2169 : RawCodec(1, "MixerFourCircuitExternalHookupDemandInput"),
            2229 : RawCodec(1, "ThermostatTerminalOneFunction"),
            2230 : RawCodec(1, "ThermostatTerminalTwoFunction"),
            2231 : RawCodec(1, "ThermostatTerminalThreeFunction"),
            2235 : RawCodec(65, "CascadeSystemConfiguration"),
            2236 : RawCodec(10, "CascadeDeviceSetpoint"),
            2237 : RawCodec(18, "CascadeDeviceStatus"),
            2241 : RawCodec(1, "OutsideTemperatureSensorSource"),	
            2257 : O3EInt16(2, "DomesticHotWaterTemperatureSetpointOffset", signed=True),
            2320 : O3EInt8(1, "DomesticHotWaterStatus"),
            2337 : RawCodec(1, "UltraLowNitroOxideStatusActive"),
            2338 : RawCodec(3, "HighLimitTestMode"),
            2339 : RawCodec(2, "SafetyLimiterThresholdTemperature"),
            2344 : RawCodec(1, "CombustionAirInterlockSettings"),
            2353 : RawCodec(4, "TargetDemandHeatProducer"),
            2382 : RawCodec(2, "PaddleSwitch"),	
            2426 : O3EInt16(6, "MixerOneCircuitRoomEcoFunctionSettings", signed=True, offset = 1),
            2427 : O3EInt16(6, "MixerTwoCircuitRoomEcoFunctionSettings", signed=True, offset = 1),
            2428 : O3EInt16(6, "MixerThreeCircuitRoomEcoFunctionSettings", signed=True, offset = 1),
            2429 : O3EInt16(6, "MixerFourCircuitRoomEcoFunctionSettings", signed=True, offset = 1),
            2445 : RawCodec(2, "SupplementalHeatEngineConfiguration"),
            2446 : RawCodec(4, "HmiWakeupTrigger"),
            2449 : RawCodec(2, "CustomerSpecificDeviceName"),
            2450 : RawCodec(16, "CascadeSequenceCurrentBoiler"),
            2451 : RawCodec(3, "CascadeEmergencyOperationMode"),	           	
            2457 : O3EComplexType(9, "CalculatedOutsideTemperature", [O3EInt16(2, "AT_gedaempft_Ist", signed=True), O3EInt16(2, "AT_gedaempft_Min", signed=True), O3EInt16(2, "AT_gedaempft_Max", signed=True), O3EInt16(2, "AT_gedaempft_Mittelwert", signed=True)]),
            2458 : RawCodec(18, "CascadeDeviceStatusLead"),
            2459 : RawCodec(18, "CascadeDeviceStatusLagOne"),
            2460 : RawCodec(18, "CascadeDeviceStatusLagTwo"),
            2461 : RawCodec(18, "CascadeDeviceStatusLagThree"),
            2462 : RawCodec(18, "CascadeDeviceStatusLagFour"),
            2463 : RawCodec(18, "CascadeDeviceStatusLagFive"),
            2464 : RawCodec(18, "CascadeDeviceStatusLagSix"),
            2465 : RawCodec(18, "CascadeDeviceStatusLagSeven"),
            2466 : RawCodec(18, "CascadeDeviceStatusLagEight"),
            2467 : RawCodec(18, "CascadeDeviceStatusLagNine"),
            2468 : RawCodec(18, "CascadeDeviceStatusLagTen"),
            2469 : RawCodec(18, "CascadeDeviceStatusLagEleven"),
            2470 : RawCodec(18, "CascadeDeviceStatusLagTwelve"),
            2471 : RawCodec(18, "CascadeDeviceStatusLagThirteen"),
            2472 : RawCodec(18, "CascadeDeviceStatusLagFourteen"),
            2473 : RawCodec(18, "CascadeDeviceStatusLagFifteen"),
            2474 : RawCodec(9, "CascadeCommonFlowTemperatureSensor"),
            2475 : O3EInt16(2, "CascadeCommonFlowCurrentTemperatureSetpoint"),
            2490 : RawCodec(1, "StartUpWizardState"),
            2491 : RawCodec(1, "DomesticHotWaterDemandInput"),
            2497 : RawCodec(3, "ResetStatisticalValuesDate"),
            2534 : RawCodec(181, "BusTopologyMatrixSix"),
            2535 : RawCodec(181, "BusTopologyMatrixSeven"),
            2536 : RawCodec(181, "BusTopologyMatrixEight"),
            2551 : RawCodec(6, "FlameBurnerTwo"),
            2552 : RawCodec(2, "ModulationCurrentValueBurnerTwo"),
            2553 : RawCodec(12, "HeatEngineStatisticalBurnerTwo"),
            2564 : RawCodec(1, "HydraulicFlapState"),
            2576 : RawCodec(2, "FuelCellTestModeOne"),
            2577 : RawCodec(6, "FuelCellTestModeTwo"),
            2583 : RawCodec(15, "OxygenProbeProcessValuesBurnerOne"),
            2584 : RawCodec(15, "OxygenProbeProcessValuesBurnerTwo"),
            2635 : RawCodec(8, "BurnerProcessDataFlags"),
            2636 : RawCodec(8, "BurnerTwoProcessDataFlags"),
            2637 : RawCodec(8, "BurnerThreeProcessDataFlags"),
            2758 : RawCodec(1, "GasPressureSwitchErrorReaction"),
            2777 : RawCodec(6, "PrimaryBootLoaderVersion"),
            2778 : RawCodec(2, "ErrorMessageInputSelection"),
            2779 : RawCodec(2, "DeltaTemperaturePumpControlSetpoint"),
            2780 : RawCodec(1, "DomesticHotWaterFlowRangeDwellDuration"), 
            2809 : RawCodec(1, "PumpMinSpeedConfiguration"),
            2810 : RawCodec(1, "CentralHeatingPumpFeedbackSignalHandlingMode"),
            2826 : RawCodec(40, "FuelCellNetworkSystemProtectionErrorHistory"),
            2827 : RawCodec(48, "FuelCellNetworkSystemProtectionParameters"),
            2828 : RawCodec(2, "FuelCellSdCardRecording"),
            2830 : RawCodec(1, "EmergencyMode"),	            	
            2855 : O3EInt16(3, "MixerOneCircuitFrostProtectionConfiguration", signed=True, offset = 1),
            2856 : O3EInt16(3, "MixerTwoCircuitFrostProtectionConfiguration", signed=True, offset = 1),
            2857 : O3EInt16(3, "MixerThreeCircuitFrostProtectionConfiguration", signed=True, offset = 1),
            2858 : O3EInt16(3, "MixerFourCircuitFrostProtectionConfiguration", signed=True, offset = 1),
            2937 : RawCodec(2, "SystemPumpConfiguration"),
            2938 : RawCodec(4, "CascadeSystemPump"),	
        }
    }
}
