"""
   Copyright 2023 abnoname
   
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""


E3Warnings = {
    0: "NoWarningAvailable",
    1: "FrostprotectionLevelOne",
    2: "FrostprotectionLevelTwo",
    3: "LossOfWaterDetection",
    4: "SolarCollectorTemperatureInvalidAtNight",
    5: "FortyFiveDaysToRegularMaintenance",
    6: "ThirtyDaysToRegularMaintenance",
    7: "OverhaulRequired",
    8: "DurationOfLife",
    9: "ChangeVentilationFilter",
    10: "LowGasPressure",
    11: "WaterPressureLevelCriticallyLow",
    12: "RealTimeClockBatteryLow",
    13: "RealTimeClockResetRequired",
    14: "FuelCellRestartSuppressed",
    15: "FiniteStateMachineErrorMode",
    16: "WaterFlowInsufficient",
    17: "LegionellaProtectionTemperatureNotReached",
    18: "HeatCellCondensatDetectionPossible",
    19: "OverHeatingProtectionTemperatureLimiter",
    20: "ServiceIntervalFailed",
    21: "WaterPressureLevelCriticallyHigh",
    22: "ExternalPowerGridSeparation",
    23: "InverterFanFailure",
    24: "ValveMountingModeActive",
    25: "InvalidCommunication",
    26: "InvalidInternalClock",
    27: "LowBattery",
    28: "FloorHeatingThermostateOutputShortCircuit",
    29: "FloorHeatingThermostatInternalFuse",
    30: "FloorHeatingThermostateInletTemperatureMissing",
    31: "FloorHeatingThermostateInletTemperatureShutDown",
    32: "FloorHeatingThermostateCondensationShutDown",
    33: "CscConfigurationChanged",
    34: "NoEnergyFeed",
    35: "InverterSwitchOpen",
    36: "IslandModeFault",
    37: "LostCommunicationBmcuEmcu",
    38: "LostCommunicationEmcuInverter",
    39: "StateInconsistencyBmcuEmcuFunctionalSoftware",
    40: "AmbientTemperatureSensorOvertemperature",
    41: "AmbientTemperatureSensorUndertemperature",
    42: "ControllerBoardTemperatureTooHigh",
    43: "PowerUnitDirectCurrentInputConfigurationIncomplete",
    45: "InverterInputACurrentTooHigh",
    46: "DualHtsDirectCurrentInputConfigurationIncomplete",
    47: "UnassignedInverterTroubleCode",
    48: "HeatCellCondensateJamReductionLimitReached",
    49: "OutOfOptimalWorkingPointCentralHeating",
    50: "OutOfOptimalWorkingPointDomesticHotWater",
    51: "OutOfOptimalWorkingPointCentralCooling",
    52: "FanIntermediateCircuitVoltageHigh",
    53: "FanSensorCableBreak",
    54: "CurrentTargetFanSpeedToLow",
    55: "FanIntermediateCircuitVoltageLow",
    56: "FanElectronicsTemperatureHigh",
    57: "FanMotorTemperatureHigh",
    58: "ValueRangeViolation",
    59: "ExternalAirPressureMonitoringTriggeredFanShutdown",
    60: "ExternalFireProtectionFlapTriggeredFanShutdown",
    61: "ElectricalHeaterReducedOutputPower",
    62: "OpenLoadFeedbackSignalCentralHeatingPump",
    63: "OpenLoadFeedbackSignalMixerTwoCircuitPump",
    64: "DryRunCentralHeatingPump",
    65: "DryRunMixerTwoCircuitPump",
    66: "DecodingErrorFeedbackSignalCentralHeatingPump",
    67: "PumpHeadMismatchCentralHeatingPump",
    68: "DecodingErrorFeedbackSignalMixerTwoCircuitPump",
    69: "PumpHeadMismatchMixerTwoCircuitPump",
    70: "ContaminationHydraulicFilter",
    71: "InverterCompressorOverCurrent",
    72: "InverterSoftwarePowerFactorCorrectionOverVoltage",
    73: "InverterFrequencySpeedMismatch",
    74: "WaterPressureDropDetected",
    75: "HydraulicSystemPressurePeaksDetected",
    76: "FrostprotectionSolarCircuit",
    77: "IgnitionElectrodeAging",
    78: "BypassFlapMonitoringTriggered",
    79: "InvalidTemperatureSensorDriftDetected",
    80: "FanBlockadeDueToIcing",
    81: "ConstraintHeatExchangerOperation",
    82: "VoltageReferenceCalibrationFailure",
    83: "DomesticHotWaterSensorNotPlausible",
    84: "ReturnTemperatureSensorNotPlausible",
    85: "SecondaryOutletTemperatureSensorNotPlausible",
    86: "FlowTemperatureSensorNotPlausible",
    87: "MixerTwoCircuitFlowTemperatureSensorNotPlausible",
    88: "OverheatingOutdoorHeatExchangerCoolingAlert",
    89: "OverheatingIndoorHeatExchangerHeatingAlert",
    90: "CompressorOverheatingProtectionActive",
    91: "ComfortEnsuringModeActive",
    92: "FrostprotectionDomesticHotWater",
    93: "CompressorOutletPressureNotPlausible",
    94: "CompressorInletPressureNotPlausible",
    95: "VolumeFlowSIgnalNotPlausible",
    96: "VentingHydraulicSystemInsufficient",
    97: "FuelCellPowerOnResetRequestAfterFailureReset",
    98: "Reuse",
    99: "SecondaryOutletTemperatureTooLow",
    100: "RestoreEepromToDefault",
    101: "CompressorOutletTemperatureSensorNotPlausible",
    102: "CompressorInletTemperatureSensorNotPlausible",
    103: "DynamicAirVolumeFlowCorrectionLimitViolation",
    104: "LagDeviceDtcReported",
    105: "RTCLostInverter",
    106: "CondtionsIsolationMonitoring",
    107: "InverterSwitchOpenDuringOperation",
    108: "InverterBatteryValuesMissing",
    109: "TargetTemperatureSetpointNotReached",
    110: "TemperatureSensorExternalThermalDeviceOneTemperatureThreasholdReached",
    111: "TemperatureSensorExternalThermalDeviceTwoTemperatureThreasholdReached",
    112: "InverterDcLinkUnderVoltageAlert",
    113: "InverterDcLinkOverVoltageAlert",
    114: "InverterDcOverCurrentAlert",
    115: "InverterAcGridUnderVoltageAlert",
    116: "InverterAcGridOverVoltageAlert",
    117: "InverterAcInputZeroCrossingAlert",
    118: "InverterAcGridOverCurrentAlert",
    119: "OutdoorUnitOverPowerProtectionAlert",
    120: "OutdoorUnitFaultyCompressorStart",
    121: "InverterHeatSinkOverTemperatureAlert",
    122: "LowEvaporatingTemperatureCoolingAlert",
    123: "LowEvaporatingTemperatureHeatingAlert",
    124: "MinimumSecondaryOutletTemperatureAlert",
    125: "OverheatingOutdoorHeatExchangerHeatingAlert",
    126: "IndoorDefrostRequestDuringNonDeicerProcessAlert",
    127: "SecondaryOutletTemperatureCountermeasureAlert",
    128: "LowPressureCountermeasureAlert",
    129: "HeatSinkOverTemperatureAlert",
    130: "LowOutsideTemperatureCoolingAlert",
    131: "HighOutsideTemperatureCoolingAlert",
    132: "LowOutsideTemperatureHeatingAlert",
    133: "HighOutsideTemperatureHeatingAlert",
    134: "LowSaltAlert",
    135: "FlowMonitorAlert",
    136: "ExcessiveWaterUseAlert",
    137: "CompressorUnexpectedStop",
    138: "CompressorDueToHeadache",
    139: "InverterAmbientTemperatureProtection",
    140: "ParameterFileNotSuitable",
    141: "DesiredCompressorOutletTemperatureHeatingExceeded",
    142: "DesiredCompressorOutletTemperatureCoolingExceeded",
    143: "DefrostingProcessAborted",
    144: "NoChangeOffPeakElectricitySignal",
    145: "BypassValveNotWorking",
    146: "BufferTopTemperatureSensorNotPlausible",
    147: "BufferMidTemperatureSensorNotPlausible",
    148: "BufferBottomTemperatureSensorNotPlausible",
    149: "DecodingErrorFeedbackSignalDhwTankLoadPump",
    150: "OpenLoadFeedbackSignalDhwTankLoadPump",
    151: "PumpHeadMismatchDhwPump",
    152: "ViewedWarningList",
    153: "WarningHasBeenConfirmed"
}