"""
    List of variants of data points having other lengths.
    Typically depends on device and/or Viessmann software version.
"""

from open3e.Open3Ecodecs import *

dataIdentifiers = {
    "name": "variants", 
    "Version": "20260527",
    "dids" : 
    {
         627 : { 12: O3EUtf8(12, "CentralHeatingOneCircuitName", acc="ro")},
         628 : { 12: O3EUtf8(12, "CentralHeatingTwoCircuitName", acc="ro")},
         629 : { 12: O3EUtf8(12, "CentralHeatingThreeCircuitName", acc="ro")},
         630 : { 12: O3EUtf8(12, "CentralHeatingFourCircuitName", acc="ro")},
        1006 : { 3: O3EComplexType(3, "TargetQuickMode", [O3EByteVal(1, "SetModeOneTimesHotWater"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], desc="External request for one-time charging of domestic hot water (0: off, 2: one-time request)", info="[Link](https://github.com/open3e/open3e/discussions/318)", acc="rw")},
        1007 : { 3: O3EComplexType(3, "CurrentQuickMode", [O3EByteVal(1, "ModeOneTimesHotWater"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], desc="State of external request for one-time charging of domestic hot water (0: off, 2: on)", info="[Link](https://github.com/open3e/open3e/discussions/318)", acc="ro")},
        1008 : { 3: O3EComplexType(3, "MixerOneCircuitTargetQuickMode", [O3EByteVal(1, "SetModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="rw")},
        1009 : { 3: O3EComplexType(3, "MixerTwoCircuitTargetQuickMode", [O3EByteVal(1, "SetModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="rw")},
        1010 : { 3: O3EComplexType(3, "MixerThreeCircuitTargetQuickMode", [O3EByteVal(1, "SetModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="rw")},
        1011 : { 3: O3EComplexType(3, "MixerFourCircuitTargetQuickMode", [O3EByteVal(1, "SetModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="rw")},
        1024 : { 3: O3EComplexType(3, "MixerOneCircuitCurrentQuickMode", [O3EByteVal(1, "ModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="ro")},
        1025 : { 3: O3EComplexType(3, "MixerTwoCircuitCurrentQuickMode", [O3EByteVal(1, "ModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="ro")},
        1026 : { 3: O3EComplexType(3, "MixerThreeCircuitCurrentQuickMode", [O3EByteVal(1, "ModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="ro")},
        1027 : { 3: O3EComplexType(3, "MixerFourCircuitCurrentQuickMode", [O3EByteVal(1, "ModeParty"), O3EByteVal(1, "State"), RawCodec(1, "Unknown")], acc="ro")},
        1603 : { 12: O3EComplexType(12, "PointOfCommonCouplingPower", [O3EInt16(2, "ActivePower", scale=1.0, signed=True, unit="W", desc="Active Power"), O3EInt16(2, "ReactivePower", scale=1.0, signed=True, unit="VA", desc="Reactive Power"), O3EInt16(2, "ActivePowerDup", scale=1.0, signed=True, unit="W", desc="Active Power Duplicate"), O3EInt16(2, "PadZeros", scale=1.0, signed=True), O3EInt16(2, "ReactivePowerDup", scale=1.0, signed=True, unit="VA", desc="Reactive Power Duplicate"), O3EInt16(2, "PadOnes", scale=1.0, signed=True)], desc="Actual Power at Point of Common Coupling", acc="ro"), # MyHomeMyData, see discussion #315
            },
        1884 : { 85: O3EComplexType(85, "RoomOneProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"), # (str, "name"); (o5cVar, "roomType"); (h5cVar, "lockMode"); (c5cVar, "roomControlAlgorithmType"); (list, "supplyChannel"); (list2, "roomDevices");
            },
        1887 : { 85: O3EComplexType(85, "RoomTwoProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1890 : { 85: O3EComplexType(85, "RoomThreeProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1893 : { 85: O3EComplexType(85, "RoomFourProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1896 : { 85: O3EComplexType(85, "RoomFiveProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1899 : { 85: O3EComplexType(85, "RoomSixProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1902 : { 85: O3EComplexType(85, "RoomSevenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1905 : { 85: O3EComplexType(85, "RoomEightProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1908 : { 85: O3EComplexType(85, "RoomNineProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1911 : { 85: O3EComplexType(85, "RoomTenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1914 : { 85: O3EComplexType(85, "RoomElevenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1917 : { 85: O3EComplexType(85, "RoomTwelveProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1920 : { 85: O3EComplexType(85, "RoomThirteenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1923 : { 85: O3EComplexType(85, "RoomFourteenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1926 : { 85: O3EComplexType(85, "RoomFifteenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1929 : { 85: O3EComplexType(85, "RoomSixteenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1932 : { 85: O3EComplexType(85, "RoomSeventeenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1935 : { 85: O3EComplexType(85, "RoomEightteenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1938 : { 85: O3EComplexType(85, "RoomNineteenProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        1941 : { 85: O3EComplexType(85, "RoomTwentyProperty", [RawCodec(1, "Unknown1"), O3EUtf8(38, "Roomname"), RawCodec(4, "Unknown2"), O3EEnum(1, "Roomtype", "Roomtypes"), RawCodec(1, "Unknown3"), O3EEnum(1, "TemperatureControl", "TemperatureControlLevels"), RawCodec(29, "Unknown4"), O3EEnum(1, "WindowDetection", "WindowDetectionStates"), RawCodec(9, "Unknown5")], acc="ro"),
            },
        2086 : { 68: O3EComplexType(68, "ZigBeeOneDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2089 : { 68: O3EComplexType(68, "ZigBeeTwoDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2092 : { 68: O3EComplexType(68, "ZigBeeThreeDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2095 : { 68: O3EComplexType(68, "ZigBeeFourDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2098 : { 68: O3EComplexType(68, "ZigBeeFiveDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2101 : { 68: O3EComplexType(68, "ZigBeeSixDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2104 : { 68: O3EComplexType(68, "ZigBeeSevenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2107 : { 68: O3EComplexType(68, "ZigBeeEightDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2110 : { 68: O3EComplexType(68, "ZigBeeNineDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2113 : { 68: O3EComplexType(68, "ZigBeeTenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2116 : { 68: O3EComplexType(68, "ZigBeeElevenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2119 : { 68: O3EComplexType(68, "ZigBeeTwelveDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2122 : { 68: O3EComplexType(68, "ZigBeeThirteenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2125 : { 68: O3EComplexType(68, "ZigBeeFourteenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2128 : { 68: O3EComplexType(68, "ZigBeeFifteenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2131 : { 68: O3EComplexType(68, "ZigBeeSixteenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2134 : { 68: O3EComplexType(68, "ZigBeeSeventeenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2137 : { 68: O3EComplexType(68, "ZigBeeEighteenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2140 : { 68: O3EComplexType(68, "ZigBeeNineteenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2143 : { 68: O3EComplexType(68, "ZigBeeTwentyDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2262 : { 68: O3EComplexType(68, "ZigBeeTwentyOneDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2265 : { 68: O3EComplexType(68, "ZigBeeTwentyTwoDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2268 : { 68: O3EComplexType(68, "ZigBeeTwentyThreeDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2271 : { 68: O3EComplexType(68, "ZigBeeTwentyFourDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2274 : { 68: O3EComplexType(68, "ZigBeeTwentyFiveDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2277 : { 68: O3EComplexType(68, "ZigBeeTwentySixDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2280 : { 68: O3EComplexType(68, "ZigBeeTwentySevenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2283 : { 68: O3EComplexType(68, "ZigBeeTwentyEightDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2286 : { 68: O3EComplexType(68, "ZigBeeTwentyNineDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2289 : { 68: O3EComplexType(68, "ZigBeeThirtyDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2292 : { 68: O3EComplexType(68, "ZigBeeThirtyOneDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2295 : { 68: O3EComplexType(68, "ZigBeeThirtyTwoDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2298 : { 68: O3EComplexType(68, "ZigBeeThirtyThreeDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2301 : { 68: O3EComplexType(68, "ZigBeeThirtyFourDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2304 : { 68: O3EComplexType(68, "ZigBeeThirtyFiveDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2307 : { 68: O3EComplexType(68, "ZigBeeThirtySixDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2310 : { 68: O3EComplexType(68, "ZigBeeThirtySevenDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2313 : { 68: O3EComplexType(68, "ZigBeeThirtyEightDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2316 : { 68: O3EComplexType(68, "ZigBeeThirtyNineDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
        2319 : { 68: O3EComplexType(68, "ZigBeeFourtyDeviceCurrentValues", [RawCodec(2, "Unknown1"), O3EInt8(1, "BatteryLevel"), RawCodec(37, "Unknown2"), O3EInt8(1, "SignalLevel", scale=2.55), O3EEnum(1, "ViCareDevice", "ViCareDeviceTypes"), O3EInt8(1, "ActualTemperature", scale=10), O3EEnum(1, "ValvePosition", "ValvePositionLevels"), O3EInt8(1, "Humidity"), RawCodec(3, "Unknown3"),O3EEnum(1,"DeviceDisplayTurned","DeviceDisplayModeStates"),RawCodec(5, "Unknown4"),O3EEnum(1,"DeviceChildLockActive","DeviceChildLockStates"),O3EInt8(1, "DeviceTemperatureSetpoint"),RawCodec(12, "Unknown5")], acc="ro"), # fixed per discussion #235, definition by Backes89
            },
    }
}